### ISSUE TITLE
Upscaling videos

### ISSUE THREAD

**Issue by Smoodie7** [upscayl/upscayl#372] opened 2023-06-29 00:05 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

You can maybe add the possibility to upscale videos, you can just upscale each image in performance mode (and try to make the upscaling coherent through every frames) and then make the upscaled images a video. (it probably will be really slow on classic computers but will be really useful for some users)

**Comment by aaronliu0130** [comment] 2023-06-29 01:33
Duplicate of #79.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-06-29 01:33 UTC
Labels: enhancement

**Comment by djdance** [comment] 2023-11-12 06:51
@aaronliu0130 

It's a pity that it is not planned (yet, I hope)
Many people use **mov2mov** in SD 1.5, and it's 512x512 is very poor even for FHD video production.
If you 'd add this feature, you win the world :-)

p.s. Yes I know one could convert video to pngs .. but.. win the world...
