### ISSUE TITLE
Always getting PNG in Batch mode

### ISSUE THREAD

**Issue by DenTheProgrammer** [upscayl/upscayl#261] opened 2023-04-02 03:36 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Always getting PNG in Batch mode even with JPG selected

### To Reproduce

Run Batch mode with JPG option selected

### Expected Behavior

images should be JPG

### Version/Commit Hash

2.0.1

### OS Specifics

Nvidia RTX 2060

**Comment by aaronliu0130** [comment] 2023-04-03 10:51
Duplicate of #174
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-04-13 23:22 UTC
Labels: bug
