### ISSUE TITLE
[FEATURE] Add support in UI for directly pasting image from clipboard.

### ISSUE THREAD

**Issue by HakaishinShwet** [upscayl/upscayl#885] opened 2024-06-22 15:35 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Many times i wanna process image which i captured in clipboard with grim+slurp and wl-copy combo as i am using linux tiling manager so its much more easier to directly paste image and process it rather than saving and then going to directories and then choosing image. As in chatgpt ui and openwebui we can directly paste screenshot or image from clipboard easily and its fast and smooth adding support for it will be great for many who use utilities which directly capture ss or captured region directly in clipboard and wanna process it directly.
Btw Thankyou for this awesome project devs :-)) 

### Related Problem(s)

:--)

**Comment by aaronliu0130** [comment] 2024-06-25 18:01
We should have this already. What platform are you on?

**Comment by aaronliu0130** [comment] 2024-06-25 18:02
Duplicate of #518

**Closed by aaronliu0130** 2024-06-25 18:02 UTC
Labels: enhancement
