### ISSUE TITLE
Batch Upscale File Format Save Error

### ISSUE THREAD

**Issue by UPSA007** [upscayl/upscayl#201] opened 2023-01-11 11:06 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When I drag and drop any image, it works smoothly as expected. However, when I turn on batch Upscale in order to automate the process the only file format it saves in is png regardless of the selected (png/jpg/webp) format in the advanced options menu. 

### To Reproduce

Turn on batch mode. Select any profile and then select any file format in advanced menu. 

### Expected Behavior

jpg/png/webp files but results in only png upscaled files.

### Version/Commit Hash

2.0.1

### OS Specifics

nvidia rtx 2060, tested both windows 10 and 11

**Comment by NayamAmarshe** [comment] 2023-01-11 11:13
Duplicate of https://github.com/upscayl/upscayl/issues/174

**Closed by NayamAmarshe** 2023-01-11 11:13 UTC
Labels: bug
