### ISSUE TITLE
Web-based translation using [Hosted Weblate](https://hosted.weblate.org/)

### ISSUE THREAD

**Issue by ovari** [upscayl/upscayl#576] opened 2023-11-23 23:47 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Please enable translations to be added using a web-based translation service like [Hosted Weblate](https://hosted.weblate.org/).

### Related Problem(s)

UX/UI improvement.

### Alternatives

[Weblate](https://weblate.org/) is copylefted libre software, used by over 2,500 libre software projects and companies in over 165 countries.

**Comment by aaronliu0130** [comment] 2023-11-24 13:50
Duplicate of #91.
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-11-24 13:50 UTC
Labels: enhancement
