### ISSUE TITLE
Undecodable image error doesn't close

### ISSUE THREAD

**Issue by Crilum** [upscayl/upscayl#269] opened 2023-04-10 22:28 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I tried to upscale an image (.jpg format), and I got an unsupported image error (Which is weird, since it's a perfectly good JPEG)...
I clicked OK.. And it popped right back up.. You can see for yourself in the attached GIF in the Screenshot section.

### To Reproduce

(I'm not exactly sure how to reproduce, but...)
1. Pick a JPEG
2. Use the Ultrasharp model
3. Upscayl
4. Receive error that doesn't go away

### Expected Behavior

Um.. Well no repeating error.. And also probably no error in the first place...

### Version/Commit Hash

2.0.1

### OS Specifics

Intel Integratd Graphics 4600 (Probably?? Other wise it'd be a Radeon HD 8800, I think) and Debian 11

### Screenshots

![Peek 2023-04-10 16-19](https://user-images.githubusercontent.com/91354257/231010209-a3062fb3-c8e3-4e8e-b911-52cdfc97e7a0.gif)

*EDIT*
I realized I'm getting the decode error probably cause of a unsupported GPU..
But the issue still stands, the error shouldn't reappear after getting closed.

**Comment by aaronliu0130** [comment] 2023-04-10 22:45
If you can reproduce this and don’t have logs, you may follow these instructions: Install git and node.js then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by Crilum** [comment] 2023-04-10 22:56
<details>
> upscayl@2.0.1 start
> tsc && electron .

16:49:20.514 › /tmp/upscayl
MESA-INTEL: warning: Haswell Vulkan support is incomplete
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /tmp/upscayl/renderer/babel.config.js

🌼 daisyUI components 2.51.4  https://daisyui.com
  ✔︎ Including:  base, components, 29 themes, utilities
  ❤︎ Support daisyUI:  https://opencollective.com/daisyui 
  
event - compiled client and server successfully in 5s (171 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

16:49:27.025 › 🚀 ICON PATH:  /tmp/upscayl/main/build/icon.png
16:49:27.025 › 🚀 UPSCAYL EXEC PATH:  /tmp/upscayl/resources/linux/bin/upscayl-
16:49:27.026 › 🚀 MODELS PATH:  /tmp/upscayl/resources/models
16:49:27.026 › 🚀 FFMPEG PATH:  /tmp/upscayl/node_modules/upscayl-ffmpeg/bin/linux/x64/ffmpeg
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.2s (284 modules)
16:51:10.417 › Selected File Path:  /home/josh/Pictures/2023/March/_MG_7460.jpg
16:51:17.643 › 🚀 => fileName _MG_7460
16:51:17.644 › 🚀 => fileExt .jpg
ℹ Command:  [
  '-i',
  '/home/josh/Pictures/2023/March/_MG_7460.jpg',
  '-o',
  '/home/josh/Pictures/2023/March/_MG_7460_upscayl_4x_realesrgan-x4plus.png',
  '-s',
  4,
  '-m',
  '/tmp/upscayl/resources/models',
  '-n',
  'realesrgan-x4plus',
  '',
  '-f',
  'png'
]
16:51:17.736 › image upscayl:  MESA-INTEL: warning: Haswell Vulkan support is incomplete

16:51:18.440 › image upscayl:  [0 Intel(R) HD Graphics 4600 (HSW GT2)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
16:51:18.444 › image upscayl:  
[0 Intel(R) HD Graphics 4600 (HSW GT2)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) HD Graphics 4600 (HSW GT2)]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/0
[0 Intel(R) HD Graphics 4600 (HSW GT2)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

16:51:18.445 › image upscayl:  [1 llvmpipe (LLVM 11.0.1, 256 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 llvmpipe (LLVM 11.0.1, 256 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 llvmpipe (LLVM 11.0.1, 256 bits)]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/0
[1 llvmpipe (LLVM 11.0.1, 256 bits)]  subgroup=1  basic=0  vote=0  ballot=0  shuffle=0

16:51:32.049 › image upscayl:  0.00%

16:51:32.060 › image upscayl:  MESA-INTEL: error: ../src/intel/vulkan/anv_device.c:3313: GPU hung on one of our command buffers (VK_ERROR_DEVICE_LOST)
vkQueueSubmit failed -4
0.09%

16:51:33.033 › image upscayl:  vkQueueSubmit failed -4
0.18%
</details>
and then it spammed the terminal with the last error about ten thousand times
(up to %99.91)

**Comment by aaronliu0130** [comment] 2023-04-10 22:57
and every time was accompanied by a pop-up? vkQueueSubmit failed -4?

**Comment by Crilum** [comment] 2023-04-10 22:59
> and every time was accompanied by a pop-up? vkQueueSubmit failed -4?

Um.. Yes? The error was the one in my screenshot above.

It might be that it's generating an error pop-up every time it gives the `vkQueueSubmit failed -4`..

**Comment by aaronliu0130** [comment] 2023-04-10 23:02
Weird. The resetImagePaths function should've stopped the entire process instead of continuing.

**Comment by NayamAmarshe** [comment] 2023-04-11 01:32
Strange. Pressing OK should close it. I'll see if I can reproduce this.

**Comment by NayamAmarshe** [comment] 2023-04-29 17:13
Unfortunately, I'm unable to reproduce this error.

**Comment by Crilum** [comment] 2023-04-29 17:32
Weird. It still does it on my machine. When i tried it just now though, there were only about 6 pop-ups to close. This supports my earlier theory:
> It might be that it's generating an error pop-up every time it gives the vkQueueSubmit failed -4..

Just a thought, it might be reproducible only on some hardware.. My computer is about 10 years old (Intel 4th gen integrated graphics 😭😂), so it's not very.. AI suited, which is why I get the error, probably.

**Comment by NayamAmarshe** [comment] 2023-04-30 01:49
> Weird. It still does it on my machine. When i tried it just now though, there were only about 6 pop-ups to close. This supports my earlier theory:
> > It might be that it's generating an error pop-up every time it gives the vkQueueSubmit failed -4..
> 
> Just a thought, it might be reproducible only on some hardware.. My computer is about 10 years old (Intel 4th gen integrated graphics 😭😂), so it's not very.. AI suited, which is why I get the error, probably.

Ah makes sense. Unfortunately, I don't think there's any way around it. We're dealing with abstractions on top of other abstractions so granular control is pretty difficult 😅

Closing this issue as a can't fix for now😅

**Closed** 2023-04-30 01:49 UTC
Labels: bug, v2.5

**Comment by aaronliu0130** [comment] 2023-04-30 14:08
Could someone change the status of this issue in the project back to Can't Fix?

**Comment by oxou** [comment] 2023-05-23 07:26
Does this happen with every JPG or just a particular one? Perhaps send a JPG that's causing the issue (ZIP it first) and then I'll try to reproduce this.

**Comment by Crilum** [comment] 2023-05-23 14:24
> Does this happen with every JPG or just a particular one? Perhaps send a JPG that's causing the issue (ZIP it first) and then I'll try to reproduce this.

All photos I have tried have resulted in the error. (Multiple JPEGs, a couple PNGs...)

>It would also be beneficial if the original poster could provide information about their Operating System such as Distro, Kernel, Windowing System (X11, Wayland), etc..

Oh! Sure. I can't believe I didn't do that in my original post :joy: 
Debian 11 (Bullseye) with X11 and kernel version `5.10.0-23-amd64`

**Comment by oxou** [comment] 2023-05-24 08:54
@Crilum Can you run these commands on your system and send the `info.zip` afterwards?

```bash
cd ~
cat /proc/cpuinfo > 1.log
sudo lshw -C display > 2.log
sudo lsusb -v > 3.log
sudo lspci -vvv > 4.log
sudo dpkg --list | grep -iE "video|gpu" | awk -F ' ' '{print $2}' | grep -iv "^lib" > 5.log
zip -0 info.zip 1.log 2.log 3.log 4.log 5.log
```

Also what are your system specifications? Computer/Laptop model, etc.

It may be that you don't have appropriate video drivers installed or the GPU device does not support Vulkan.

**Comment by aaronliu0130** [comment] 2023-05-24 13:02
(Don’t worry, I can verify that these commands only produces your system configuration.)

**Comment by Crilum** [comment] 2023-05-25 06:35
> @Crilum Can you run these commands on your system and send the `info.zip` afterwards?
> 
> ```shell
> cd ~
> cat /proc/cpuinfo > 1.log
> sudo lshw -C display > 2.log
> sudo lsusb -v > 3.log
> sudo lspci -vvv > 4.log
> sudo dpkg --list | grep -iE "video|gpu" | awk -F ' ' '{print $2}' | grep -iv "^lib" > 5.log
> zip -0 info.zip 1.log 2.log 3.log 4.log 5.log
> ```
> 
> Also what are your system specifications? Computer/Laptop model, etc.
> 
> It may be that you don't have appropriate video drivers installed or the GPU device does not support Vulkan.

Here:

[info.zip](https://github.com/upscayl/upscayl/files/11561753/info.zip)

My GPUs (integrated and discrete) are so old.. They're definitely the problem :joy:

**Comment by aaronliu0130** [comment] 2023-05-31 20:06
[(There's an upadated guide on how to find GPU ID without commands.)](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id)
