### ISSUE TITLE
Error with "Batch Upscale" ignores the "Image Scale" setting.

### ISSUE THREAD

**Issue by plhappylemonpl** [upscayl/upscayl#607] opened 2023-12-23 22:34 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

There is an issue with the "Batch Upscale" mode that I'm already explaining. I have a picture in 1280x720, and I need to upscale it only twice (x2) to get 2560x1440. When I do a single photo, there's no problem; it scales it to 2560x1440. HOWEVER, when I want it to do everything (about 7500 photos), it ignores the x2 setting in the settings and scales them to x4, resulting in a resolution of 5120x2880.

### To Reproduce

1. Settings
2. IMAGE SCALE 
3. CHANGE 4x TO 2x
4. Back to Upscayl
5. Check Batch Upscayl
6. Sellect folder
7. etc / select model, output folder
8. start Upscayl
9. The pictures are not enlarged by a factor of x2 but by x4.

### Version (or commit hash)

2.9.5

### Select your Operating System

Windows

### OS Version

Windows 10 PRO FOR WORKSTATIONS 22H2 19045.3803

### GPU Name

RTX 4070

### Screenshots

https://www.youtube.com/watch?v=uJ7GvRykdaA

It was much quicker for me to record it than to take a thousand screenshots.

P.S. Even if I don't press stop, for example, I would wait until the end because I also did such a test; it's the same. I prefer to mark it just in case.

### Paste the logs

```sh
🎯 GET_MODELS_LIST:  
🧠 Recalling Output Folder:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]
🐞 BACKEND REPORTED:  📁 Updating Output Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  true
🐞 BACKEND REPORTED:  📐 Updating Compression:  NaN
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🔀 Setting model to ultramix_balanced
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting rememberOutputFolder from localStorage:  true
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatki
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatki
🖼 Selected Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatki
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatkiV2_upscayl
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatkiV2_upscayl
🗂 Setting Output Path:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatkiV2_upscayl
🧠 Remembering Output Folder:  C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatkiV2_upscayl
🔀 Model changed:  ultramix_balanced
🔀 Setting model to ultramix_balanced
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatki,-o,C:\Users\LemoN\Downloads\Zemsta Freddy'ego - odcinek 3 [HD]\klatkiV2_upscayl\upscayl_ultramix_balanced_x2,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,-g,0,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4070]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4070]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4070]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4070]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%
0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%
32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%
25,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  28,57%
28,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  32,14%
32,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  35,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  39,29%
39,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  42,86%
42,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  46,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  50,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  53,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  57,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  60,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  64,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  67,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  71,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  75,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  78,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  82,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  85,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  89,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  92,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  96,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  0,00%

🚧 FOLDER_UPSCAYL_PROGRESS:  3,57%
3,57%

🚧 FOLDER_UPSCAYL_PROGRESS:  7,14%
7,14%

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  Upscayl Successful

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  10,71%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  14,29%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  17,86%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  21,43%

🚧 FOLDER_UPSCAYL_PROGRESS:  25,00%
25,00%

🛑 Stopping Upscayl
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  true
🐞 BACKEND REPORTED:  🛑 Stopping Upscaling Process 13028
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Getting gpuId from localStorage:  0
⚙️ Getting rememberOutputFolder from localStorage:  true
```

**Comment by aaronliu0130** [comment] 2023-12-23 23:39
Duplicate of #574.
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-12-23 23:39 UTC
Labels: bug
