### ISSUE TITLE
Batch multi folder convert!!!

### ISSUE THREAD

**Issue by jamedom** [upscayl/upscayl#709] opened 2024-02-11 14:38 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

First I want to thank you for new release v2.9.9 and I'm very happy with it and also plz have a good luck with your long vacation 😅.  I hope when you return, It would be appreciated if you could or consider to add a new feature that allow to add multiple folder at once when converting. I know this feature have already been requested by other and I don't know if it's possible to do so but it would be great help if it can add in the next update. I wish it is possible😂 . Thank you very much.

**Comment by aaronliu0130** [comment] 2024-02-11 16:58
Duplicate of #402, but I've tried selecting multiple folders and it seems possible to select multiple folders through `properties: ["openDirectory", "multiSelections"],`... @NayamAmarshe thoughts?

**Comment by NayamAmarshe** [comment] 2024-02-12 02:17
> Duplicate of #402, but I've tried selecting multiple folders and it seems possible to select multiple folders through `properties: ["openDirectory", "multiSelections"],`... @NayamAmarshe thoughts?

After v3 then.

**Comment by NayamAmarshe** [comment] 2024-04-25 05:06
I'll be closing this in favor of #283

**Closed by NayamAmarshe** 2024-04-25 05:06 UTC
Labels: enhancement, help wanted
