### ISSUE TITLE
Downscaling?

### ISSUE THREAD

**Issue by Drael64** [upscayl/upscayl#1000] opened 2024-10-10 08:56 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

So, AI downscaling seems like it could be quite useful, if you can generate or render at higher than needed resolution, and the AI downscaler could preserve some of that detail. Obviously it would be most ideal if you could choose a precise parameter for how much to downscale. Most people use 1080P screens, so over a certain resolution without zooming you don't see it anyway. 

### Related Problem(s)

I'm not sure if there are open source AI downscaling algos. 

### Alternatives

Not really. Manually downscaling uses approximation, it doesn't know which details to preserve.

**Comment by aaronliu0130** [comment] 2024-11-01 14:11
Duplicate of #940
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-11-01 14:11 UTC
Labels: enhancement
