### ISSUE TITLE
commandline support 

### ISSUE THREAD

**Issue by byblo** [upscayl/upscayl#236] opened 2023-02-25 04:27 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Please add basic commandline support like the path to the filename or the folder to upscale.

For example:

 **c:\apps\Upscayl.exe -i d:\folders\pictures\image2.png**
 **c:\apps\Upscayl.exe -i d:\folders\pictures\*.png**

### Alternatives

none

**Comment by aaronliu0130** [comment] 2023-02-25 17:45
Duplicate of #10
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-03-04 01:53 UTC
Labels: enhancement
