### ISSUE TITLE
UPSCAYL BLOCKING AFTER UPSCAYLING 

### ISSUE THREAD

**Issue by Samedi4225** [upscayl/upscayl#389] opened 2023-07-07 14:40 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

</pre>
</details>

### Describe the Bug

After upscayling the image the result is fragmented blocks - it has been excellent up to the current update to 2.5.5 then it went odd

### To Reproduce

I am not sure 

### Version/Commit Hash

2.5.5

### OS Specifics

I am not sure 

### Expected Behavior

It should have upscayled the image 

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/138891337/72942741-454f-4bbc-93db-525b8b7ecbae)
 result after upscayl is 

![image](https://github.com/upscayl/upscayl/assets/138891337/c247da68-170c-47a7-a9d4-0ecbf9fc1799)

**Comment by NayamAmarshe** [comment] 2023-07-07 18:31
Please read the wiki

**Comment by aaronliu0130** [comment] 2023-07-07 18:41
Duplicate of #303 and the FAQ.

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
![and double ones are issued when you somehow manage to duplicate both](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-07-07 18:42 UTC
Labels: bug
