### ISSUE TITLE
Upscayl refuses to upscale images that have already been upscaled, even if they have been changed.

### ISSUE THREAD

**Issue by CheesecakeCG** [upscayl/upscayl#318] opened 2023-05-12 20:40 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Upscayl refuses to upscale images that have already been upscaled, even if they have overwritten with new images on disk since it only checks if the file already exists. See:
https://github.com/upscayl/upscayl/blob/a94fcf3a354b487755e0e337d2382cb97850899e/electron/index.ts#L507

### To Reproduce

1. Upscayl an image.
2. Edit the image.
3. Try to upscale again.
It just shows the old upscaled image again.

### Expected Behavior

Upscayl should check if the image has been modified, and upscale if it has.

### Version/Commit Hash

2.5.1

### OS Specifics

GTX 1660, Arch Linux

**Comment by aaronliu0130** [comment] 2023-05-12 21:18
Duplicate of #276.
> I have checked that this issue isn't addressed in any other issue or pull request.
---
Your title and description is way clearer though.

**Closed by aaronliu0130** 2023-05-12 21:18 UTC
Labels: bug

**Comment by NayamAmarshe** [comment] 2023-05-12 22:03
> Upscayl should check if the image has been modified, and upscale if it has.

That's not possible. There's no way to predict the checksum.

I can add an overwrite option though

**Comment by CheesecakeCG** [comment] 2023-05-12 22:21
It could just used the modified date of file. It could also cache the checksums of the source images and compare them with the current version.

**Comment by NayamAmarshe** [comment] 2023-05-12 22:53
> It could just used the modified date of file. It could also cache the checksums of the source images and compare them with the current version.

I suppose checking the date could work, thanks for the idea but I think adding an option for overwriting would be a bit better since upscaling the same image twice won't really give any different results.
