### ISSUE TITLE
Batch processing on Windows ignores the methods and file types

### ISSUE THREAD

**Issue by daath** [upscayl/upscayl#239] opened 2023-03-08 01:51 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

I just found Upscayl, and it is awesome for single images. However, I tried to batch process a folder with PNG images and selected "General Photo (Ultramix Balanced)", selected "Advanced Options" then "JPG" - all files were converted, BUT with "General Photo (Real-ESRGAN)" and all files were saved as PNG. I tried a few times, because I thought I'd done something wrong, but it always does it this way.

### To Reproduce

Open Upscayl. Select "Batch Upscale".
Pick a folder with PNG-images. 
Select "General Photo (Ultramix Balanced)".
Select "Advanced Options" - make sure "JPG" is selected.
Click "Upscayl".

### Expected Behavior

All images should be converted using the algorithm and filetype chosen.

### Version/Commit Hash

2.0.1

### OS Specifics

Windows 11

**Comment by aaronliu0130** [comment] 2023-03-08 11:54
Duplicate of #174
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by NayamAmarshe** [comment] 2023-03-08 12:49
> Même problème, je l'ai signalé, mais mon post a été supprimé...

Nous sommes conscients du problème mais malheureusement, le binaire Real-ESRGAN n'est pas sans erreur. En tant que tel, nous ne pouvons rien y faire pour le moment.

We are aware of the issue but unfortunately, the Real-ESRGAN binary is kinda buggy. As such, we can do nothing about it for now :(

**Closed by NayamAmarshe** 2023-03-08 12:49 UTC
Labels: bug

**Comment by SpiralBrad** [comment] 2023-03-12 04:09
> We are aware of the issue but unfortunately, the Real-ESRGAN binary is kinda buggy. As such, we can do nothing about it for now :(

"Nothing" is a bit much.  You can disable or change these non-working options when you know the user has selected a combination where they won't work as expected.

**Comment by NayamAmarshe** [comment] 2023-03-12 09:44
> > We are aware of the issue but unfortunately, the Real-ESRGAN binary is kinda buggy. As such, we can do nothing about it for now :(
> 
> Saying you can do "nothing" is a bit too far; you can disable or change these non-working options when you know the user has selected a combination where they won't work as expected.

https://github.com/upscayl/upscayl/issues/174#issuecomment-1372642540

**Comment by SpiralBrad** [comment] 2023-03-12 16:28
> [#174 (comment)](https://github.com/upscayl/upscayl/issues/174#issuecomment-1372642540)

2 months ago, not in a released build.  But that's a step in the right direction, at least.
