### ISSUE TITLE
Error processing (scaling and converting) the image

### ISSUE THREAD

**Issue by Access-Denied-20** [upscayl/upscayl#477] opened 2023-09-16 17:04 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"C:\\Users\\Xiao\\Pictures\\00006-4269215103.png","extension":"png"}
🖼 Setting image path:  C:\Users\Xiao\Pictures\00006-4269215103.png
🗂 Setting output path:  C:\Users\Xiao\Pictures
🖼 imagePath:  C:\Users\Xiao\Pictures\00006-4269215103.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\Xiao\Pictures\00006-4269215103.png,-o,C:\Users\Xiao\Pictures\00006-4269215103_upscayl_4x_ultramix_balanced.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultramix_balanced,,,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: C:\Users\Xiao\Pictures\00006-4269215103_upscayl_4x_ultramix_balanced.png
🔄 Resetting image paths
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
```

### Describe the Bug

Unable to process any image files, error message appears: Error processing (scaling and converting) the image. please repott this error on Upscayl GitHub lssues page.

### To Reproduce

1. Install Upscayl
2. Open the program, select the picture, and click "UPSCAYL"
3. The error appears immediately

### Version/Commit Hash

2.8.1

### OS Specifics

NVIDIA GeForce GTX 1060 (Laptop), Windows 10 22H2

### Expected Behavior

The image should be processed successfully. I used it successfully in version 2.7.5. But now it can’t be used even if I reinstall version 2.7.5

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/50802292/1db84002-afb4-485d-b837-06656fe506fc)

**Comment by aaronliu0130** [comment] 2023-09-16 17:28
Duplicate of #463
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-09-16 17:29 UTC
Labels: bug
