### ISSUE TITLE
Can we use Python to implement it with code?

### ISSUE THREAD

**Issue by jememouse** [upscayl/upscayl#254] opened 2023-03-25 03:51 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Can we use Python to implement it with code?
I want to use Python to call the functions of this library and process images.

### Description

I want to use Python to call the functions of this library and process images.

### Alternatives

None.

**Comment by aaronliu0130** [comment] 2023-03-25 17:33
Duplicate of #10 . We use REAL-ERSGAN for the actual upscaling functionality.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by coolst3r** [comment] 2023-04-07 00:06
> ### Checklist
> 
>     * [x]  I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> 
>     * [x]  I have checked that this issue isn't addressed in any other issue or pull request.
> 
> 
> ### Related Problem(s)
> 
> Can we use Python to implement it with code? I want to use Python to call the functions of this library and process images.
> ### Description
> 
> I want to use Python to call the functions of this library and process images.
> ### Alternatives
> 
> None.

lazy dev

**Comment by NayamAmarshe** [comment] 2023-04-07 00:13
You can use Python code from the Real-ESRGAN repository.

**Comment by aaronliu0130** [comment] 2023-04-07 14:07
> lazy dev

wdym lazy? python is still nice even though kotlin and c++ are nicer

**Closed by aaronliu0130** 2023-04-07 14:07 UTC
Labels: enhancement
