### ISSUE TITLE
Scaling and Converting causes Out of memory error

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#447] opened 2023-09-03 06:14 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>

[Upscaly Log.txt](https://github.com/upscayl/upscayl/files/12518109/Upscaly.Log.txt)

</pre></details>

### Describe the Bug

Program upscale process is stuck at 99.48% you stop just click stop to finish the process.  The image has completed upscaling but the program is just stuck have to manually stop it to complete the process.  This is for a single image I have not tested with batch process it would not surprise me if there is the same problem for batch processing.  

### To Reproduce

Just upscale any image right at the time it should complete it gets stuck 

### Version/Commit Hash

2.7.5

### OS Specifics

Windows 10

### Expected Behavior

Program should get to 100% upscale process and totally finish 

### Screenshots

![Upscle Not Finishing](https://github.com/upscayl/upscayl/assets/38142712/ba37f1d5-1852-44ca-80e3-8230f50e792f)

**Comment by aaronliu0130** [comment] 2023-09-03 17:18
Could you send the logs? The instructions are detailed [here](https://github.com/upscayl/upscayl/wiki/Guide#logs).

**Comment by stevehorwitz** [comment] 2023-09-04 23:14
I have the same problem, but it stops at 90.55%. The file is *not* written when I click on "Stop".  Despite the UI stopping at 90.55%, the log file indicates that upscaling has completed,

[upscayl.log](https://github.com/upscayl/upscayl/files/12517094/upscayl.log)

Attached is the log file. Unfortunately, the file that is being upscaled is 64Mb, and cannot be uploaded.

I am using an NVidia GeForce RTX 2040 GPU that has 11 GB memory. I am using Windows 10. My machine has 64GB of memory.

I am guessing that the source of the problem can be seen at the end of the log file:

           Getting rememberOutputFolder from localStorage false

I didn't change the output directory accepting the default directory which is where the image is. But, the same problem occurs even when I change the output directory.

**Comment by aaronliu0130** [comment] 2023-09-05 01:11
Thanks for the logs and info! Relevant parts:
```sh
🚧 UPSCAYL_PROGRESS:  90.55%

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Getting gpuId from localStorage NVidia GeForce RTX 2040
⚙️ Getting rememberOutputFolder from localStorage false
🛑 Stopping Upscayl
🔄 Resetting image paths
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🛑 Stopping Upscaling Process 86112
```
I suspect it's with the conversion step. We'll investigate this.

**Comment by DJboutit** [comment] 2023-09-05 02:25
Updated my logs

**Comment by NayamAmarshe** [comment] 2023-09-05 05:52
It seems scaling and conversion causes the memory to run out, especially in batch upscale.

I'll try to find a fix for this issue.

**Comment by aaronliu0130** [comment] 2023-09-05 13:03
@DJboutit I still don’t see your logs

**Comment by NayamAmarshe** [comment] 2023-09-05 18:04
We'll be switching from JIMP to Sharp. It should fix memory issues.

https://github.com/jimp-dev/jimp/issues/153

**Comment by NayamAmarshe** [comment] 2023-09-05 18:08
Duplicate of #439

Closing this.

**Closed by NayamAmarshe** 2023-09-05 18:08 UTC
Labels: bug
