### ISSUE TITLE
No difference in clarity of image after upscaling

### ISSUE THREAD

**Issue by TechPro424** [upscayl/upscayl#640] opened 2024-01-11 13:04 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

I'm trying to make an image clearer using Upscayl (as shown in the https://upscayl.org/ demo)
However. there is no increase in clarity of the image even when tried using multiple models (even the preview after completion shows no difference)
It's a .jpg image

I have only an integerated GPU so that's the only one that can be used, hence I have not set GPU ID

### To Reproduce

Take a .jpg image, try upscayling it using real ersgan, fast real ersgan or ultrasharp model (I normally use the 3rd one and it works)
No difference in clarity in the new image

### Version (or commit hash)

2.9.5

### Select your Operating System

Windows

### OS Version

Windows 11

### GPU Name

Intel(R) UHD Graphics 730

### Expected Behavior

There should have been a significant increase in clarity of image

### Screenshots

Can't post screenshots as the photo is that of a friend, I don't want to post it online

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔀 Model changed:  RealESRGAN_General_x4_v3
🔀 Setting model to RealESRGAN_General_x4_v3
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to RealESRGAN_General_x4_v3
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🐞 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\TechPro424\Downloads\GP2.jpg
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\TechPro424\Downloads\GP2.jpg
🖼 Selected Image Path:  C:\Users\TechPro424\Downloads\GP2.jpg
📁 Selected Image Directory:  C:\Users\TechPro424\Downloads
🖼 imagePath:  C:\Users\TechPro424\Downloads\GP2.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  true
🐞 BACKEND REPORTED:  🖼️ Updating No Image Processing:  false
🐞 BACKEND REPORTED:  📐 Updating Compression:  0
🐞 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"png","inputDir":"C:\\Users\\TechPro424\\Downloads","outputDir":"C:\\Users\\TechPro424\\Downloads","fullfileName":"GP2.jpg","fileName":"GP2","initialScale":"4","desiredScale":"4","outFile":"C:\\Users\\TechPro424\\Downloads\\GP2_upscayl_4x_ultrasharp.png","compression":0}
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\TechPro424\Downloads\GP2.jpg,-o,C:\Users\TechPro424\Downloads\GP2_upscayl_4x_ultrasharp.png,-s,4,-m,C:\Users\TechPro424\scoop\apps\upscayl\current\resources\models,-n,ultrasharp,,,-f,png
🐞 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Users\\TechPro424\\scoop\\apps\\upscayl\\current\\resources\\bin\\upscayl-bin","args":["C:\\Users\\TechPro424\\scoop\\apps\\upscayl\\current\\resources\\bin\\upscayl-bin","-i","C:\\Users\\TechPro424\\Downloads\\GP2.jpg","-o","C:\\Users\\TechPro424\\Downloads\\GP2_upscayl_4x_ultrasharp.png","-s","4","-m","C:\\Users\\TechPro424\\scoop\\apps\\upscayl\\current\\resources\\models","-n","ultrasharp","","","-f","png"]}
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🐞 BACKEND REPORTED:  image upscayl:  [0 Intel(R) UHD Graphics 730]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics 730]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics 730]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics 730]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Intel(R) UHD Graphics 730]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics 730]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics 730]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics 730]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  2.08%

🚧 UPSCAYL_PROGRESS:  2.08%

🐞 BACKEND REPORTED:  image upscayl:  4.17%

🚧 UPSCAYL_PROGRESS:  4.17%

🐞 BACKEND REPORTED:  image upscayl:  6.25%

🚧 UPSCAYL_PROGRESS:  6.25%

🐞 BACKEND REPORTED:  image upscayl:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🐞 BACKEND REPORTED:  image upscayl:  10.42%

🚧 UPSCAYL_PROGRESS:  10.42%

🐞 BACKEND REPORTED:  image upscayl:  12.50%

🚧 UPSCAYL_PROGRESS:  12.50%

🐞 BACKEND REPORTED:  image upscayl:  14.58%

🚧 UPSCAYL_PROGRESS:  14.58%

🐞 BACKEND REPORTED:  image upscayl:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🐞 BACKEND REPORTED:  image upscayl:  18.75%

🚧 UPSCAYL_PROGRESS:  18.75%

🐞 BACKEND REPORTED:  image upscayl:  20.83%

🚧 UPSCAYL_PROGRESS:  20.83%

🐞 BACKEND REPORTED:  image upscayl:  22.92%

🚧 UPSCAYL_PROGRESS:  22.92%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  27.08%

🚧 UPSCAYL_PROGRESS:  27.08%

🐞 BACKEND REPORTED:  image upscayl:  29.17%

🚧 UPSCAYL_PROGRESS:  29.17%

🐞 BACKEND REPORTED:  image upscayl:  31.25%

🚧 UPSCAYL_PROGRESS:  31.25%

🐞 BACKEND REPORTED:  image upscayl:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🐞 BACKEND REPORTED:  image upscayl:  35.42%

🚧 UPSCAYL_PROGRESS:  35.42%

🐞 BACKEND REPORTED:  image upscayl:  37.50%

🚧 UPSCAYL_PROGRESS:  37.50%

🐞 BACKEND REPORTED:  image upscayl:  39.58%

🚧 UPSCAYL_PROGRESS:  39.58%

🐞 BACKEND REPORTED:  image upscayl:  41.67%

🚧 UPSCAYL_PROGRESS:  41.67%

🐞 BACKEND REPORTED:  image upscayl:  43.75%

🚧 UPSCAYL_PROGRESS:  43.75%

🐞 BACKEND REPORTED:  image upscayl:  45.83%

🚧 UPSCAYL_PROGRESS:  45.83%

🐞 BACKEND REPORTED:  image upscayl:  47.92%

🚧 UPSCAYL_PROGRESS:  47.92%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  52.08%

🚧 UPSCAYL_PROGRESS:  52.08%

🐞 BACKEND REPORTED:  image upscayl:  54.17%

🚧 UPSCAYL_PROGRESS:  54.17%

🐞 BACKEND REPORTED:  image upscayl:  56.25%

🚧 UPSCAYL_PROGRESS:  56.25%

🐞 BACKEND REPORTED:  image upscayl:  58.33%

🚧 UPSCAYL_PROGRESS:  58.33%

🐞 BACKEND REPORTED:  image upscayl:  60.42%

🚧 UPSCAYL_PROGRESS:  60.42%

🐞 BACKEND REPORTED:  image upscayl:  62.50%

🚧 UPSCAYL_PROGRESS:  62.50%

🐞 BACKEND REPORTED:  image upscayl:  64.58%

🚧 UPSCAYL_PROGRESS:  64.58%

🐞 BACKEND REPORTED:  image upscayl:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🐞 BACKEND REPORTED:  image upscayl:  68.75%

🚧 UPSCAYL_PROGRESS:  68.75%

🐞 BACKEND REPORTED:  image upscayl:  70.83%

🚧 UPSCAYL_PROGRESS:  70.83%

🐞 BACKEND REPORTED:  image upscayl:  72.92%

🚧 UPSCAYL_PROGRESS:  72.92%

🐞 BACKEND REPORTED:  image upscayl:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🐞 BACKEND REPORTED:  image upscayl:  77.08%

🚧 UPSCAYL_PROGRESS:  77.08%

🐞 BACKEND REPORTED:  image upscayl:  79.17%

🚧 UPSCAYL_PROGRESS:  79.17%

🐞 BACKEND REPORTED:  image upscayl:  81.25%

🚧 UPSCAYL_PROGRESS:  81.25%

🐞 BACKEND REPORTED:  image upscayl:  83.33%

🚧 UPSCAYL_PROGRESS:  83.33%

🐞 BACKEND REPORTED:  image upscayl:  85.42%

🚧 UPSCAYL_PROGRESS:  85.42%

🐞 BACKEND REPORTED:  image upscayl:  87.50%

🚧 UPSCAYL_PROGRESS:  87.50%

🐞 BACKEND REPORTED:  image upscayl:  89.58%

🚧 UPSCAYL_PROGRESS:  89.58%

🐞 BACKEND REPORTED:  image upscayl:  91.67%

🚧 UPSCAYL_PROGRESS:  91.67%

🐞 BACKEND REPORTED:  image upscayl:  93.75%

🚧 UPSCAYL_PROGRESS:  93.75%

🐞 BACKEND REPORTED:  image upscayl:  95.83%

🚧 UPSCAYL_PROGRESS:  95.83%

🐞 BACKEND REPORTED:  image upscayl:  97.92%

🚧 UPSCAYL_PROGRESS:  97.92%

🐞 BACKEND REPORTED:  image upscayl:  Upscayl Successful

🚧 UPSCAYL_PROGRESS:  Upscayl Successful

🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  Skipping png compression for 4x scale
upscaledImagePath:  C:\Users\TechPro424\Downloads\GP2_upscayl_4x_ultrasharp.png
💯 UPSCAYL_DONE:  C:\Users\TechPro424\Downloads\GP2_upscayl_4x_ultrasharp.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment] 2024-01-11 15:56
> **To Reproduce**
Take a .jpg image, try upscayling it using real ersgan, fast real ersgan or ultrasharp model (I normally use the 3rd one and it works)
No difference in clarity in the new image

This issue is not reproducible. It's most likely your iGPU. Upscayl does not support (officially) integrated GPUs.

**Comment by TechPro424** [comment] 2024-01-11 17:38
It did work for me with other images, maybe I should convert the file format?

**Comment by aaronliu0130** [comment] 2024-01-12 12:51
Give us a different photo that isn’t of your friend.

**Comment by TechPro424** [comment] 2024-01-12 14:26
downloaded from the internet
![test](https://github.com/upscayl/upscayl/assets/86620085/de6c3316-bd22-46b3-9cc9-472a0db5caac)

No change when using ultrasharp model

**Comment by aaronliu0130** [comment] 2024-01-12 16:20
Please send the before and after. As long as the resolution increased and it wasn’t pixelated, it worked.

**Comment by NayamAmarshe** [comment] 2024-01-12 16:27
> downloaded from the internet
> 
> ![test](https://github.com/upscayl/upscayl/assets/86620085/de6c3316-bd22-46b3-9cc9-472a0db5caac)
> 
> 
> 
> No change in clarity when using ultrasharp model
> 
> 

We can't really guarantee every upscale to meet expectations because models work differently for each image. If other images are working fine, then this is too. This is not a bug and the model is working as it should be. Results always depend on the type of image used.

I'm closing this issue because it's not really a bug but more of a stylistic disagreement.

**Closed by NayamAmarshe** 2024-01-12 16:27 UTC
Labels: bug
