### ISSUE TITLE
"ENCODING ERROR =>" on Windows 10, for overly long file names ?

### ISSUE THREAD

**Issue by Ysengwen** [upscayl/upscayl#146] opened 2022-11-29 19:19 UTC
The same images cause an encoding error around 75% progress, but are upscaled fine if I create a renamed version with a shorter file name.

Win 10 PC.

**Comment by NayamAmarshe** [comment] 2022-11-29 21:44
Duplicate of #
https://github.com/upscayl/upscayl/issues/132

**Closed** 2022-11-30 15:47 UTC
