### ISSUE TITLE
The photo after processing is displayed incorrectly

### ISSUE THREAD

**Issue by Agniya551** [upscayl/upscayl#309] opened 2023-05-10 12:21 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

The photo after processing is displayed incorrectly

### To Reproduce

The photo after processing is displayed incorrectly

### Expected Behavior

The photo after processing is displayed incorrectly

### Version/Commit Hash

2.5.1

### OS Specifics

Lenovo IdeaPad 3 15ITL6 / Windows 11 Pro

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/84963460/62e0bbb5-c4e8-4db9-84a7-bdbdb6d047ef)

![kandinsky-download-1683705889694_upscayl_3x_realesrgan-x4plus jpg](https://github.com/upscayl/upscayl/assets/84963460/3f70eb24-4e48-4184-afa7-ee5c5de4389a)

**Comment by NayamAmarshe** [comment] 2023-05-10 13:38
Please search for pre-existing issues before creating new ones.

Duplicate of #303

**Closed by NayamAmarshe** 2023-05-10 13:38 UTC
Labels: bug
