### ISSUE TITLE
Request: CLI interface to pass in parms so upscayl can be called from scripts.

### ISSUE THREAD

**Issue by famewolf** [upscayl/upscayl#262] opened 2023-04-02 15:45 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Inability to upscale video.

### Description

I'd like to use a bash shell script which would call ffmpeg to deconstruct a video into it's frames then call upscayl to perform the upscale and then finally use a ffmpeg command to rebuild the video from the upscayled frames.    This would simply  be passing in the name of file/folder, engine to use etc and then let it perform the procedure as normal in the gui as long as a return code is returned upon completion to indicate success or failure.

### Alternatives

Current alternative is manually extracting the frames for a video which requires large amount of storage.  a script could extract a set amount of frames from a video, upscale them and then delete the original frames requiring minimal storage as it loops through.

**Comment by aaronliu0130** [comment] 2023-04-03 10:52
Duplicate of #10
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-04-04 07:26 UTC
Labels: enhancement

**Comment by infinity0** [comment] 2024-03-02 15:30
Upscayl in fact does have an internal CLI, which you can see, together with its CLI args, in the stdout logs it outputs when processing an image. On GNU/Linux this is located at `/opt/Upscayl/resources/bin/upscayl-bin`. It even takes `--help` so you can see what all the options are.

**Comment by imshvc** [comment] 2024-12-05 00:17
Save this as **C:\\Windows\\System32\\upscayl.bat**

```bat
@echo off
setlocal
set "EXE_PATH=C:\Program Files\Upscayl\resources\bin\upscayl-bin.exe"

rem Check if Upscayl is installed at the default directory.
if not exist "%EXE_PATH%" (
    echo Upscayl is not installed.
    echo Get it here: https://github.com/upscayl/upscayl/releases
    endlocal
    exit /B 1
)

rem Call the executable with any provided arguments.
"%EXE_PATH%" %*

endlocal

exit /B %ERRORLEVEL%
```

Terminal:

```
C:\>upscayl
Usage: upscayl-bin -i infile -o outfile [options]...

  -h                   show this help
  -i input-path        input image path (jpg/png/webp) or directory
  -o output-path       output image path (jpg/png/webp) or directory
  -z model-scale       scale according to the model (can be 2, 3, 4. default=4)
  -s output-scale      custom output scale (can be 2, 3, 4. default=4)
  -r resize            resize output to dimension (default=WxH:default), use '-r help' for more details
  -w width             resize output to a width (default=W:default), use '-r help' for more details
  -c compress          compression of the output image, default 0 and varies to 100
  -t tile-size         tile size (>=32/0=auto, default=0) can be 0,0,0 for multi-gpu
  -m model-path        folder path to the pre-trained models. default=models
  -n model-name        model name (default=realesrgan-x4plus, can be realesr-animevideov3 | realesrgan-x4plus-anime | realesrnet-x4plus or any other model)
  -g gpu-id            gpu device to use (default=auto) can be 0,1,2 for multi-gpu
  -j load:proc:save    thread count for load/proc/save (default=1:2:2) can be 1:2,2,2:2 for multi-gpu
  -x                   enable tta mode
  -f format            output image format (jpg/png/webp, default=ext/png)
  -v                   verbose output
```

**Comment by aaronliu0130** [comment] 2024-12-27 16:26
The CLI has its own repository at https://github.com/upscayl/upscayl-ncnn.

**Comment by yashschandra** [comment] 2025-04-08 01:10
I had similar (and some more) use cases so I created one myself https://github.com/yashschandra/upscayl-cli
