### ISSUE TITLE
Crash on Wayland / GBM backend

### ISSUE THREAD

**Issue by savchenko** [upscayl/upscayl#964] opened 2024-09-07 02:22 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Upscayl GPU process crashes when ozone platform is set to Wayland.

`UPSCAYL_GPU_ID` referenced in https://github.com/upscayl/upscayl/issues/913#issuecomment-2227357322 has no effect.

### To Reproduce

1. Install proprietary NVidia drivers
2. Launch KDE/Plasma Wayland session
3. `./upscayl-2.11.5-linux.AppImage --ozone-platform=wayland`
4. Observe the crash.

### Upscayl Version (or commit hash)

2.11.5

### Platform

Linux
Single GPU

### OS Version

Debian 12

### GPU Name

RTX 4070 Ti

### Expected Behavior

GUI launches.

### Screenshots

N/A

### Logs

```sh
📂 DIRNAME /tmp/.mount_upscayND80VD/resources/app.asar/export/electron
Checking for update
11:49:16.215 › 🚀 UPSCAYL EXEC PATH:  /tmp/.mount_upscayND80VD/resources/bin/upscayl-bin
11:49:16.217 › 🚀 MODELS PATH:  /tmp/.mount_upscayND80VD/resources/models
Generated new staging user ID: 475cebe2-fadd-55c0-b4ae-c684b356b577
[211724:0907/114916.486105:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211724:0907/114916.486191:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[211724:0907/114916.486337:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211724:0907/114916.486402:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[211724:0907/114916.486435:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[211724:0907/114916.486472:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[211724:0907/114916.486525:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[211686:0907/114916.495901:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
[211761:0907/114916.645221:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211761:0907/114916.645280:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[211761:0907/114916.645358:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211761:0907/114916.645388:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[211761:0907/114916.645413:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[211761:0907/114916.645443:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[211761:0907/114916.645499:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[211686:0907/114916.656135:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
[211777:0907/114916.798012:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211777:0907/114916.798081:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[211777:0907/114916.798149:ERROR:gbm_wrapper.cc(253)] Failed to export buffer to dma_buf: No such file or directory (2)
[211777:0907/114916.798183:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[211777:0907/114916.798207:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[211777:0907/114916.798233:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[211777:0907/114916.798277:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[211686:0907/114916.804435:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
11:49:17.037 › ⚙ Setting saveImageAs to png
11:49:17.038 › 🔀 Setting model to realesrgan-x4plus
11:49:17.038 › ⚙ Setting gpuId to empty string
11:49:17.038 › 🔀 Setting model to null
11:49:17.041 › 🔀 Setting model to realesrgan-x4plus
Update for version 2.11.5 is not available (latest version: 2.11.5, downgrade is disallowed).
```

**Comment by aaronliu0130** [comment] 2024-09-07 18:22
Duplicate of #591.

**Closed by aaronliu0130** 2024-09-07 18:22 UTC
Labels: bug, vulkan
