### ISSUE TITLE
Most Process Images Have a Section Of Blurry Foggy Pixels 

### ISSUE THREAD

**Issue by DJboutit** [upscayl/upscayl#104] opened 2022-10-03 05:42 UTC
Most processed Images have section of blurry foggy pixels this needs to be fixed

Examples 

Vanessa Hudgens in skirt https://i.ibb.co/s3c9Y8F/001-13-upscayl-4x-realesrgan-x4plus.jpg

Alexis Ren https://i.ibb.co/wL6RGQF/MED32-EP-o-upscayl-4x-realesrgan-x4plus.jpg

Tela Piece Of Mind album cover https://i.ibb.co/XVnKRjY/Tela-POM.jpg

**Comment by NayamAmarshe** [comment] 2022-10-03 06:18
Duplicate of #92 

I explained why I can't fix this, this is how the algorithm works. You can create an issue on Real-ESRGAN's repository, although I doubt it's maintained as much anymore.

**Closed by NayamAmarshe** 2022-10-03 06:18 UTC
