### ISSUE TITLE
Upscayl stuck on 'Hold on...', Stops working after first time

### ISSUE THREAD

**Issue by Redo11** [upscayl/upscayl#80] opened 2022-09-20 16:20 UTC
Doing the Upscayl magic...

It's just stuck like that. It worked once, somehow, but it broke again.

**Comment by NayamAmarshe** [comment] 2022-09-20 17:34
Yeah for some people it's broken for no reason. I think it's got something to do with AppImage configuration or something, I'm unable to reproduce this issue.

**Comment by 19s-fautley-k** [comment] 2022-09-20 20:16
Able to reproduce on Flatpak and AppImage. Worked once on AppImage but now won't work on either.

**Comment by 19s-fautley-k** [comment] 2022-09-20 20:20
I am on Ubuntu 22.04, Cinnamon desktop, with a GTX 1060, an image that worked previously does not

**Comment by NayamAmarshe** [comment] 2022-09-21 14:58
Yeah something's wrong with the way AppImages are working. I'll publish a deb file if possible.

**Comment by 19s-fautley-k** [comment] 2022-09-22 10:58
> Yeah something's wrong with the way AppImages are working. I'll publish a deb file if possible.

Is the flatpak an appimage then?

**Comment by 19s-fautley-k** [comment] 2022-09-22 11:03
Also, might be useful to change the title

**Comment by Redo11** [comment] 2022-09-22 18:28
it is appimage

**Comment by Redo11** [comment] 2022-09-22 18:29
And it didn't work the first time, it worked one time

**Comment by NayamAmarshe** [comment] 2022-09-22 18:30
> And it didn't work the first time, it worked one time

Are you keeping the AppImage in your home directory? Can you try launching the AppImage from another folder?

**Comment by winsomehax** [comment] 2022-09-22 18:38
> > And it didn't work the first time, it worked one time
> 
> Are you keeping the AppImage in your home directory? Can you try launching the AppImage from another folder?

Can [this issue](https://github.com/upscayl/upscayl/issues/53) be renamed... there's a fair amount of info in it. The later posts are my findings with regard to the issue. It sounds very similar and there's workaround if it is the same thing. I'll keep digging myself but if anyone has any info/investigation to add themselves it would be very handy.

**Comment by NayamAmarshe** [comment] 2022-09-26 08:20
@Redo11 @19s-fautley-k

Could you guys please test this build: https://link.storjshare.io/jw34l25j4e27dpthmpi5tpy426kq/drive%2FUpscayl-1.5.5.AppImage

**Comment by 19s-fautley-k** [comment] 2022-09-26 10:59
I'll try it when I get home

________________________________
Disclaimer

The information in this message should be regarded as confidential and is intended for the addressee only unless explicitly stated. If you have received this message in error it must be deleted and the sender notified. The views expressed in this message are personal and not necessarily those of the Danes Educational Trust unless explicitly stated. Please be aware that emails sent to or received from the Danes Educational Trust may be intercepted and read by the IT support team. Interception will only occur to ensure compliance with school policies or procedures or regulatory obligations, to prevent or deter crime, or for the purposes of essential maintenance of the email system.

________________________________
Disclaimer

The information in this message should be regarded as confidential and is intended for the addressee only unless explicitly stated. If you have received this message in error it must be deleted and the sender notified. The views expressed in this message are personal and not necessarily those of St. Clement Danes School unless explicitly stated. Please be aware that emails sent to or received from St. Clement Danes School may be intercepted and read by the School’s IT support team. Interception will only occur to ensure compliance with school policies or procedures or regulatory obligations, to prevent or deter crime, or for the purposes of essential maintenance of the email system.

**Comment by 19s-fautley-k** [comment] 2022-09-26 13:54
I'll try it when I get home.
(resent so I'm not doxxed)

**Comment by NayamAmarshe** [comment] 2022-09-30 17:30
Fixed in: https://github.com/upscayl/upscayl/releases/tag/v1.5.5

**Closed as completed** 2022-09-30 17:30 UTC
Labels: bug, HIGH PRIORITY

**Comment by cristianleo83** [comment] 2022-09-30 22:34
with the update it keeps telling me decoding error, does anyone else get it?

**Comment by NayamAmarshe** [comment] 2022-10-01 00:34
> with the update it keeps telling me decoding error, does anyone else get it?

https://github.com/upscayl/upscayl/issues/53#issuecomment-1257203553
