### ISSUE TITLE
Really long HTML update message on Windows

### ISSUE THREAD

**Issue by thunder-red-star** [upscayl/upscayl#310] opened 2023-05-11 03:12 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [x] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Very long `<a>` tag, which isn't rendered and instead shows up as raw, in the update popup after opening Upscayl v2.0.1 on Windows.
<details>
<summary>Logs</summary>
<pre>

N/A (I updated before having the idea to post this issue)
</pre>
</details>

### To Reproduce

1. Open Upscayl 2.0 on Windows
2. Watch as two popups appear prompting you to update, but the popups are not formatted properly

### Expected Behavior

An update popup that isn't 400 meters tall

### Version/Commit Hash

332f9f91bb663fba3e11c5c060d45c46bb0547ef (v2.0.1)

### OS Specifics

RTX 2060, Windows 11 Home 22H2

### Screenshots

![image](https://github.com/upscayl/upscayl/assets/67127399/fbab0251-0e06-4c78-aab5-6098a4a59b0b)

**Comment by aaronliu0130** [comment] 2023-05-11 11:38
Duplicate of #175.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-05-11 11:38 UTC
Labels: bug

**Comment by NayamAmarshe** [comment] 2023-05-11 11:41
I'll disable the release notes on windows.

**Comment by thunder-red-star** [comment] 2023-05-11 12:58
Sorry, I didn't look too far back thought this was a recent issue :P
