### ISSUE TITLE
Save Image As does not work for Batch Upscales

### ISSUE THREAD

**Issue by derickso** [upscayl/upscayl#230] opened 2023-02-16 12:21 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Selecting JPG in Save As option when using Batch Upscale saves it as .png

### To Reproduce

- Set Batch Upscale
- Choose folder
- Save As: PNG
- Run Upscayl

Output images are saved as .png

### Expected Behavior

Output images are saved as extension chosen

### Version/Commit Hash

2.0.1

### OS Specifics

GeForce 3090, Windows 11

**Comment by aaronliu0130** [comment] 2023-02-16 20:31
Duplicate of #174.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-02-16 23:27 UTC
Labels: bug
