### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by DaimuX** [upscayl/upscayl#670] opened 2024-01-25 14:38 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I want to translate it into another language, but the language file is pak. How can I translate it into the local language？thx

**Comment by aaronliu0130** [comment] 2024-01-25 16:25
Duplicate of #91

**Closed by aaronliu0130** 2024-01-25 16:25 UTC
Labels: enhancement
