### ISSUE TITLE
Need More Details In Batch Upscale

### ISSUE THREAD

**Issue by chauhanvats3** [upscayl/upscayl#331] opened 2023-05-21 08:29 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

I would also like to see the progress of the whole batch upscale operation instead of each file's progress only.
Also, in batch operation, if we could show the file name of file currently being processed, that'd be great.

### Alternatives

Although it's working awesome as it is right now, adding these will improve User Experience.

**Comment by aaronliu0130** [comment] 2023-05-21 13:39
Possible duplicate of #130

**Comment by NayamAmarshe** [comment] 2023-05-21 15:32
Not possible. We don't get enough data from the backend for this to happen. You can always check the logs though.

The issue is with parallel processing. We can't predict completion time. We can't show percentage as they run parallelly. There's not much to calculate and show on the frontend.

**Comment by aaronliu0130** [comment] 2023-05-21 17:16
Maybe we could count the number of times the percentage jumps back down?

**Comment by NayamAmarshe** [comment] 2023-05-21 17:34
> Maybe we could count the number of times the percentage jumps back down?

That's not possible, that was also my first thought. Sometimes the percentages don't start from 0 for some photos .

**Closed** 2023-05-23 13:28 UTC
Labels: enhancement
