### ISSUE TITLE
Support for Google Colab 

### ISSUE THREAD

**Issue by Vampire-Chan** [upscayl/upscayl#632] opened 2024-01-08 07:15 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Can we have a Google Colab version of this? So that those people who don't own a powerful GPU can use Google Provided GPUs?

**Comment by NayamAmarshe** [comment] 2024-01-08 07:51
Duplicate of #56

**Closed** 2024-01-08 07:51 UTC
Labels: enhancement
