### ISSUE TITLE
UB2 (intel only Mac build)

### ISSUE THREAD

**Issue by moebis** [upscayl/upscayl#431] opened 2023-08-28 19:05 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

The current version 2.5.5 is compiled for intel only. Will there be a UB2 (universal binary) or Apple Silicon (arm64) version soon?

### Related Problem(s)

The current version 2.5.5 is compiled for intel only. Will there be a UB2 (universal binary) or Apple Silicon (arm64) version soon?

### Alternatives

The current version 2.5.5 is compiled for intel only. Will there be a UB2 (universal binary) or Apple Silicon (arm64) version soon?

**Comment by aaronliu0130** [comment] 2023-08-28 20:48
Duplicate of #333.
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-08-28 20:48 UTC
Labels: enhancement
