### ISSUE TITLE
API access

### ISSUE THREAD

**Issue by dbhurley** [upscayl/upscayl#287] opened 2023-04-26 00:37 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

No issues, would love to see the system accessible via an API endpoint.

### Alternatives

Allow the form to be submitted without the UI and parse the response out as a JSON

**Comment by aaronliu0130** [comment] 2023-04-26 19:13
Duplicate of #10 and the FAQ.
>- Is there a CLI available?
> - - The CLI tool is called real-esrgan-ncnn-vulkan and it's available on the Real-ESRGAN repository.

> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-04-26 19:13 UTC
Labels: enhancement

**Comment by infinity0** [comment] 2024-03-02 15:29
Upscayl in fact does have an internal CLI, which you can see, together with its CLI args, in the stdout logs it outputs when processing an image. On GNU/Linux this is located at `/opt/Upscayl/resources/bin/upscayl-bin`. It even takes `--help` so you can see what all the options are.
