### ISSUE TITLE
The resulting image becomes a square box

### ISSUE THREAD

**Issue by Rzk7** [upscayl/upscayl#349] opened 2023-06-09 04:40 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Hi, I tried upscayl today, and the result is like a big pixel box. Previously it was not like this, I have also tried downloading and reinstalling but the result is still the same. I am using the latest version (upscayl-2.5.5)

### To Reproduce

1. Import image from folder

### Expected Behavior

The resulting image should be upscaled

### Version/Commit Hash

upscayl-2.5.5

### OS Specifics

Windows 10, GTX 1650

### Screenshots

![Untitled](https://github.com/upscayl/upscayl/assets/136048652/7db30752-beb7-4859-81ab-30d2f12eb27a)
![Untitled2](https://github.com/upscayl/upscayl/assets/136048652/3c584d4a-34a6-44ce-8028-d050d7327ce7)

**Comment by NayamAmarshe** [comment] 2023-06-09 04:57
Duplicate of #303

**Closed by NayamAmarshe** 2023-06-09 04:57 UTC
Labels: bug

**Comment by Rzk7** [comment] 2023-06-09 05:13
Thank You :)
