### ISSUE TITLE
Localized languages

### ISSUE THREAD

**Issue by DaimuX** [upscayl/upscayl#734] opened 2024-03-02 13:38 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Is it possible to consider making some open localization language packs so that people can contribute localized languages

**Comment by aaronliu0130** [comment] 2024-03-02 17:20
Duplicate of #91 
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-03-02 17:20 UTC
Labels: enhancement
