### ISSUE TITLE
Add the Feature to set the output size in the tool!

### ISSUE THREAD

**Issue by TheNopCrafter** [upscayl/upscayl#203] opened 2023-01-14 11:11 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

Hey, I use Upscale, and it's the best tool I've ever used, thanks for a great job!

(I checked the FAQ and hopefully everywhere. If I missed something that this feature has already been requested or is in the tool, then I'm sorry…)

### Description

I want that you can say how big/witch size the picture that is upscaled has. So that you can say 1x 2x 4x 8x etc.

Example:

The original Picture is 500×500 px

Then I can say 1x, so that the picture is the same size, only sharper and more detail on the fewer pixels
2x means 1000×1000, 4x is 2000×2000 etc. Hope you understand! :)

So, in detail, I want that you can set die output size of the upscaled picture!

### Alternatives

I think no.

**Comment by NayamAmarshe** [comment] 2023-01-14 11:55
Duplicate of https://github.com/upscayl/upscayl/issues/144 https://github.com/upscayl/upscayl/issues/8 

>  I have checked that this issue isn't addressed in any other issue or pull request.

![image](https://user-images.githubusercontent.com/25067102/212470467-2f4b1b20-4663-4de2-99ad-6aa49efb8f69.png)

**Closed by NayamAmarshe** 2023-01-14 11:55 UTC
Labels: enhancement
