### ISSUE TITLE
JPG impossible avec Batch Upscale

### ISSUE THREAD

**Issue by Charlie-82** [upscayl/upscayl#238] opened 2023-03-07 11:12 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Pour faire un batch, je sélectionne JPG, mais j'obtiens toujours des fichiers PNG
To do a batch, I select JPG, but I always get PNG files
![000507](https://user-images.githubusercontent.com/127202274/223405092-27188673-0c67-4bd8-8e1f-4506036a0005.jpg)

### To Reproduce

![000507](https://user-images.githubusercontent.com/127202274/223405316-68cc8fae-2570-4c15-8d9c-2e6bb8a66e1d.jpg)

Faire un batch et choisir jpg en sortie image

### Expected Behavior

Obtenir Fichiers jpeg et non png... 
![000508](https://user-images.githubusercontent.com/127202274/223406236-d8e868ef-5e93-4134-97f9-3f15aa955977.jpg)

### Version/Commit Hash

2.0.1

### OS Specifics

Nvidia GTX970

**Comment by aaronliu0130** [comment] 2023-03-07 17:20
Duplicate of #174
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-03-07 18:26 UTC
Labels: bug
