### ISSUE TITLE
Icon is too big on Mac

### ISSUE THREAD

**Issue by jfdnet** [upscayl/upscayl#306] opened 2023-05-10 07:12 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
<summary>Logs</summary>
<pre>

Icon is too big on Mac
</pre>
</details>

### To Reproduce

Icon is too big on Mac

### Expected Behavior

Icon is too big on Mac

### Version/Commit Hash

2.5.1

### OS Specifics

M2 macbook pro 14 / Macos 13.3.1

**Comment by NayamAmarshe** [comment] 2023-05-10 07:27
Could you please post a screenshot?

**Comment by coolst3r** [comment] 2023-05-15 19:19
you can install a mac on linux using amd gpu pass through

**Comment by aaronliu0130** [comment] 2023-05-15 20:51
Hackintoshing, while possible, is still a long and tedious process, nor is it guaranteed that we can find out the problem even on a Mac.

**Comment by coolst3r** [comment] 2023-05-16 09:14
> Hackintoshing, while possible, is still a long and tedious process, nor is it guaranteed that we can find out the problem even on a Mac.

yeah but you can recreate and debug it if you hackintosh

**Comment by aaronliu0130** [comment] 2023-05-16 12:24
I can in fact recreate it, but not debug it. Just being able to run macOS does not magically tell us where the problem is.

**Comment by coolst3r** [comment] 2023-05-16 13:56
> I can in fact recreate it, but not debug it. Just being able to run macOS does not magically tell us where the problem is.
the bug happens on macs so how does testing it on a mac not help recreate it can please explain in detail why

**Comment by coolst3r** [comment] 2023-05-16 13:57
> I can in fact recreate it, but not debug it. Just being able to run macOS does not magically tell us where the problem is.
you can debug it just use a ide and debug the gui sections

**Comment by jfdnet** [comment] 2023-05-16 14:43
> Okay, that indeed is quite large.
> 
> Not sure what's wrong. I don't have a Mac anymore😅 I'll add it to the project tracking board and try to fix it. Thanks for reporting.


May it be helpful?

https://stackoverflow.com/questions/71118094/why-is-my-app-icon-bigger-than-the-others-in-the-macos-dock

**Comment by aaronliu0130** [comment] 2023-05-16 15:39
@coolst3r You can’t debug an issue that doesn’t have anything to do with the code.

**Comment by NayamAmarshe** [comment] 2023-05-16 23:38
> > Okay, that indeed is quite large.
> > 
> > Not sure what's wrong. I don't have a Mac anymore😅 I'll add it to the project tracking board and try to fix it. Thanks for reporting.
> 
> 
> May it be helpful?
> 
> https://stackoverflow.com/questions/71118094/why-is-my-app-icon-bigger-than-the-others-in-the-macos-dock

Thank you. Seems like there's some padding required.

**Comment by NayamAmarshe** [comment] 2023-06-04 07:33
Fixed in https://github.com/upscayl/upscayl/commit/64065e875f7c5be2a5b2876cad87fa35043859db

Could you please check if the icns file is alright?

**Closed** 2023-06-04 07:34 UTC
Labels: bug
