### ISSUE TITLE
No image in display area

### ISSUE THREAD

**Issue by GabrielLN88** [upscayl/upscayl#626] opened 2024-01-05 01:32 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [X] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Describe the Bug

I can't seem to get the image to show in the main display. 

### To Reproduce

Loading in an image or upscaling an image results in no image on display.

![Screenshot 2024-01-04 164816](https://github.com/upscayl/upscayl/assets/155691700/efb2e9d3-f965-44c0-b5af-0c8c8f258099)

### Version (or commit hash)

2.9.5

### Select your Operating System

Windows

### OS Version

11

### GPU Name

RTX 4080

### Expected Behavior

image should be displayed

### Screenshots

![Screenshot 2024-01-04 164816](https://github.com/upscayl/upscayl/assets/155691700/2b3d1074-beea-4719-9cb4-e853b0ff5814)

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  💾 Updating Save Output Folder:  false
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"\\\\CTM-NAS1\\Google Drive\\Gabriel LN\\Midjourney\\lake cabin\\lake cabin.png","extension":"png"}
🖼 Setting image path:  \\CTM-NAS1\Google Drive\Gabriel LN\Midjourney\lake cabin\lake cabin.png
🗂 Setting output path:  \\CTM-NAS1\Google Drive\Gabriel LN\Midjourney\lake cabin
🖼 imagePath:  \\CTM-NAS1\Google Drive\Gabriel LN\Midjourney\lake cabin\lake cabin.png
🔤 Extension:  png
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
```

**Comment by NayamAmarshe** [comment] 2024-01-05 02:32
Duplicate of #567

**Closed** 2024-01-05 02:33 UTC
Labels: bug
