### ISSUE TITLE
Upscayl Flatpak crashes on launch on Wayland

### ISSUE THREAD

**Issue by dsbrown** [upscayl/upscayl#591] opened 2023-12-04 21:08 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [ ] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).
- [ ] I am using Windows and I've tried [common troubleshooting steps](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

### Paste the logs

```sh
Sorry no logs were generated on the Fedora reporting manager, but if you give me a place to look, I will follow up. I can't actually go to the settings tab of course since it crashes before I can get there.
```

### Describe the Bug

Upscayl crashes on launch on Fedora 39, installed from flathub v2.9.1. I tried installing from flathub using the Fedora GUI, Discover, and from the command line 'flatpak install' . The workaround, for now is to use the Appimage binary which is working. I  tried installing and uninstalling several times and of course deleting all user data. 

### To Reproduce

Install program from Fedora Discover or from flatpak command line. Launch and be sad.

### Version (or commit hash)

v2.9.1

### Select your Operating System

Linux

### OS Version

Operating System: Fedora Linux 39 KDE Plasma Version: 5.27.9 KDE Frameworks Version: 5.111.0 Qt Version: 5.15.11 Kernel Version: 6.6.3-200.fc39.x86_64 (64-bit) Graphics Platform: Wayland Processors: 16 × AMD Ryzen 7 5700G with Radeon Graphics Memory: 31.1 GiB of RAM 

### GPU Name

Graphics Processor: AMD Radeon RX 6750 XT Manufacturer: ASUS

### Expected Behavior

Launch baby launch, please don't explode on the pad.

### Screenshots

Nothing fun to look at. Just failed to generate report.

**Comment by aaronliu0130** [comment] 2023-12-04 21:11
What does the command line say when you do `flatpak run org.upscayl.Upscayl`?

**Comment by alcir** [comment] 2023-12-05 11:48
```
$ flatpak run org.upscayl.Upscayl
[3:1205/124805.387905:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1205/124805.958670:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[3:1205/124805.958681:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
/app/bin/upscayl-run: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper /app/upscayl/upscayl
```

**Comment by aaronliu0130** [comment] 2023-12-05 11:56
Are you using Wayland? (Which also should be supported…)

**Comment by alcir** [comment] 2023-12-05 12:10
> Are you using Wayland? (Which also should be supported…)

Yes I am.
Thanks.

**Comment by NayamAmarshe** [comment] 2023-12-05 12:46
Sorry for the trouble. Looks like my wayland changes didn't work properly.

**Comment by RayJW** [comment] 2023-12-05 12:52
I don't think that causes the issue, but I saw that you added flags that are not needed to the .desktop file. Since Upscayl uses a relatively recent Electron version, these flags should be enough `--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations`. By adding `--ozone-platform=wayland` you always force Wayland even if the user is not using it, `--ozone-platform-hint=auto` should already handle both cases and `--enable-features=UseOzonePlatform` is already the default on recent Electron versions.

But since this person is using Wayland, that probably isn't causing these issues.

**Comment by BigBoyBarney** [comment] 2023-12-07 12:43
> [barney@barney-pc ~]$ flatpak run org.upscayl.Upscayl
[3:1207/134140.435814:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1207/134140.691918:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[3:1207/134140.691926:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
/app/bin/upscayl-run: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper /app/upscayl/upscayl

I know this provides no new information, just wanted to say that I'm running into the same issue on Fedora 38 wayland, also flatpak. Upscayl has been working until just now, so it's not an Upscayl update that broke it directly.

Thank you for the app, it's fantastic!
Cheers

**Comment by NayamAmarshe** [comment] 2023-12-09 03:53
> ![image](https://private-user-images.githubusercontent.com/11874211/288901950-2e19f1c0-9ecd-43e4-ae15-f9dbeb887999.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwOTQzMTIsIm5iZiI6MTcwMjA5NDAxMiwicGF0aCI6Ii8xMTg3NDIxMS8yODg5MDE5NTAtMmUxOWYxYzAtOWVjZC00M2U0LWFlMTUtZjlkYmViODg3OTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAzNTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYTQzYjM0NjliMTc0NzZjMDZhYzg2OTNiNWRlY2RhYmRmM2FkMWYwMjIyOTQ3MDZkNzNlMmQ5ZDIwZjg5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7miXd5aXHcag7RKX7ZSKLMwSyUQuG-Xv83qop9JMXg) @NayamAmarshe Did we forget to change the version number listing for Flathub?

Oh strange. I'll check

**Comment by NayamAmarshe** [comment] 2023-12-09 03:54
<img width="547" alt="image" src="https://github.com/upscayl/upscayl/assets/25067102/3dc76cdd-db31-4b3d-bcca-168410685011">

**Comment by heinwol** [comment] 2023-12-09 22:52
I can reproduce this issue, nixos-unstable, upscayl flatpak v2.9.5. Appimage works just fine though, seems like a packaging issue indeed

**Comment by FaridZelli** [comment] 2023-12-10 00:15
Also reproducible on openSUSE Tumbleweed at the moment.

**Comment by gaxweb** [comment] 2023-12-11 14:08
I can get it to work on Fedora 38 under Wayland, if I use Flatseal to disable the `socket=fallback-x11` permission.

To fix the non-fatal issue with D-Bus, you need to enable `socket=system-bus`.

**Comment by BigBoyBarney** [comment] 2023-12-11 14:16
I can confirm that disabling `Fallback to X11 windowing system` solves the issue and Upscayl starts normall. However, it runs under X —and not wayland—as tested with `xeyes`.

![image](https://github.com/upscayl/upscayl/assets/86712892/ca72d48b-c1d1-432e-94ba-de9503c03a62)

**Comment by K1Hyve** [comment] 2023-12-15 01:09
> I can confirm that disabling `Fallback to X11 windowing system` solves the issue and Upscayl starts normally. However, it runs under X —and not wayland—as tested with `xeyes`. If I `X11 windowing system` is disabled, Upscayl will not run, even though I'm fairly certain it used to.

Thank you! Upscayl with this change.

**Comment by NayamAmarshe** [comment] 2023-12-26 09:34
Should be fixed now, sorry for the delay.

**Comment by NayamAmarshe** [comment] 2023-12-26 15:59
Oops, still crashing for me on Zorin 17 Wayland

**Comment by heinwol** [comment] 2023-12-26 19:40
Works fine for me now

**Comment by NayamAmarshe** [comment] 2023-12-27 04:02
Seems like there's an issue with nvidia. Doesn't launch there.

**Closed** 2024-01-15 15:31 UTC
Labels: bug
