### ISSUE TITLE
Upscale doesn't work with custom Width option

### ISSUE THREAD

**Issue by myillstudio** [upscayl/upscayl#807] opened 2024-05-02 16:48 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

Upscale doesn't work with Custom Width option. When I try to Upscayl a custom width it goes through the routine but when it comes to creating the new file it fails. It creates a file which appears to be a fraction of the expected size and no thumbnail
<img width="414" alt="Screen Shot 2024-04-29 at 2 17 44 PM" src="https://github.com/upscayl/upscayl/assets/163213490/94f985d1-dcc6-409a-a25b-74387b80fbd5">
and Photoshop gets a error trying o open it. The file “5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E_upscayl_1600px_ultrasharp.jpg” could not be opened.
This happens now after I deleted the app and tried reinstalling it. The previous install of Upscayl gave a permissions error for the new file and no new file was created.

### To Reproduce

On a Mac OS 12.7.4 Run upscayl in Custom Width mode.

### Upscayl Version (or commit hash)

2.11.0

### Platform

Linux

### OS Version

12.7.4

### GPU Name

AMD Radeon R9 M390 2 GB

### Expected Behavior

It should've created a new custom width file that can be opened it Photoshop.

### Logs

```sh
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"/Users/steveworon/Downloads/-U_uMfQnSCOwjv0OZ3tezQ-fotor-202405020415.png","extension":"png"}
🖼 Setting image path:  /Users/steveworon/Downloads/-U_uMfQnSCOwjv0OZ3tezQ-fotor-202405020415.png
🗂 Setting output path:  /Users/steveworon/Downloads
🖼 imagePath:  /Users/steveworon/Downloads/-U_uMfQnSCOwjv0OZ3tezQ-fotor-202405020415.png
🔤 Extension:  png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png","extension":"png"}
🖼 Setting image path:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png
🗂 Setting output path:  /Users/steveworon/Downloads/Spy Standing Outdoors
🖼 imagePath:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png
🔤 Extension:  png
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"/Users/steveworon/Downloads/Spy Standing Outdoors","fileNameWithExt":"1t-oZW61SkuGRuj2NTpnWw.png","outputDir":"/Users/steveworon/Downloads/Spy Standing Outdoors","outFile":"/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg","fileName":"1t-oZW61SkuGRuj2NTpnWw","scale":"4","compression":"0","customWidth":"1600","useCustomWidth":true,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png,-o,/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,ultrasharp,-f,jpg,-w,1600,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","args":["/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","-i","/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png","-o","/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg","-m","/Applications/Upscayl.app/Contents/Resources/models","-n","ultrasharp","-f","jpg","-w","1600","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  🚀 Starting Upscayl - Copyright © 2024

🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024

🎒 BACKEND REPORTED:  ✨ Using the default scale x4

🚧 UPSCAYL_PROGRESS:  ✨ Using the default scale x4

🎒 BACKEND REPORTED:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  3.57%

🚧 UPSCAYL_PROGRESS:  3.57%

🎒 BACKEND REPORTED:  7.14%

🚧 UPSCAYL_PROGRESS:  7.14%

🎒 BACKEND REPORTED:  10.71%
100.00%

🚧 UPSCAYL_PROGRESS:  10.71%
100.00%

🎒 BACKEND REPORTED:  14.29%

🚧 UPSCAYL_PROGRESS:  14.29%

🎒 BACKEND REPORTED:  17.86%

🚧 UPSCAYL_PROGRESS:  17.86%

🎒 BACKEND REPORTED:  21.43%

🚧 UPSCAYL_PROGRESS:  21.43%

🎒 BACKEND REPORTED:  25.00%
100.00%

🚧 UPSCAYL_PROGRESS:  25.00%
100.00%

🎒 BACKEND REPORTED:  28.57%

🚧 UPSCAYL_PROGRESS:  28.57%

🎒 BACKEND REPORTED:  32.14%

🚧 UPSCAYL_PROGRESS:  32.14%

🎒 BACKEND REPORTED:  35.71%

🚧 UPSCAYL_PROGRESS:  35.71%

🎒 BACKEND REPORTED:  39.29%
100.00%

🚧 UPSCAYL_PROGRESS:  39.29%
100.00%

🎒 BACKEND REPORTED:  42.86%

🚧 UPSCAYL_PROGRESS:  42.86%

🎒 BACKEND REPORTED:  46.43%

🚧 UPSCAYL_PROGRESS:  46.43%

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  53.57%
100.00%

🚧 UPSCAYL_PROGRESS:  53.57%
100.00%

🎒 BACKEND REPORTED:  57.14%

🚧 UPSCAYL_PROGRESS:  57.14%

🎒 BACKEND REPORTED:  60.71%

🚧 UPSCAYL_PROGRESS:  60.71%

🎒 BACKEND REPORTED:  64.29%

🚧 UPSCAYL_PROGRESS:  64.29%

🎒 BACKEND REPORTED:  67.86%
100.00%

🚧 UPSCAYL_PROGRESS:  67.86%
100.00%

🎒 BACKEND REPORTED:  71.43%

🚧 UPSCAYL_PROGRESS:  71.43%

🎒 BACKEND REPORTED:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🎒 BACKEND REPORTED:  78.57%

🚧 UPSCAYL_PROGRESS:  78.57%

🎒 BACKEND REPORTED:  82.14%
100.00%

🚧 UPSCAYL_PROGRESS:  82.14%
100.00%

🎒 BACKEND REPORTED:  85.71%

🚧 UPSCAYL_PROGRESS:  85.71%

🎒 BACKEND REPORTED:  89.29%

🚧 UPSCAYL_PROGRESS:  89.29%

🎒 BACKEND REPORTED:  92.86%

🚧 UPSCAYL_PROGRESS:  92.86%

🎒 BACKEND REPORTED:  96.43%
100.00%

🚧 UPSCAYL_PROGRESS:  96.43%
100.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to desired resolution

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to desired resolution

🎒 BACKEND REPORTED:  🏞️ Resized image from 768x1232 to 1600x-1162901328

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 768x1232 to 1600x-1162901328

🎒 BACKEND REPORTED:  🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg
💯 UPSCAYL_DONE:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"/Users/steveworon/Downloads/Spy Standing Outdoors","fileNameWithExt":"1t-oZW61SkuGRuj2NTpnWw.png","outputDir":"/Users/steveworon/Downloads/Spy Standing Outdoors","outFile":"/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_3x_ultrasharp.jpg","fileName":"1t-oZW61SkuGRuj2NTpnWw","scale":"3","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png,-o,/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_3x_ultrasharp.jpg,-s,3,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,ultrasharp,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","args":["/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","-i","/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw.png","-o","/Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_1600px_ultrasharp.jpg","-m","/Applications/Upscayl.app/Contents/Resources/models","-n","ultrasharp","-f","jpg","-w","1600","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  🚀 Starting Upscayl - Copyright © 2024
✨ Using the default scale x4

🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024
✨ Using the default scale x4

🎒 BACKEND REPORTED:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  3.57%

🚧 UPSCAYL_PROGRESS:  3.57%

🎒 BACKEND REPORTED:  7.14%

🚧 UPSCAYL_PROGRESS:  7.14%

🎒 BACKEND REPORTED:  10.71%
100.00%

🚧 UPSCAYL_PROGRESS:  10.71%
100.00%

🎒 BACKEND REPORTED:  14.29%

🚧 UPSCAYL_PROGRESS:  14.29%

🎒 BACKEND REPORTED:  17.86%

🚧 UPSCAYL_PROGRESS:  17.86%

🎒 BACKEND REPORTED:  21.43%

🚧 UPSCAYL_PROGRESS:  21.43%

🎒 BACKEND REPORTED:  25.00%
100.00%

🚧 UPSCAYL_PROGRESS:  25.00%
100.00%

🎒 BACKEND REPORTED:  28.57%

🚧 UPSCAYL_PROGRESS:  28.57%

🎒 BACKEND REPORTED:  32.14%

🚧 UPSCAYL_PROGRESS:  32.14%

🎒 BACKEND REPORTED:  35.71%

🚧 UPSCAYL_PROGRESS:  35.71%

🎒 BACKEND REPORTED:  39.29%
100.00%

🚧 UPSCAYL_PROGRESS:  39.29%
100.00%

🎒 BACKEND REPORTED:  42.86%

🚧 UPSCAYL_PROGRESS:  42.86%

🎒 BACKEND REPORTED:  46.43%

🚧 UPSCAYL_PROGRESS:  46.43%

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  53.57%
100.00%

🚧 UPSCAYL_PROGRESS:  53.57%
100.00%

🎒 BACKEND REPORTED:  57.14%

🚧 UPSCAYL_PROGRESS:  57.14%

🎒 BACKEND REPORTED:  60.71%

🚧 UPSCAYL_PROGRESS:  60.71%

🎒 BACKEND REPORTED:  64.29%

🚧 UPSCAYL_PROGRESS:  64.29%

🎒 BACKEND REPORTED:  67.86%
100.00%

🚧 UPSCAYL_PROGRESS:  67.86%
100.00%

🎒 BACKEND REPORTED:  71.43%

🚧 UPSCAYL_PROGRESS:  71.43%

🎒 BACKEND REPORTED:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🎒 BACKEND REPORTED:  78.57%

🚧 UPSCAYL_PROGRESS:  78.57%

🎒 BACKEND REPORTED:  82.14%
100.00%

🚧 UPSCAYL_PROGRESS:  82.14%
100.00%

🎒 BACKEND REPORTED:  85.71%

🚧 UPSCAYL_PROGRESS:  85.71%

🎒 BACKEND REPORTED:  89.29%

🚧 UPSCAYL_PROGRESS:  89.29%

🎒 BACKEND REPORTED:  92.86%

🚧 UPSCAYL_PROGRESS:  92.86%

🎒 BACKEND REPORTED:  96.43%
100.00%

🚧 UPSCAYL_PROGRESS:  96.43%
100.00%

🎒 BACKEND REPORTED:  🏞️ Resizing image according to output scale

🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🎒 BACKEND REPORTED:  🏞️ Resized image from 768x1232 to 2304x3696

🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 768x1232 to 2304x3696

🎒 BACKEND REPORTED:  🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_3x_ultrasharp.jpg
💯 UPSCAYL_DONE:  /Users/steveworon/Downloads/Spy Standing Outdoors/1t-oZW61SkuGRuj2NTpnWw_upscayl_3x_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
```

**Comment by aaronliu0130** [comment] 2024-05-02 20:43
Bizarre. Could you reproduce this with the 5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E picture and send the logs for that picture instead?

**Comment by myillstudio** [comment] 2024-05-03 04:29
Heres the code: Trying create a JPEG ⚙️ Getting saveImageAs from localStorage:  jpg⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}⚙️ Setting gpuId to empty string🔀 Setting model to 🔀 Setting model to ultrasharp⚙️ Getting saveImageAs from localStorage:  jpg⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}⚙️ Setting gpuId to empty string🔄 Resetting image paths⤵️ Dropped file:  {"type":"image/jpeg","filePath":"/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg","extension":"jpeg"}🖼 Setting image path:  /Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg🗂 Setting output path:  /Users/steveworon/Downloads/Spy Wetsuit🖼 imagePath:  /Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg🔤 Extension:  jpeg⚙️ Getting saveImageAs from localStorage:  jpg⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}⚙️ Setting gpuId to empty string🔀 Setting model to 🔀 Setting model to ultrasharp🔄 Resetting Upscaled Image Path🏁 UPSCAYL🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"/Users/steveworon/Downloads/Spy Wetsuit","fileNameWithExt":"5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg","outputDir":"/Users/steveworon/Downloads/Spy Wetsuit","outFile":"/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2_upscayl_2500px_ultrasharp.jpg","fileName":"5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2","scale":"3","compression":"0","customWidth":"2500","useCustomWidth":true,"tileSize":null}🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg,-o,/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2_upscayl_2500px_ultrasharp.jpg,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,ultrasharp,-f,jpg,-w,2500,-c,0🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","args":["/Applications/Upscayl.app/Contents/Resources/bin/upscayl-bin","-i","/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2.jpeg","-o","/Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2_upscayl_2500px_ultrasharp.jpg","-m","/Applications/Upscayl.app/Contents/Resources/models","-n","ultrasharp","-f","jpg","-w","2500","-c","0"]}🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false🎒 BACKEND REPORTED:  🚀 Starting Upscayl - Copyright © 2024
🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024
🎒 BACKEND REPORTED:  ✨ Using the default scale x4
🚧 UPSCAYL_PROGRESS:  ✨ Using the default scale x4
🎒 BACKEND REPORTED:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1][0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=110  bugcopc=0  bugihfa=0[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
🚧 UPSCAYL_PROGRESS:  [0 AMD Radeon R9 M390]  queueC=0[1]  queueG=0[1]  queueT=0[1][0 AMD Radeon R9 M390]  bugsbn1=0  bugbilz=110  bugcopc=0  bugihfa=0[0 AMD Radeon R9 M390]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1[0 AMD Radeon R9 M390]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1
🎒 BACKEND REPORTED:  0.00%
🚧 UPSCAYL_PROGRESS:  0.00%
🎒 BACKEND REPORTED:  2.86%
🚧 UPSCAYL_PROGRESS:  2.86%
🎒 BACKEND REPORTED:  5.71%
🚧 UPSCAYL_PROGRESS:  5.71%
🎒 BACKEND REPORTED:  8.57%
🚧 UPSCAYL_PROGRESS:  8.57%
🎒 BACKEND REPORTED:  11.43%100.00%
🚧 UPSCAYL_PROGRESS:  11.43%100.00%
🎒 BACKEND REPORTED:  14.29%
🚧 UPSCAYL_PROGRESS:  14.29%
🎒 BACKEND REPORTED:  17.14%
🚧 UPSCAYL_PROGRESS:  17.14%
🎒 BACKEND REPORTED:  20.00%
🚧 UPSCAYL_PROGRESS:  20.00%
🎒 BACKEND REPORTED:  22.86%
🚧 UPSCAYL_PROGRESS:  22.86%
🎒 BACKEND REPORTED:  25.71%100.00%
🚧 UPSCAYL_PROGRESS:  25.71%100.00%
🎒 BACKEND REPORTED:  28.57%
🚧 UPSCAYL_PROGRESS:  28.57%
🎒 BACKEND REPORTED:  31.43%
🚧 UPSCAYL_PROGRESS:  31.43%
🎒 BACKEND REPORTED:  34.29%
🚧 UPSCAYL_PROGRESS:  34.29%
🎒 BACKEND REPORTED:  37.14%
🚧 UPSCAYL_PROGRESS:  37.14%
🎒 BACKEND REPORTED:  40.00%100.00%
🚧 UPSCAYL_PROGRESS:  40.00%100.00%
🎒 BACKEND REPORTED:  42.86%
🚧 UPSCAYL_PROGRESS:  42.86%
🎒 BACKEND REPORTED:  45.71%
🚧 UPSCAYL_PROGRESS:  45.71%
🎒 BACKEND REPORTED:  48.57%
🚧 UPSCAYL_PROGRESS:  48.57%
🎒 BACKEND REPORTED:  51.43%
🚧 UPSCAYL_PROGRESS:  51.43%
🎒 BACKEND REPORTED:  54.29%100.00%
🚧 UPSCAYL_PROGRESS:  54.29%100.00%
🎒 BACKEND REPORTED:  57.14%
🚧 UPSCAYL_PROGRESS:  57.14%
🎒 BACKEND REPORTED:  60.00%
🚧 UPSCAYL_PROGRESS:  60.00%
🎒 BACKEND REPORTED:  62.86%
🚧 UPSCAYL_PROGRESS:  62.86%
🎒 BACKEND REPORTED:  65.71%
🚧 UPSCAYL_PROGRESS:  65.71%
🎒 BACKEND REPORTED:  68.57%100.00%
🚧 UPSCAYL_PROGRESS:  68.57%100.00%
🎒 BACKEND REPORTED:  71.43%
🚧 UPSCAYL_PROGRESS:  71.43%
🎒 BACKEND REPORTED:  74.29%
🚧 UPSCAYL_PROGRESS:  74.29%
🎒 BACKEND REPORTED:  77.14%
🚧 UPSCAYL_PROGRESS:  77.14%
🎒 BACKEND REPORTED:  80.00%
🚧 UPSCAYL_PROGRESS:  80.00%
🎒 BACKEND REPORTED:  82.86%100.00%
🚧 UPSCAYL_PROGRESS:  82.86%100.00%
🎒 BACKEND REPORTED:  85.71%
🚧 UPSCAYL_PROGRESS:  85.71%
🎒 BACKEND REPORTED:  88.57%
🚧 UPSCAYL_PROGRESS:  88.57%
🎒 BACKEND REPORTED:  91.43%
🚧 UPSCAYL_PROGRESS:  91.43%
🎒 BACKEND REPORTED:  94.29%
🚧 UPSCAYL_PROGRESS:  94.29%
🎒 BACKEND REPORTED:  97.14%100.00%
🚧 UPSCAYL_PROGRESS:  97.14%100.00%
🎒 BACKEND REPORTED:  🏞️ Resizing image according to desired resolution
🚧 UPSCAYL_PROGRESS:  🏞️ Resizing image according to desired resolution
🎒 BACKEND REPORTED:  🏞️ Resized image from 832x1216 to 2500x-1143183248🚨 Error: Couldn't write the image /Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2_upscayl_2500px_ultrasharp.jpg
🔄 Resetting image paths🚧 UPSCAYL_PROGRESS:  🏞️ Resized image from 832x1216 to 2500x-1143183248🚨 Error: Couldn't write the image /Users/steveworon/Downloads/Spy Wetsuit/5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E-2_upscayl_2500px_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage:  jpg⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}⚙️ Setting gpuId to empty string
    On Thursday, May 2, 2024, 04:44:06 PM EDT, Aaron Liu ***@***.***> wrote:  
 
 


Bizarre. Could you reproduce this with the 5F53CDAABD836A52DA17D5D85157444CFC09088FE0812E6D9916F987AFEF978E picture and send the logs for that picture instead?

**Comment by NayamAmarshe** [comment] 2024-05-03 06:01
Duplicate of #794

**Comment by NayamAmarshe** [comment] 2024-05-03 06:02
Please read this: https://github.com/upscayl/upscayl/issues/794#issuecomment-2081446991

**Comment by aaronliu0130** [comment] 2024-05-03 13:06
The issue isn't that the image is wrong, it's that the image can't be opened at all, and logs indicate a write error.

**Comment by aaronliu0130** [comment] 2024-05-03 13:07
Wait,

**Closed by aaronliu0130** 2024-05-03 13:07 UTC
Labels: bug
