### ISSUE TITLE
Preview: one portrait and the other landscape

### ISSUE THREAD

**Issue by ZuluPilgrim** [upscayl/upscayl#169] opened 2022-12-26 03:08 UTC
Once my image has been upscayl'd the preview shows the origional in portait and th upscayl'd one in landscape, making it hard to compare them side by side. This has only started happening since I upgraded to 2.0.0.

**Comment by NayamAmarshe** [comment] 2022-12-26 08:39
Duplicate of #68

**Closed** 2022-12-26 08:39 UTC
