### ISSUE TITLE
Batch processing only stores PNG

### ISSUE THREAD

**Issue by sgoehler** [upscayl/upscayl#280] opened 2023-04-19 23:16 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

By the FAQ, batch processing can't save PNGs, only JPGs, but version 2.0.1 ONLY saves PNGs and ignores the selected output format - JPG selection seems to be ignored.

### To Reproduce

- Select batch input folder
- Set output format to JPG
- Start batch process

### Expected Behavior

Expected JPEG, got PNG

### Version/Commit Hash

2.0.1

### OS Specifics

Windows 11, RTX 2080

**Comment by aaronliu0130** [comment] 2023-04-20 00:30
Duplicate of #174.
> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-04-20 00:30 UTC
Labels: bug
