### ISSUE TITLE
Suggestion: Possible you guys can implement PNG  compression as well?

### ISSUE THREAD

**Issue by CptJackieSparrow** [upscayl/upscayl#225] opened 2023-02-11 20:10 UTC
Possible you guys can implement PNG  compression as well?
These guys are killing it: https://pngquant.org/

**Comment by aaronliu0130** [comment] 2023-02-11 22:07
That is lossy compression which goes against the reason you are upscayling in the first place. Plus this is a duplicate of #116 #78 and the like.

**Comment by veikk0** [comment] 2023-02-27 00:08
The fastest lossless PNG optimizer I know is [oxipng](https://github.com/shssoichiro/oxipng), which is written in Rust (also available as a library, though I only use the CLI). With the material I'm currently upscaling, I'm able to reduce the size of the output PNGs by ~30% using oxipng's fastest setting (-o 1). On an i5-6200U, the user+sys time was 13.94 seconds, which is fairly cheap since this is a 15W mobile chip from 2015.

JPEG XL would be a more long-term solution. On the fastest [libjxl](https://github.com/libjxl/libjxl) setting (effort 1, q 100 i.e. lossless) it reduced file size by about 38% while being absolutely blazing fast (less than one second user+sys time). Effort 3 reduces size by 50% while using 8.91 seconds of user+sys time, which is still fast (these are 5120x2880 images). It's diminishing returns after that.

I don't know what settings are currently used for PNGs, but it's not the most space-optimized ones. It's always a tradeoff between compute and file size, and PNG can get pretty heavy when you want to get the upper end of efficiency out of it at high resolutions. And for many PNG libraries the output file size seems to be a secondary consideration anyway, at least compared to what oxipng can do.

**Comment by aaronliu0130** [comment] 2023-02-27 01:27
First of all, disregard what I said, I misinterpreting that PR.
Secondly, how can we implement a rust application into an electron project? The only option I know is to include binaries for the platforms we support, like what we're currently doing with the REAL-ERSGAN binary. However that would affect build size a lot since we're putting in another triple-binary

**Comment by NayamAmarshe** [comment] 2023-03-04 02:06
Hi sorry, PNG compression is not possible right now. I wouldn't mind a PR but I won't be able to make time for it :(

**Closed by NayamAmarshe** 2023-03-04 02:06 UTC
