### ISSUE TITLE
progress text not visible on dark images.

### ISSUE THREAD

**Issue by Cyborgscode** [upscayl/upscayl#224] opened 2023-02-11 13:17 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

While processing a file, there is the gray progress text over the blurred image.

It's gray, which is very bad readable with dark parts at that position. 

### Description

A small "check the pixel value / adapt color to it" magic,  would be helpful. 

### Alternatives

If thats too much effort, a half  transparent background  with another color behind the text would be ok too.

**Comment by Cyborgscode** [comment] 2023-02-11 13:19
![upscale bug](https://user-images.githubusercontent.com/8317797/218260093-a57329cf-146e-48f2-ba6b-ca05cdd9a9c7.png)
![upscale bug2](https://user-images.githubusercontent.com/8317797/218260140-673f5bd9-fcd0-4dfd-9c28-09e1515eb4da.png)

**Comment by aaronliu0130** [comment] 2023-02-11 22:01
Duplicate of #206.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-02-12 00:13 UTC
Labels: enhancement
