### ISSUE TITLE
Can't upscayl pictures no matter what the mode is   (Input file is missing)

### ISSUE THREAD

**Issue by DrDosCat** [upscayl/upscayl#463] opened 2023-09-10 01:27 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\26529\\Desktop\\1.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\26529\Desktop\1.jpg
🗂 Setting output path:  C:\Users\26529\Desktop
🖼 imagePath:  C:\Users\26529\Desktop\1.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\26529\Desktop\1.jpg,-o,C:\Users\26529\Desktop\1_upscayl_4x_realesrgan-x4plus-anime.png,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,,,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  ❌ Error reading original image metadata Error: ENOENT: no such file or directory, open 'C:\Users\26529\Desktop\1_upscayl_4x_realesrgan-x4plus-anime.png'
🚧 UPSCAYL_PROGRESS:  Error: ENOENT: no such file or directory, open 'C:\Users\26529\Desktop\1_upscayl_4x_realesrgan-x4plus-anime.png'
⚙️ Getting saveImageAs from localStorage png
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
```

### Describe the Bug

I can't upscayl the image no matter what mode it's in, and it says it's loading all the time.

btw  the original pic is quite small,only 512×512

### To Reproduce

same as（Describe the Bug）

### Version/Commit Hash

2.7.5and2.5.5 all have this bug

### OS Specifics

OS：Windows 11 家庭中文版 64-bit (10.0, Build 22621) (22621.ni_release.220506-1250)     GPU：NVIDIA GeForce RTX 4060 Laptop GPU

### Screenshots

<img width="966" alt="屏幕截图 2023-09-10 091323" src="https://github.com/upscayl/upscayl/assets/144570798/8ce602e7-92a0-4fdd-90c8-abd35b49ed42">

**Comment by NayamAmarshe** [comment] 2023-09-10 05:01
Did you try the instructions mentioned in the wiki for Windows?

**Comment by DrDosCat** [comment] 2023-09-10 07:31
> Did you try the instructions mentioned in the wiki for Windows?

yeah，and I think I had done all things I can do while the  program is still broken.

ps. another screenshot
<img width="966" alt="屏幕截图 2023-09-10 153131" src="https://github.com/upscayl/upscayl/assets/144570798/ccf3f9c8-152c-4631-b073-ac9d7917e97d">

**Comment by DrDosCat** [comment] 2023-09-10 07:54
This bug is so weird, the day before yesterday it was working fine, today I updated it and it doesn't work, and even if I return the software version from 2.7.5 to 2.5.5 it doesn't help!

**Comment by NayamAmarshe** [comment] 2023-09-10 09:14
> This bug is so weird, the day before yesterday it was working fine, today I updated it and it doesn't work, and even if I return the software version from 2.7.5 to 2.5.5 it doesn't help!

Yeah, vulkan can be weird sometimes. Especially on windows where drivers are updated all the time.

**Comment by DrDosCat** [comment] 2023-09-10 09:26
I really hope cloud comes out soon, I just checked the drivers and registry again.Sadly no luck.

**Comment by aaronliu0130** [comment] 2023-09-10 15:26
Pretty sure this is a duplicate of #450, but you mention that 2.5.5 doesn't work either? If so, could you also post the logs for 2.5.5?

**Comment by DrDosCat** [comment] 2023-09-11 07:31
> Pretty sure this is a duplicate of #450, but you mention that 2.5.5 doesn't work either? If so, could you also post the logs for 2.5.5?

Sure.

> ⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultrasharp
🐞 BACKEND REPORTED:  ✅ Update Downloaded
🐞 BACKEND REPORTED:  🚫 Update Installation Cancelled
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\26529\Desktop\图片1.jpg
🖼 Selected Image Path:  C:\Users\26529\Desktop\图片1.jpg
📁 Selected Image Directory:  C:\Users\26529\Desktop
🖼 imagePath:  C:\Users\26529\Desktop\图片1.jpg
🔤 Extension:  jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\26529\Desktop\图片1.jpg,-o,C:\Users\26529\Desktop\图片1_upscayl_4x_ultrasharp.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-g,1,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\26529\Desktop\图片1_upscayl_4x_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false

**Comment by DrDosCat** [comment] 2023-09-11 07:34
In this case,the bug is similar to https://github.com/upscayl/upscayl/issues/455

**Comment by aaronliu0130** [comment] 2023-09-11 15:19
@DrDosCat Are you sure it doesn’t work in 2.5.5? The logs are pretty normal. If you can confirm there’s no output or preview could you try naming the file in English? Also, the bug you linked is purely visual and still outputs.

**Comment by DrDosCat** [comment] 2023-09-13 01:15
> @DrDosCat Are you sure it doesn’t work in 2.5.5? The logs are pretty normal. If you can confirm there’s no output or preview could you try naming the file in English? Also, the bug you linked is purely visual and still outputs.

It has been changed to English and still doesn't work.Here's the log.

> ⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to ultrasharp
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\26529\\Desktop\\pic1.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\26529\Desktop\pic1.jpg
🗂 Setting output path:  C:\Users\26529\Desktop
🖼 imagePath:  C:\Users\26529\Desktop\pic1.jpg
🔤 Extension:  jpg
🐞 BACKEND REPORTED:  ✅ Update Downloaded
🐞 BACKEND REPORTED:  🚫 Update Installation Cancelled
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\26529\Desktop\pic1.jpg,-o,C:\Users\26529\Desktop\pic1_upscayl_4x_ultrasharp.jpg,-s,4,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-g,1,-f,jpg
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  C:\Users\26529\Desktop\pic1_upscayl_4x_ultrasharp.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Getting gpuId from localStorage 1
⚙️ Getting rememberOutputFolder from localStorage false


> the screenshot
<img width="966" alt="屏幕截图 2023-09-13 091249" src="https://github.com/upscayl/upscayl/assets/144570798/c2e941d5-e46e-4169-90b3-007e0d2c9cc9">

**Comment by aaronliu0130** [comment] 2023-09-13 01:25
and there's no output at C:\Users\26529\Desktop\pic1_upscayl_4x_ultrasharp.jpg?

**Comment by DrDosCat** [comment] 2023-09-13 03:33
> and there's no output at C:\Users\26529\Desktop\pic1_upscayl_4x_ultrasharp.jpg?

yes of course.No output which is quite weird. Though I've given it administrator rights.

**Comment by NayamAmarshe** [comment] 2023-09-14 01:03
Can you try v2.8?

**Comment by DrDosCat** [comment] 2023-09-14 13:09
> Can you try v2.8?

I'm afraid it still can't work.The log says that.

> ⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/jpeg","filePath":"C:\\Users\\26529\\Desktop\\1\\4311fe0d710d8b862f8ab45bc9194d45-1024x576.jpg","extension":"jpg"}
🖼 Setting image path:  C:\Users\26529\Desktop\1\4311fe0d710d8b862f8ab45bc9194d45-1024x576.jpg
🗂 Setting output path:  C:\Users\26529\Desktop\1
🖼 imagePath:  C:\Users\26529\Desktop\1\4311fe0d710d8b862f8ab45bc9194d45-1024x576.jpg
🔤 Extension:  jpg
🔀 Model changed:  RealESRGAN_General_x4_v3
🔀 Setting model to RealESRGAN_General_x4_v3
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to RealESRGAN_General_x4_v3
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to RealESRGAN_General_x4_v3
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  C:\Users\26529\Desktop
🗂 Setting Output Path:  C:\Users\26529\Desktop
🧠 Remembering Output Folder:  C:\Users\26529\Desktop
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\26529\Desktop\1\4311fe0d710d8b862f8ab45bc9194d45-1024x576.jpg,-o,C:\Users\26529\Desktop\4311fe0d710d8b862f8ab45bc9194d45-1024x576_upscayl_4x_RealESRGAN_General_x4_v3.jpg,-s,4,-m,D:\Upscayl\resources\models,-n,RealESRGAN_General_x4_v3,-g,1,-f,png
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
🐞 BACKEND REPORTED:  ❌ Error processing (scaling and converting) the image. Please report this error on GitHub. Error: Input file is missing: C:\Users\26529\Desktop\4311fe0d710d8b862f8ab45bc9194d45-1024x576_upscayl_4x_RealESRGAN_General_x4_v3.jpg
🔄 Resetting image paths
🔄 Resetting image paths
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"RealESRGAN_General_x4_v3"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting quality from localStorage 0

> 
<img width="961" alt="屏幕截图 2023-09-14 210522" src="https://github.com/upscayl/upscayl/assets/144570798/f9d0fe91-5ac1-47c2-85ec-7827e4d32d17">

**Comment by DrDosCat** [comment] 2023-09-14 13:19
it is always saying"Input file is missing".
This is so confusing.😒😒😒

**Comment by NayamAmarshe** [comment] 2023-09-14 16:16
Very weird. Does it work if you put the image in C:\ directly?

**Comment by DrDosCat** [comment] 2023-09-15 08:26
> Very weird. Does it work if you put the image in C:\ directly?

sadly no. it does not work

**Comment by DrDosCat** [comment] 2023-09-15 14:42
GOOD NEWS!!!
The reason for the bug seems to be that some dll files were being occupied, I fixed my c++ libraries and the software worked fine!

**Comment by NayamAmarshe** [comment] 2023-09-15 15:14
> GOOD NEWS!!!
> The reason for the bug seems to be that some dll files were being occupied, I fixed my c++ libraries and the software worked fine!

Oh wow. Could you please post exactly what you did? It might be helpful for someone else having the same problem 🙏

**Comment by DrDosCat** [comment] 2023-09-16 12:42
This error seems to be caused by directX not working properly, so I think any tool that can fix directX will fix it.

one possible example：
http://blog.csdn.net/vbcom/article/details/6962388

**Closed** 2023-09-16 13:54 UTC
Labels: bug
