### ISSUE TITLE
GUI issue: Cannot Select any Upscale Type Other Than Top Choice in Drop Down

### ISSUE THREAD

**Issue by WyvernPyre** [upscayl/upscayl#167] opened 2022-12-25 21:32 UTC
I love Upscayl! However, since being forced to upgrade to 2.0 today, I cannot select any Upscale Type from the drop down, other than the first choice. When trying to select Sharpen Image from Upscale Type it opens the new Advanced Options button directly under it instead. Sharpen Image is the only Upscale Type I use for projects. In its current state, Upscayl is completely useless to me. :(
Help!

**Comment by aaronliu0130** [comment] 2022-12-25 23:18
Duplicate of #165

**Comment by NayamAmarshe** [comment] 2022-12-26 10:22
> I love Upscayl! However, since being forced to upgrade to 2.0 today, I cannot select any Upscale Type from the drop down, other than the first choice. When trying to select Sharpen Image from Upscale Type it opens the new Advanced Options button directly under it instead. Sharpen Image is the only Upscale Type I use for projects. In its current state, Upscayl is completely useless to me. :(
> Help!

Did you scroll down properly?
could you please send a screenshot?

**Comment by petrovicstefanrs** [comment] 2022-12-26 21:54
I can confirm that it does not select the option from the dropdown. The option might be selected but the UI doesn't show it. Also, selecting JPG as output format did nothing, the images were exported as png, as can be seen here https://share.getcloudapp.com/Koun4weZ

**Comment by NayamAmarshe** [comment] 2022-12-27 06:26
Will release v2.0.1, already have implemented the fix.

**Comment by NayamAmarshe** [comment] 2022-12-27 06:27
> Also, selecting JPG as output format did nothing, the images were exported as png, as can be seen here https://share.getcloudapp.com/Koun4weZ

Yeah, I have a fix for that. Turns out, you can't render alpha channel in JPG.

**Closed** 2022-12-27 11:53 UTC

**Comment by petrovicstefanrs** [comment] 2022-12-29 21:23
Thank you for doing that so quickly!
