### ISSUE TITLE
Add an "Alllow Auto-Update" button to let the user be in control of updates

### ISSUE THREAD

**Issue by LxeC** [upscayl/upscayl#352] opened 2023-06-10 23:04 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

There should be an "Alllow Auto-Update" button to let the user be in control of updates. I had an issue where I used the program and it kept popping up the update dialog every time (I think it was because I was closing the program before it was done downloading the update). But sometimes an update might just break something instead of fixing it, and I'd like to be in control of it instead of having to turn off my internet or block the program with the firewall. 

### Description

Add an "Alllow Auto-Update" button to let the user be in control of updates

### Alternatives

Turning off the entire internet.

**Comment by aaronliu0130** [comment] 2023-06-11 02:24
Duplicate of #305 , also already done.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed** 2023-06-11 02:24 UTC
Labels: enhancement
