### ISSUE TITLE
getting GPU error

### ISSUE THREAD

**Issue by Raja31081987** [upscayl/upscayl#830] opened 2024-05-14 19:35 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

I am getting this bug error.

### To Reproduce

please guide me. my upscayl tools is not working. it is showing GPU error.

### Upscayl Version (or commit hash)

2.11.0

### Platform

Windows

### OS Version

windows 10

### GPU Name

intel(R) HD Graphics family

### Expected Behavior

whent I put upscale buuton after uploading image, then it will show GPU error.

### Screenshots

![upscayl error](https://github.com/upscayl/upscayl/assets/169843723/18423541-7dba-4d06-b439-6f7a2940eab3)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🖼 Selected Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
📁 Selected Image Directory:  C:\Users\raja\Downloads\Video\photos
🖼 imagePath:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","fileNameWithExt":"20240422_201326.jpg","outputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","outFile":"C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326_upscayl_4x_ultrasharp.jpg","fileName":"20240422_201326","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg,-o,C:\Users\raja\Downloads\Video\photos\20240422_201326_upscayl_4x_ultrasharp.jpg,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326.jpg","-o","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326_upscayl_4x_ultrasharp.jpg","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultrasharp","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201334.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\raja\Downloads\Video\photos\20240422_201334.jpg
🖼 Selected Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201334.jpg
📁 Selected Image Directory:  C:\Users\raja\Downloads\Video\photos
🖼 imagePath:  C:\Users\raja\Downloads\Video\photos\20240422_201334.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","fileNameWithExt":"20240422_201334.jpg","outputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","outFile":"C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201334_upscayl_4x_ultrasharp.jpg","fileName":"20240422_201334","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\raja\Downloads\Video\photos\20240422_201334.jpg,-o,C:\Users\raja\Downloads\Video\photos\20240422_201334_upscayl_4x_ultrasharp.jpg,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326.jpg","-o","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326_upscayl_4x_ultrasharp.jpg","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultrasharp","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🖼 Selected Image Path:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
📁 Selected Image Directory:  C:\Users\raja\Downloads\Video\photos
🖼 imagePath:  C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"jpg","inputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","fileNameWithExt":"20240422_201326.jpg","outputDir":"C:\\Users\\raja\\Downloads\\Video\\photos","outFile":"C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326_upscayl_4x_ultrasharp.jpg","fileName":"20240422_201326","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\raja\Downloads\Video\photos\20240422_201326.jpg,-o,C:\Users\raja\Downloads\Video\photos\20240422_201326_upscayl_4x_ultrasharp.jpg,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-f,jpg,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326.jpg","-o","C:\\Users\\raja\\Downloads\\Video\\photos\\20240422_201326_upscayl_4x_ultrasharp.jpg","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultrasharp","-f","jpg","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed -3
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
```

**Comment by NayamAmarshe** [comment] 2024-05-15 10:36
Duplicate of #675 
Please follow the troubleshooting guide.

**Closed by NayamAmarshe** 2024-05-15 10:36 UTC
Labels: bug

**Comment by aaronliu0130** [comment] 2024-05-15 10:59
> Yes, unfortunately. NCNN Vulkan requires a Vulkan-compatible GPU. Upscayl won't work with most iGPUs or CPUs.

A workaround exists for Windows and Linux in #580.

> Make sure to read [the FAQ](https://github.com/upscayl/upscayl#-faq) first to avoid getting rickrolled.

> If the name is something like "Intel Core", "Intel Graphics" or "AMD Vega" and you can't Upscayl images, [STOP and read the 3rd point in the FAQ](https://github.com/upscayl/upscayl?tab=readme-ov-file#-faq).

![compulsory rickrolls are issued for duplicates of issues and the FAQ and normies who use intelgrated GPUs](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
