### ISSUE TITLE
Upscale completed, but no image displayed or saved

### ISSUE THREAD

**Issue by ImperatorTheo** [upscayl/upscayl#986] opened 2024-09-24 09:42 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When attempting to upscale a larger image using Upscaly, the process completes without errors, but the upscaled image is neither displayed nor saved. This issue does not occur with smaller images.

### To Reproduce

I don't know. 
The source image is 10074x5804 in size. 
I follow setp 1 to 4.

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Microsoft Windows 11 Pro Version	10.0.22631 Build 22631

### GPU Name

NVIDIA GeForce RTX 4090 Laptop GPU

### Expected Behavior

Get an upscaled image.

### Screenshots

<img width="958" alt="image" src="https://github.com/user-attachments/assets/d31dba37-c0b8-4362-97ee-87b7a796d2d6">

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  D:\AI\PANO0001-Pano.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  D:\AI\PANO0001-Pano.png
🖼 Selected Image Path:  D:\AI\PANO0001-Pano.png
📁 Selected Image Directory:  D:\AI
🖼 imagePath:  D:\AI\PANO0001-Pano.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultrasharp","gpuId":null,"saveImageAs":"png","inputDir":"D:\\AI","fileNameWithExt":"PANO0001-Pano.png","outputDir":"D:\\AI","outFile":"D:\\AI\\PANO0001-Pano_upscayl_4x_ultrasharp.png","fileName":"PANO0001-Pano","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,D:\AI\PANO0001-Pano.png,-o,D:\AI\PANO0001-Pano_upscayl_4x_ultrasharp.png,-m,C:\Program Files\Upscayl\resources\models,-n,ultrasharp,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","D:\\AI\\PANO0001-Pano.png","-o","D:\\AI\\PANO0001-Pano_upscayl_4x_ultrasharp.png","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","ultrasharp","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 4090 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  subgroup=16  basic=1  vote=1  ballot=1  shuffle=1
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 4090 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 4090 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[1 Microsoft Direct3D12 (NVIDIA GeForce RTX 4090 Laptop GPU)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[2 Intel(R) RaptorLake-S Mobile Graphics Controller]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[3 Microsoft Direct3D12 (Intel(R) UHD Graphics)]  subgroup=16  basic=1  vote=1  ballot=1  shuffle=1
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  queueC=1[8]  queueG=0[4]  queueT=0[4]
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  fp16-p/s/a=1/1/1  int8-p/s/a=1/0/0
[4 Microsoft Direct3D12 (Microsoft Basic Render Driver)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0,00%

🚧 UPSCAYL_PROGRESS:  0,00%

🎒 BACKEND REPORTED:  0,07%

🚧 UPSCAYL_PROGRESS:  0,07%

🎒 BACKEND REPORTED:  0,13%

...

🎒 BACKEND REPORTED:  39,93%

🚧 UPSCAYL_PROGRESS:  39,93%

🎒 BACKEND REPORTED:  40,00%

🚧 UPSCAYL_PROGRESS:  40,00%

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultrasharp)","value":"ultrasharp"}
⚙️ Setting gpuId to empty string
🎒 BACKEND REPORTED:  40,07%

🚧 UPSCAYL_PROGRESS:  40,07%

🎒 BACKEND REPORTED:  40,13%

...

🎒 BACKEND REPORTED:  86,54%

🚧 UPSCAYL_PROGRESS:  86,54%

🎒 BACKEND REPORTED:  86,60%

🚧 UPSCAYL_PROGRESS:  86,60%

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  D:\AI\PANO0001-Pano_upscayl_4x_ultrasharp.png
💯 UPSCAYL_DONE:  D:\AI\PANO0001-Pano_upscayl_4x_ultrasharp.png
```

**Comment by aaronliu0130** [comment] 2024-09-25 03:02
Duplicate of #958

**Closed by aaronliu0130** 2024-09-25 03:02 UTC
Labels: bug
