### ISSUE TITLE
Progress text unreadable with certain images

### ISSUE THREAD

**Issue by amadeusjustinn** [upscayl/upscayl#206] opened 2023-01-15 01:19 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

I used Upscayl to upscale this image:

![Raja-Ampat-indonesia-liveaboard-Asiaqua](https://user-images.githubusercontent.com/67861264/212504404-c96f7566-abbb-4436-8ba9-4d24b16340ca.jpeg)

While the result was beyond satisfactory, I noticed that the text that reads the progress of the upscaling was hard to read:

<img width="1412" alt="Screenshot 2023-01-10 at 3 55 47 PM" src="https://user-images.githubusercontent.com/67861264/212504393-32b30cdc-2554-40f1-b216-03bfebcb7153.png">

### Description

Please make the progress text legible under a wider variety of images.

### Alternatives

I assume the legibility of the progress text depends on the colours of the image being upscaled, so I cannot think of any workaround to this issue.

**Comment by NayamAmarshe** [comment] 2023-01-15 01:31
>  I have checked that this issue isn't addressed in any other issue or pull request.

Duplicate of https://github.com/upscayl/upscayl/issues/186 😅

**Comment by amadeusjustinn** [comment] 2023-01-15 02:03
@NayamAmarshe I am so sorry. :/ Is that a coming change for the next update?

**Comment by NayamAmarshe** [comment] 2023-01-15 02:11
> @NayamAmarshe I am so sorry. :/ Is that a coming change for the next update?

Yeah, I'll try to fix it :)

**Comment by amadeusjustinn** [comment] 2023-01-15 02:13
Got it. Thanks again for all your hard work!

**Comment by NayamAmarshe** [comment] 2023-01-15 03:58
> Got it. Thanks again for all your hard work!

Let's keep this issue opened for now :)

**Comment by oxou** [comment] 2023-01-15 04:14
Perhaps a good fix would be to add [`text-shadow`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow) that's white and the color of font black to the progress text element so that it's visible in both cases where the background is bright or dark.

**Comment by NayamAmarshe** [comment] 2023-03-04 02:08
Tracking: https://github.com/orgs/upscayl/projects/1/

**Closed** 2023-03-12 09:41 UTC
Labels: enhancement, v2.5
