### ISSUE TITLE
Allow batch in subfolder

### ISSUE THREAD

**Issue by imagicalFantasy** [upscayl/upscayl#434] opened 2023-08-30 03:35 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

When you run batch process, it will only convert file in the defined folder but there is no way to also includes all subfolders.
Could be very handy to have the option for that.

### Alternatives

Process each folder on by one or make flat folder.

**Comment by aaronliu0130** [comment] 2023-08-30 13:23
Duplicate of #283 .

**Closed by aaronliu0130** 2023-08-30 13:23 UTC
Labels: enhancement
