### ISSUE TITLE
On windows 7 x64 upscayl 2.5.1 not start

### ISSUE THREAD

**Issue by abellos** [upscayl/upscayl#308] opened 2023-05-10 09:55 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

When i start the program, i receive error and upscayl not start, version 2.0.1 work fine, maybe can put an option to avoid the update

### To Reproduce

Just open the program and get the attached error, think is a problem related to windows 7 64 bit, tested on windows 10 and work fine

### Expected Behavior

Program should start and open his interface

### Version/Commit Hash

2.5.1

### OS Specifics

Sapphire radeon tri-x R9 290 4GB - windows 7 x64

### Screenshots

![Upscayl_error](https://github.com/upscayl/upscayl/assets/111513140/001b4c53-c7fc-48dc-88a9-c3da15e236d5)

**Comment by NayamAmarshe** [comment] 2023-05-10 10:04
Duplicate of https://github.com/upscayl/upscayl/issues/305

Upscayl doesn't support Windows 7 officially but you can try the fix mentioned in #305.

**Closed** 2023-05-10 10:04 UTC
Labels: bug

**Comment by halinoureddine2017-netizen** [comment] 2026-01-15 07:51
شكرا لكم

**Comment by halinoureddine2017-netizen** [comment] 2026-01-15 07:51
thank you
