### ISSUE TITLE
context menu option

### ISSUE THREAD

**Issue by JasimAlrawie** [upscayl/upscayl#1058] opened 2024-12-06 01:29 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

can you please add an option to the context menu of image files
upscayl when click it gonna open the app with the image and do the things we do in the program
or an option for quick upscale
orrr
a menu with sub options from the app and it does it in the background or open the app to do it :)

### Related Problem(s)

none

### Alternatives

context menu :D

**Comment by NayamAmarshe** [comment] 2024-12-23 08:25
Ok,  I can try

**Comment by aaronliu0130** [comment] 2024-12-27 16:44
Duplicate of #268

**Closed by aaronliu0130** 2024-12-27 16:44 UTC
Labels: enhancement

**Comment by JasimAlrawie** [comment] 2024-12-28 12:54
its not duplicate 
the man compiling about a bug and im suggesting a feature :)

**Comment by aaronliu0130** [comment] 2025-01-01 02:30
that one's also a feature request tho
