### ISSUE TITLE
Uppercase file extensions are ignored during post-processing in batch mode

### ISSUE THREAD

**Issue by alexhunsley** [upscayl/upscayl#687] opened 2024-01-30 18:38 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

In batch mode, images with uppercase filenames are ignored. So if you batch mode a dir full of uppercase files, nothing happens and upscayl immediately says it has completed processing.

Note that single file mode handles uppercase filenames OK.

### To Reproduce

1. Create a dir. Place some supported format image files in it with uppercase filenames, e.g.:

IMAGE1.JPG
IMAGE2.JPEG
IMAGE3.WEBP
IMAGE4.PNG

2. Launch upscayl, put it in batch mode, select the dir you made in step 1.

3. Hit the "upscayl" button

Result: Upscayl immediately says processing has finished and no images were processed.

### Upscayl Version (or commit hash)

2.9.8

### Platform

MacOS DMG / Homebrew

### OS Version

14.2.1

### GPU Name

MacBook Pro (2021) M1 Pro

### Expected Behavior

The folder of files (batch processing mode) should have all been processed.

### Screenshots

N/A

### Logs

```sh
Sorry, I missed the logs, but I think the bug probably doesn't need logs to fix!
```

**Comment by aaronliu0130** [comment] 2024-01-30 23:00
Works for me. Please send logs.

**Comment by aaronliu0130** [comment] 2024-01-30 23:01
The upscayling works for me. Please send logs.

The post-processing does indeed seem to fail

**Comment by NayamAmarshe** [comment] 2024-01-31 11:08
That's pretty weird

**Comment by NayamAmarshe** [comment] 2024-02-07 01:36
Unable to reproduce. Upscayl is working as expected.

![Image](https://github.com/upscayl/upscayl/assets/25067102/db8e9726-9949-4431-9a54-4a3a22faffd6)

**Comment by aaronliu0130** [comment] 2024-02-07 01:45
It seems to only fail in batch mode

**Comment by NayamAmarshe** [comment] 2024-02-07 01:52
Ah! Possibly an issue with ncnn backend.
@TGS963

**Comment by NayamAmarshe** [comment] 2024-02-07 01:53
Maybe updating the ncnn binary will fix the issue.

**Comment by TGS963** [comment] 2024-02-07 01:54
> Maybe updating the ncnn binary will fix the issue.

Possibly, might've ignored uppercase extensions when ignoring hidden files and folders

**Comment by NayamAmarshe** [comment] 2024-02-08 15:22
Fixed in latest NCNN release. Will be there in v2.9.9

**Closed by NayamAmarshe** 2024-02-08 15:22 UTC
Labels: bug
