### ISSUE TITLE
Limit Amount of Batch Processing

### ISSUE THREAD

**Issue by finezzo** [upscayl/upscayl#1043] opened 2024-11-18 07:10 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

I am trying to run a batch with around 20.000 images, however the processing always stops at about 1600-1700 images. After that is shows that everything is done.

### To Reproduce

Run a batch of more than 10k pictures. I used the FAST Real ESRGAN Model

### Upscayl Version (or commit hash)

2.11.5

### Platform

Linux

### OS Version

Mac OS 15.0.1

### GPU Name

Apple M1

### Expected Behavior

Process all Images in the supplied folder

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4fast
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  /Volumes/NG2TB/Example/Frames
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  /Volumes/NG2TB/Example/Frames
🖼 Selected Folder Path:  /Volumes/NG2TB/Example/Frames
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  /Volumes/NG2TB/Example/Scaled
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  /Volumes/NG2TB/Example/Scaled
🗂 Setting Output Path:  /Volumes/NG2TB/Example/Scaled
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Volumes/NG2TB/Example/Frames,-o,/Volumes/NG2TB/Example/Scaled/upscayl_png_realesrgan-x4fast_2x,-s,2,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,realesrgan-x4fast,-f,png,-c,0
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024

🚧 FOLDER_UPSCAYL_PROGRESS:  ✨ Detected scale x4
✨ Using the default scale x4

🚧 FOLDER_UPSCAYL_PROGRESS:  [0 Apple M1]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M1]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Apple M1]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M1]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  3.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  18.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  21.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  23.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  28.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  30.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  31.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  35.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  36.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  38.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  43.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  45.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  48.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  51.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  56.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  61.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  63.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  65.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  68.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  70.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  71.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  76.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  78.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  81.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  85.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  90.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  95.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  96.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  98.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🚧 FOLDER_UPSCAYL_PROGRESS:  🏞️ Scaled image from 1920x1080 to 3840x2160

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🚧 FOLDER_UPSCAYL_PROGRESS:  3.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  5.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  6.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  8.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  10.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  11.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  13.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  15.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  16.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  18.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  20.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  21.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  23.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  25.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  26.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  28.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  30.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  31.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  33.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  35.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  36.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  38.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  40.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  41.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  43.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  45.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  46.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  48.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  50.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  51.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  53.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  55.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  56.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  58.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  60.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  61.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  63.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  65.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  66.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  68.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  70.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  71.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  73.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  75.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  76.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  78.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  80.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  81.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  83.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  85.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  86.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  88.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  90.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  91.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  93.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  95.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  96.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  98.33%

🚧 FOLDER_UPSCAYL_PROGRESS:  🏞️ Resizing image according to output scale

🚧 FOLDER_UPSCAYL_PROGRESS:  🏞️ Scaled image from 1920x1080 to 3840x2160

🚧 FOLDER_UPSCAYL_PROGRESS:  0.00%

🚧 FOLDER_UPSCAYL_PROGRESS:  1.67%

🚧 FOLDER_UPSCAYL_PROGRESS:  100.00

🎒 BACKEND REPORTED:  💯 Done upscaling
💯 FOLDER_UPSCAYL_DONE:  /Volumes/NG2TB/Example/Scaled/upscayl_png_realesrgan-x4fast_2x
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Fast Real-ESRGAN)","value":"realesrgan-x4fast"}
⚙️ Setting gpuId to empty string
```

**Comment by finezzo** [comment] 2024-11-18 09:54
Sadly the behavior from the Command line is the same

**Comment by aaronliu0130** [comment] 2024-12-02 01:09
pretty much a duplicate of #832

**Closed by aaronliu0130** 2024-12-02 01:09 UTC
Labels: bug

**Comment by nienphan1** [comment] 2024-12-21 18:27
Is this problem fixed yet? I'm facing the above situation

**Comment by finezzo** [comment] 2024-12-21 19:15
> Is this problem fixed yet? I'm facing the above situation

No its not Fixed. According to the answers of the Developers its not possible "by design" unless you have a lot of memory.

**Comment by aaronliu0130** [comment] 2024-12-27 16:41
It's not "by design". We need manpower to investigate the memory leak.

**Comment by finezzo** [comment] 2024-12-27 17:18
> It's not "by design". We need manpower to investigate the memory leak.

By saying its by Design i didnt mean its integrated on purpose. Just that its not designed for a lot of Images Like 50-100k, which then results in a Memory leak which could be considered an Expected behaviour. Of course we are all happy for having the product :)
