### ISSUE TITLE
At 3x or 2x, the picture will tear.

### ISSUE THREAD

**Issue by LuZixuan2022** [upscayl/upscayl#411] opened 2023-08-10 09:32 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

At 3x or 2x, the picture will tear.
Like this:
I use 3x.
 Original:
![61efb6393fdb0](https://github.com/upscayl/upscayl/assets/114159378/a18e5b27-3d24-4941-a66c-c496e18c2046)

 After processing:
![61efb6393fdb0_upscayl_3x_ultrasharp](https://github.com/upscayl/upscayl/assets/114159378/6e1c2109-31b5-4ed7-a6ca-2e9dcdd7ff24)

### Describe the Bug

At 3x or 2x, the picture will tear.

### To Reproduce

just use 2x/3x upscayl a photo.

### Version/Commit Hash

2.55

### OS Specifics

it's very old

**Comment by aaronliu0130** [comment] 2023-08-10 22:21
Duplicate of #303. Also keep in mind next time that "it's very old" is not enough for OS specifics lol

**Closed by aaronliu0130** 2023-08-10 22:21 UTC
Labels: bug
