### ISSUE TITLE
Please add compression settings, file sizes are wayy too big

### ISSUE THREAD

**Issue by Ramam001** [upscayl/upscayl#432] opened 2023-08-29 06:01 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

ive usied stale diffusion for upscales with same models but the image sizes were wayyyy too better in it compared to it, 
it would be better to add compression settings or at least a toggle to make image size shorter in png format without loosing quality if possible

**Comment by Ramam001** [comment] 2023-08-29 06:33
ye salso add 1x with
[https://drive.google.com/file/d/1zAJfsgX-aLdt7y1UilActp3SF5NsfXr5/view?usp=drive_link

**Comment by aaronliu0130** [comment] 2023-08-29 19:42
We cannot add models without knowing their licensing info.

Compression does sound good, maybe we could use something like pingo which is the most promising according to https://css-ig.net/benchmark/png-lossless

**Comment by aaronliu0130** [comment] 2023-09-01 18:28
Done and apparently this was a duplicate of #370

**Closed by aaronliu0130** 2023-09-01 18:28 UTC
Labels: enhancement
