### ISSUE TITLE
Customizable Output Image Size

### ISSUE THREAD

**Issue by fendrix69** [upscayl/upscayl#223] opened 2023-02-10 07:02 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Related Problem(s)

I love the app but I really think it needs to let users choose an output size. 

I don't need to resize 720p to 5K, I would much rather upscale to 2k and have far less artifacts, which are more noticeable when upscaling 3d. I can definitely see banding being introduced in some areas when upscaling at such high resolution upscaling using all available algos.

### Description

Please allow full customisation of output image size.

### Alternatives

No

**Comment by NayamAmarshe** [comment] 2023-02-10 13:35
>  I have checked that this issue isn't addressed in any other issue or pull request

Duplicate of https://github.com/upscayl/upscayl/issues/203

**Closed by NayamAmarshe** 2023-02-10 13:35 UTC
Labels: enhancement

**Comment by aaronliu0130** [comment] 2023-02-10 22:03
(and #8)
