### ISSUE TITLE
Upscaling is broken: Invalid arguments: the model name doesn't contain scale 

### ISSUE THREAD

**Issue by UnknownUser95** [upscayl/upscayl#797] opened 2024-04-26 17:58 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

Upscaling immediately crashes, wrong arguments for upscaler.

The logs mention: `🚨 Error: The model name doesn't contain scale. Please make sure that the model name contains x2, x3, x4, etc. or 2x, x3, x4, etc.`

### To Reproduce

Try to upscale an image.

### Upscayl Version (or commit hash)

2.10.9 (AUR: upscayl-bin)

### Platform

Linux

### OS Version

Arch Linux 6.8.7-zen

### GPU Name

AMD XFX 6900XT

### Expected Behavior

The image is upscaled.

### Logs

```sh
📂 DIRNAME /opt/upscayl/app.asar/export/electron
APPIMAGE env is not defined, current application is not an AppImage
19:45:42.409 › 🚀 UPSCAYL EXEC PATH:  /opt/upscayl/bin/upscayl-bin
19:45:42.411 › 🚀 MODELS PATH:  /opt/upscayl/models
19:45:42.971 › 🎯 GET_MODELS_LIST:  
19:45:42.993 › 📁 Updating Output Folder Path:  "/home/$USER/Documents/Bac/#Unsynched"
19:45:42.994 › 💾 Updating Remember Output Folder:  true
19:45:42.994 › 📐 Updating Compression:  null
19:45:42.995 › 🖼 Updating No Image Processing:  false
19:45:42.996 › ⚙ Getting saveImageAs from localStorage:  png
19:45:42.996 › ⚙ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
19:45:42.996 › ⚙ Setting gpuId to empty string
19:45:42.996 › 🔀 Setting model to null
19:45:42.998 › 🔀 Setting model to ultramix_balanced
19:45:43.000 › 𝌖 BACKEND REPORTED:  📁 Updating Output Folder Path:  "/home/$USER/Documents/Bac/#Unsynched"
19:45:43.029 › 𝌖 BACKEND REPORTED:  💾 Updating Remember Output Folder:  true
19:45:43.029 › 𝌖 BACKEND REPORTED:  📐 Updating Compression:  NaN
19:45:43.029 › 𝌖 BACKEND REPORTED:  🖼 Updating No Image Processing:  false
19:45:43.818 › 🔄 Resetting image paths
[19867:0426/194545.807908:ERROR:browser_main_loop.cc(280)] GLib-GObject: ../glib/gobject/gsignal.c:2685: instance '0x35280215d2b0' has no handler with id '8332'
19:45:45.808 › 🖼 Updating Image Path:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:45.808 › 📄 Selected File Path:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:45.809 › 𝌖 BACKEND REPORTED:  🖼 Updating Image Path:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:45.811 › 🖼 Selected Image Path:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:45.811 › 📁 Selected Image Directory:  /home/$USER/Documents/Bac/#Unsynched
19:45:45.811 › 🖼 imagePath:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:45.812 › 🔤 Extension:  jpg
19:45:45.812 › 𝌖 BACKEND REPORTED:  📄 Selected File Path:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg
19:45:47.150 › 🔄 Resetting Upscaled Image Path
19:45:47.151 › 🖼 Updating No Image Processing:  false
19:45:47.152 › 📐 Updating Compression:  0
19:45:47.152 › Is Default Model? :  true
19:45:47.152 › ✅ Upscayl Variables:  {"model":"ultramix_balanced","gpuId":null,"saveImageAs":"png","inputDir":"/home/$USER/Documents/Bac/#Unsynched","outputDir":"/home/$USER/Documents/Bac/#Unsynched","fullfileName":"DPJP-photography.jpg","fileName":"DPJP-photography","scale":"4","outFile":"/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png","compression":0}
19:45:47.153 › 📢 Upscayl Command:  [
  '-i',
  '/home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg',
  '-o',
  '/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png',
  '-s 4',
  '-m',
  '/opt/upscayl/models',
  '-n',
  'ultramix_balanced',
  '-f',
  'png'
]
19:45:47.162 › 👶 Updating Child Processes:  {"binary":"/opt/upscayl/bin/upscayl-bin","args":["/opt/upscayl/bin/upscayl-bin","-i","/home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg","-o","/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png","-s 4","-m","/opt/upscayl/models","-n","ultramix_balanced","-f","png"]}
19:45:47.162 › 🛑 Updating Stopped:  false
19:45:47.163 › 🏁 UPSCAYL
19:45:47.164 › image upscayl:  🚀 Starting Upscayl - Copyright © 2024
🚨 Error: The model name doesn't contain scale. Please make sure that the model name contains x2, x3, x4, etc. or 2x, x3, x4, etc.

19:45:47.165 › 💯 Done upscaling
19:45:47.165 › ♻ Scaling and converting now...
19:45:47.184 › 𝌖 BACKEND REPORTED:  🖼 Updating No Image Processing:  false
19:45:47.184 › 𝌖 BACKEND REPORTED:  📐 Updating Compression:  0
19:45:47.185 › 𝌖 BACKEND REPORTED:  Is Default Model? :  true
19:45:47.185 › 𝌖 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultramix_balanced","gpuId":null,"saveImageAs":"png","inputDir":"/home/$USER/Documents/Bac/#Unsynched","outputDir":"/home/$USER/Documents/Bac/#Unsynched","fullfileName":"DPJP-photography.jpg","fileName":"DPJP-photography","scale":"4","outFile":"/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png","compression":0}
19:45:47.185 › 𝌖 BACKEND REPORTED:  📢 Upscayl Command:  -i,/home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg,-o,/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png,-s 4,-m,/opt/upscayl/models,-n,ultramix_balanced,-f,png
19:45:47.185 › 𝌖 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"/opt/upscayl/bin/upscayl-bin","args":["/opt/upscayl/bin/upscayl-bin","-i","/home/$USER/Documents/Bac/#Unsynched/DPJP-photography.jpg","-o","/home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png","-s 4","-m","/opt/upscayl/models","-n","ultramix_balanced","-f","png"]}
19:45:47.185 › 𝌖 BACKEND REPORTED:  🛑 Updating Stopped:  false
19:45:47.186 › 𝌖 BACKEND REPORTED:  image upscayl:  🚀 Starting Upscayl - Copyright © 2024
🚨 Error: The model name doesn't contain scale. Please make sure that the model name contains x2, x3, x4, etc. or 2x, x3, x4, etc.

19:45:47.186 › 🚧 UPSCAYL_PROGRESS:  🚀 Starting Upscayl - Copyright © 2024
🚨 Error: The model name doesn't contain scale. Please make sure that the model name contains x2, x3, x4, etc. or 2x, x3, x4, etc.

19:45:47.186 › 𝌖 BACKEND REPORTED:  💯 Done upscaling
19:45:47.186 › 𝌖 BACKEND REPORTED:  ♻ Scaling and converting now...
19:45:47.186 › upscaledImagePath:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png
19:45:47.187 › 💯 UPSCAYL_DONE:  /home/$USER/Documents/Bac/#Unsynched/DPJP-photography_upscayl_4x_ultramix_balanced.png
```

**Comment by UnknownUser95** [comment] 2024-04-26 18:03
Note: There is no output image, even though the logs mention it.

**Comment by UnknownUser95** [comment] 2024-04-26 18:07
I just found out:

Upscayl works if I use
- REAL-ESRGAN
- Fast REAL-ESRGAN
- Digital Art

It doesn't work on
- Remacri
- Ultramix Balanced
- Ultrasharp

The three latter ones all have the same error as I posted (model name doesn't contain scale).

**Comment by aaronliu0130** [comment] 2024-04-26 19:12
Duplicate of #792, but that guy hung instead. Weird. TL;DR: download Upscayl again.

**Closed by aaronliu0130** 2024-04-26 19:12 UTC
Labels: bug, duplicate

**Comment by UnknownUser95** [comment] 2024-04-26 19:16
As I was writing this, you posted you answer.

As you said 2.11 (e.g. the Flatpak version) fixes this.

Also in the time between me posting this and now answering the AUR package got flagged as Out-Of-Date, so that's already done.

**Comment by UnknownUser95** [comment] 2024-04-26 19:17
Anyway, still thank you for the answer.
