### ISSUE TITLE
Request to add more languages, such as Chinese

### ISSUE THREAD

**Issue by cbbos** [upscayl/upscayl#758] opened 2024-03-25 14:31 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Look forward to the language switching option appearing in subsequent updates.

**Comment by aaronliu0130** [comment] 2024-03-25 15:17
Duplicate of #91
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-03-25 15:17 UTC
Labels: enhancement
