### ISSUE TITLE
Upscayl wish list for enhancements

### ISSUE THREAD

**Issue by Spirograph12** [upscayl/upscayl#265] opened 2023-04-05 15:12 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Thanks for Upscayl! If fills a definite need for something that's super easy to install and use, with a simple, intuitive UI.

Upscayl (currently at v 2.0.1) is **very useful** because the Linux appimage requires virtually no advanced knowledge on the part of the end user. It "just works."

In my experience, it will sometimes work even without a dedicated GPU. It works on my Dell Inspiron 3670, where the CPU is Intel Core i5-8400 CPU @2.80 GHz, and there's no dedicated graphics card. YMMV. (Of course, it will work much faster if you have a fast nVidia card with lots of vRam.)

While Upscayl is already a **great achievement**, here's my wish list for enhancements. (May include more detailed discussion of suggestions from other users.)

- Ability to choose the scale factor. AFAIK, currently everything is 4x. Sometimes you only want 2x. Sometimes only 1x if all you need is the built-in noise reduction/image enhancement which some models provide.

- A few more built-in models:

Universal Upscaler v2
NMKD Siax
4x Country Roads
lollypop
realesrgan-x4minus
SwinIR-L (003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN)

- Ability to load user-supplied models, such as special purpose models downloaded from: 

[https://upscale.wiki/wiki/Model_Database](https://upscale.wiki/wiki/Model_Database)

- Support for Codeformer, which is not an ESRGAN model, but is an _extremely useful_ combination photo restorer and upscaler which often achieves superior results. It is currently supported by chaiNNer and Automatic1111 (neither of which are particularly easy to install or use).

- Support for Lanczos, which is a popular non-AI method of upscaling which largely preserves the original image and does not "hallucinate" any new detail.

- Ability to use 2 upscalers and set the ratio between them.

An important use case for 2 upscalers, specifically Codeformer and Lanczos, is this:

Codeformer does a fantastic job of restoring and upscaling old photos. But even with the fidelity/identity slider set as high as 0.9, it may still make faces too "perfect," losing expression and character. OTOH, a Lanczos upscale will basically preserve the original image. By mixing in some Lanczos with Codeformer, you may be able to get the ideal balance between upscaling, restoration, and preservation of expressive detail.

The broad case for including more models is this: Especially when upscaling images of natural media or human faces, it's sometimes hard to find an upscaling model which preserves the natural look, doesn't introduce artifacts, doesn't oversmooth skin, and doesn't destroy desired grain and texture.

Some people claim that Universal Upscaler v2 is good for landscapes, while lollypop is good for (realistic) people. Different content will benefit from having a wide choice of different upscalers which were trained on different data sets and therefore give a different look. (Getting a natural look for natural subjects often requires the most experimentation.)

Some of these suggestions might be considered advanced. If so, they could be hidden under the Advanced menu. That way, Upscayl would still be easy to use for newbies, while having advanced features under the hood.

Thanks again for Upscayl, and thank you for your time!

### Alternatives

Lacking the ability to mix 2 different models proportionally in Upscayl, it could be done using an image editor like GIMP or Photoshop which supports layers. Starting from the original image, one version could be upscaled in Upscayl, while another version could be upscaled to the same dimensions using Lanczos in an image editor. The two different results could be placed on different layers, and layer opacity sliders used to experiment with different ratios. Using layer masking, it would also be possible to "paint in" certain details from one layer, to cover areas which are less good on the other layer. However, mixing models proportionally in Upscayl might yield good results quickly, with far less effort.

**Comment by aaronliu0130** [comment] 2023-04-05 22:03
Scale factor: Duplicate of #144, already implemented in HEAD (main branch of the source code that doesn't have binaries released yet, you could do the development run to try it out)
User supply models: Duplicate of #200
Codeformer: Duplicate of #246 and #146
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)
---
For the other suggestions, they all look pretty good! However, I don't really get what using 2 upscalers is. AFAIK models can't be mixed. I'm not the expert at image models though, so let's see what @NayamAmarshe says about this.

**Comment by NayamAmarshe** [comment] 2023-04-11 01:43
- I tried running Codeformer NCNN but unfortunately couldn't, so that's a lost cause for now.
- Ability to add custom models is already being implemented.
- Lancsoz would require some canvas work, which is currently out of scope for this project. Upscayl passes the raw image data to Real-ESRGAN, so I'm not sure if Lancsoz is even useful.
- The ability to use 2 upscalers is not needed imo. You can easily put the images on each other in [PhotoPea](https://photopea.com) and adjust the opacity of the top image.

**Comment by NayamAmarshe** [comment] 2023-04-11 01:43
Closing this for now. Happy to discuss further if you'd like or would like to suggest something different.

**Closed by NayamAmarshe** 2023-04-11 01:43 UTC
Labels: enhancement
