### ISSUE TITLE
Adding several folders at once in upscayl

### ISSUE THREAD

**Issue by haidautuiosif** [upscayl/upscayl#503] opened 2023-10-03 20:01 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
WITHOUT URNS
```

### Describe the Bug

GOOD DAY, I WOULD ALSO LIKE YOU TO ADD AN OPTION TO ALLOW THE APPLICATION TO TAKE MULTIPLE IMAGE FOLDERS IN ROW FOR UPSCALING. That is, instead of select folder, to have the option of "Select many
 folders". 
As in the picture

### To Reproduce

REPLACE "SELECT FOLDER" WITH "SELECT MANY FOLDERS" OR SOMETHING SIMILAR

### Version/Commit Hash

2.5.5

### OS Specifics

windows 11 , video card rtx 3050 ti

### Screenshots

![1](https://github.com/upscayl/upscayl/assets/140640441/2488de0f-f2c3-4c86-b2d2-c9e3c8945fcc)

**Comment by haidautuiosif** [comment] 2023-10-03 20:03
I WILL SELECT SEVERAL FOLDERS SIMULTANEOUSLY AND UPSCALE THEM IN ROW

**Comment by aaronliu0130** [comment] 2023-10-03 21:05
I believe this is a feature request, not a bug, and a duplicate of #402 which you also filed. We cannot do this currently due to electron limitations, sorry. In the meantime, you can wait while we implement #283.

**Closed by aaronliu0130** 2023-10-03 21:05 UTC
Labels: bug

**Comment by haidautuiosif** [comment] 2023-10-03 22:59
hello, I am willing to pay for this modification if it helps you with anything

**Comment by aaronliu0130** [comment] 2023-10-03 23:00
Sorry, it can't. It's an issue with the underlying framework

**Comment by haidautuiosif** [comment] 2023-10-03 23:02
is there any possibility to fix this problem??

**Comment by haidautuiosif** [comment] 2023-10-03 23:03
future ?

**Comment by aaronliu0130** [comment] 2023-10-03 23:05
At best we may be able to manage a flow like this: select a folder→ press the "+" and select another folder→..., we won't be able to have a selector that can select multiple folders at once until electron fixes their s***.

**Comment by haidautuiosif** [comment] 2023-10-03 23:06
ok

**Comment by aaronliu0130** [comment] 2023-10-03 23:07
@NayamAmarshe Would you like to implement the plus flow I described above?

**Comment by haidautuiosif** [comment] 2023-10-03 23:24
yes

**Comment by haidautuiosif** [comment] 2023-10-03 23:25
this method is so that I don't have to go back to the computer every time the images in a folder are upscaled, so that I can then go to another folder

**Comment by haidautuiosif** [comment] 2023-10-03 23:26
> u vom putea avea un selector care poate selecta mai multe foldere deodată până când electron le repară s***.

or by drag and drop if possible

**Comment by NayamAmarshe** [comment] 2023-10-04 05:51
I'll consider this feature.

**Comment by haidautuiosif** [comment] 2023-10-04 10:16
OK thank you very much

**Comment by haidautuiosif** [comment] 2023-10-06 12:16
do you have any idea when the upscayl cloud application will be available?
