### ISSUE TITLE
The Real-ESRGAN model cannot be converted successfully

### ISSUE THREAD

**Issue by Kongsea** [upscayl/upscayl#969] opened 2024-09-12 06:15 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

The Real-ESRGAN model cannot be converted successfully.
Even [the official .pth weights](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) cannot be converted too.

> An error occurred in a pytorch Convert To NCNN node:
> 
> Shape not currently supported by NCNN.
> 
> Input values:
> • PyTorch Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
> • Data Type: fp16

### To Reproduce

Just install chaiNNer 0.24.1 to convert [the model](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) and the error was reported.

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10

### GPU Name

NVIDIA 4090D

### Screenshots

![image](https://github.com/user-attachments/assets/5aff1d06-c73a-4d52-899d-61a004214fe7)

### Logs

```sh
Error

An error occurred in a pytorch Convert To NCNN node:

Shape not currently supported by NCNN.

Input values:
• PyTorch Model: Value of type 'spandrel.__helpers.model_descriptor.ImageModelDescriptor'
• Data Type: fp16

Stack Trace:
Traceback (most recent call last):
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\process.py", line 174, in run_node
    raw_output = node.run(context, *enforced_inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\packages\chaiNNer_pytorch\pytorch\utility\convert_to_ncnn.py", line 77, in convert_to_ncnn_node
    ncnn_model, fp_mode = onnx_convert_to_ncnn_node(onnx_model, is_fp16)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\packages\chaiNNer_onnx\onnx\utility\convert_to_ncnn.py", line 45, in convert_to_ncnn_node
    ncnn_model = NcnnModelWrapper(converter.convert(fp16, False))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\A\AppData\Local\chaiNNer\app-0.24.1\resources\src\nodes\impl\onnx\onnx_to_ncnn.py", line 2852, in convert
    raise ValueError(error_msg)
ValueError: Shape not currently supported by NCNN.
```

**Comment by Kongsea** [comment] 2024-09-12 06:49
**Update:**
[Real-ESRGAN x2plus model](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x2plus.pth) cannot be converted successfully.
But [Real-ESRGAN x4plus](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.1/RealESRGAN_x4plus.pth) can be converted successfully.

However, the converted Real-ESRGAN x4plue model cannot be used by Upscayl to generate expected outputs and the results is like mentioned in [issue](https://github.com/upscayl/upscayl/issues/960).

**Comment by NayamAmarshe** [comment] 2024-09-12 12:37
This is a Chainner issue. Please report this on their repository :)

**Comment by Kongsea** [comment] 2024-09-13 00:50
> This is a Chainner issue. Please report this on their repository :)

The converted Real-ESRGANx4plus model used in Upscayl fails to generate the expected outputs as well...

**Comment by aaronliu0130** [comment] 2024-09-17 03:04
Duplicate of #960

**Closed by aaronliu0130** 2024-09-17 03:04 UTC
Labels: bug, dependencies
