### ISSUE TITLE
2x and 3x scaling issues 

### ISSUE THREAD

**Issue by PatrykKeska** [upscayl/upscayl#322] opened 2023-05-14 15:42 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Hi, 

Hi, I know that the 2x and 3x zoom options are marked as experimental, but I checked on macOS and the images do not combine properly. I'm attaching a sample photo as an example.
 2x result  [https://pasteboard.co/2KalL1CYPpeV.png](url)

<details>
<summary>Logs</summary>
<pre>

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🎯 GET_MODELS_LIST:  
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  /Users/patrykkeska/Desktop/hrglago_0.webp
🖼 Selected Image Path:  /Users/patrykkeska/Desktop/hrglago_0.webp
📁 Selected Image Directory:  /Users/patrykkeska/Desktop
🖼 imagePath:  /Users/patrykkeska/Desktop/hrglago_0.webp
🔤 Extension:  webp
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/Users/patrykkeska/Desktop/hrglago_0.webp,-o,/Users/patrykkeska/Desktop/hrglago_0_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,/Applications/Upscayl.app/Contents/Resources/models,-n,realesrgan-x4plus,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [0 Apple M1 Max]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M1 Max]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Apple M1 Max]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M1 Max]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 Apple M1 Max]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Apple M1 Max]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Apple M1 Max]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Apple M1 Max]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🐞 BACKEND REPORTED:  image upscayl:  1.67%

🚧 UPSCAYL_PROGRESS:  1.67%

🐞 BACKEND REPORTED:  image upscayl:  3.33%

🚧 UPSCAYL_PROGRESS:  3.33%

🐞 BACKEND REPORTED:  image upscayl:  5.00%

🚧 UPSCAYL_PROGRESS:  5.00%

🐞 BACKEND REPORTED:  image upscayl:  6.67%

🚧 UPSCAYL_PROGRESS:  6.67%

🐞 BACKEND REPORTED:  image upscayl:  8.33%

🚧 UPSCAYL_PROGRESS:  8.33%

🐞 BACKEND REPORTED:  image upscayl:  10.00%

🚧 UPSCAYL_PROGRESS:  10.00%

🐞 BACKEND REPORTED:  image upscayl:  11.67%

🚧 UPSCAYL_PROGRESS:  11.67%

🐞 BACKEND REPORTED:  image upscayl:  13.33%

🚧 UPSCAYL_PROGRESS:  13.33%

🐞 BACKEND REPORTED:  image upscayl:  15.00%

🚧 UPSCAYL_PROGRESS:  15.00%

🐞 BACKEND REPORTED:  image upscayl:  16.67%

🚧 UPSCAYL_PROGRESS:  16.67%

🐞 BACKEND REPORTED:  image upscayl:  18.33%

🚧 UPSCAYL_PROGRESS:  18.33%

🐞 BACKEND REPORTED:  image upscayl:  20.00%

🚧 UPSCAYL_PROGRESS:  20.00%

🐞 BACKEND REPORTED:  image upscayl:  21.67%

🚧 UPSCAYL_PROGRESS:  21.67%

🐞 BACKEND REPORTED:  image upscayl:  23.33%

🚧 UPSCAYL_PROGRESS:  23.33%

🐞 BACKEND REPORTED:  image upscayl:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🐞 BACKEND REPORTED:  image upscayl:  26.67%

🚧 UPSCAYL_PROGRESS:  26.67%

🐞 BACKEND REPORTED:  image upscayl:  28.33%

🚧 UPSCAYL_PROGRESS:  28.33%

🐞 BACKEND REPORTED:  image upscayl:  30.00%

🚧 UPSCAYL_PROGRESS:  30.00%

🐞 BACKEND REPORTED:  image upscayl:  31.67%

🚧 UPSCAYL_PROGRESS:  31.67%

🐞 BACKEND REPORTED:  image upscayl:  33.33%

🚧 UPSCAYL_PROGRESS:  33.33%

🐞 BACKEND REPORTED:  image upscayl:  35.00%

🚧 UPSCAYL_PROGRESS:  35.00%

🐞 BACKEND REPORTED:  image upscayl:  36.67%

🚧 UPSCAYL_PROGRESS:  36.67%

🐞 BACKEND REPORTED:  image upscayl:  38.33%

🚧 UPSCAYL_PROGRESS:  38.33%

🐞 BACKEND REPORTED:  image upscayl:  40.00%

🚧 UPSCAYL_PROGRESS:  40.00%

🐞 BACKEND REPORTED:  image upscayl:  41.67%

🚧 UPSCAYL_PROGRESS:  41.67%

🐞 BACKEND REPORTED:  image upscayl:  43.33%

🚧 UPSCAYL_PROGRESS:  43.33%

🐞 BACKEND REPORTED:  image upscayl:  45.00%

🚧 UPSCAYL_PROGRESS:  45.00%

🐞 BACKEND REPORTED:  image upscayl:  46.67%

🚧 UPSCAYL_PROGRESS:  46.67%

🐞 BACKEND REPORTED:  image upscayl:  48.33%

🚧 UPSCAYL_PROGRESS:  48.33%

🐞 BACKEND REPORTED:  image upscayl:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🐞 BACKEND REPORTED:  image upscayl:  51.67%

🚧 UPSCAYL_PROGRESS:  51.67%

🐞 BACKEND REPORTED:  image upscayl:  53.33%

🚧 UPSCAYL_PROGRESS:  53.33%

🐞 BACKEND REPORTED:  image upscayl:  55.00%

🚧 UPSCAYL_PROGRESS:  55.00%

🐞 BACKEND REPORTED:  image upscayl:  56.67%

🚧 UPSCAYL_PROGRESS:  56.67%

🐞 BACKEND REPORTED:  image upscayl:  58.33%

🚧 UPSCAYL_PROGRESS:  58.33%

🐞 BACKEND REPORTED:  image upscayl:  60.00%

🚧 UPSCAYL_PROGRESS:  60.00%

🐞 BACKEND REPORTED:  image upscayl:  61.67%

🚧 UPSCAYL_PROGRESS:  61.67%

🐞 BACKEND REPORTED:  image upscayl:  63.33%

🚧 UPSCAYL_PROGRESS:  63.33%

🐞 BACKEND REPORTED:  image upscayl:  65.00%

🚧 UPSCAYL_PROGRESS:  65.00%

🐞 BACKEND REPORTED:  image upscayl:  66.67%

🚧 UPSCAYL_PROGRESS:  66.67%

🐞 BACKEND REPORTED:  image upscayl:  68.33%

🚧 UPSCAYL_PROGRESS:  68.33%

🐞 BACKEND REPORTED:  image upscayl:  70.00%

🚧 UPSCAYL_PROGRESS:  70.00%

🐞 BACKEND REPORTED:  image upscayl:  71.67%

⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
🚧 UPSCAYL_PROGRESS:  71.67%

🐞 BACKEND REPORTED:  image upscayl:  73.33%

🚧 UPSCAYL_PROGRESS:  73.33%

🐞 BACKEND REPORTED:  image upscayl:  75.00%

🚧 UPSCAYL_PROGRESS:  75.00%

🐞 BACKEND REPORTED:  image upscayl:  76.67%

🚧 UPSCAYL_PROGRESS:  76.67%

🐞 BACKEND REPORTED:  image upscayl:  78.33%

🚧 UPSCAYL_PROGRESS:  78.33%

🐞 BACKEND REPORTED:  image upscayl:  80.00%

🚧 UPSCAYL_PROGRESS:  80.00%

🐞 BACKEND REPORTED:  image upscayl:  81.67%

🚧 UPSCAYL_PROGRESS:  81.67%

🐞 BACKEND REPORTED:  image upscayl:  83.33%

🚧 UPSCAYL_PROGRESS:  83.33%

🐞 BACKEND REPORTED:  image upscayl:  85.00%

🚧 UPSCAYL_PROGRESS:  85.00%

🐞 BACKEND REPORTED:  image upscayl:  86.67%

🚧 UPSCAYL_PROGRESS:  86.67%

🐞 BACKEND REPORTED:  image upscayl:  88.33%

🚧 UPSCAYL_PROGRESS:  88.33%

🐞 BACKEND REPORTED:  image upscayl:  90.00%

🚧 UPSCAYL_PROGRESS:  90.00%

🐞 BACKEND REPORTED:  image upscayl:  91.67%

🚧 UPSCAYL_PROGRESS:  91.67%

🐞 BACKEND REPORTED:  image upscayl:  93.33%

🚧 UPSCAYL_PROGRESS:  93.33%

🐞 BACKEND REPORTED:  image upscayl:  95.00%

🚧 UPSCAYL_PROGRESS:  95.00%

🐞 BACKEND REPORTED:  image upscayl:  96.67%

🚧 UPSCAYL_PROGRESS:  96.67%

🐞 BACKEND REPORTED:  image upscayl:  98.33%

🚧 UPSCAYL_PROGRESS:  98.33%

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  /Users/patrykkeska/Desktop/hrglago_0_upscayl_2x_realesrgan-x4plus.jpg

</pre>
</details>

### To Reproduce

1. Open upscale 
2. Pick img
3. Settings => 2x scale
4. upscale

### Expected Behavior

![test-img](https://github.com/upscayl/upscayl/assets/45535706/5be45a30-fc36-4f45-a9f3-88eaf8f44383)

### Version/Commit Hash

2.5.1

### OS Specifics

M1 Max  24 Cores 

### Screenshots

<img width="1296" alt="Screenshot 2023-05-14 at 17 35 44" src="https://github.com/upscayl/upscayl/assets/45535706/2bf90037-9b4a-4c89-84a4-abe370602fe1">

**Comment by aaronliu0130** [comment] 2023-05-14 17:04
Duplicate of #303 and the FAQ.
> I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-05-14 17:04 UTC
Labels: bug

**Comment by NayamAmarshe** [comment] 2023-05-14 22:24
Hi, please check the wiki. I've explained the issue there :)
