### ISSUE TITLE
Feature parity with Waifu2x-Extension-GUI

### ISSUE THREAD

**Issue by Tarek-Hasan** [upscayl/upscayl#162] opened 2022-12-24 14:31 UTC
[Waifu2x-Extension-GUI](https://github.com/AaronFeng753/Waifu2x-Extension-GUI) provides around similar quality results of top AI upscaling softwares, as shown here https://www.youtube.com/watch?v=D-4sq6EfElQ. And fully built upon open source AI libraries and technologies and has many models (models provided are non-free but built from open dataset). You can look into its features or models and try them out, for possible future enhancement.
I hope you would learn many things from this project.

**Comment by NayamAmarshe** [comment] 2022-12-24 16:40
I don't think we're trying to have feature parity with Waifu2x-Extension-GUI. We're aiming for something much simpler, something that even a kid can use without much reading.

More models are nice but the problem is with code storage. We cannot go over limits as we've already gone over the allowed limit for a repository 😅 I had to remove some models because of that.

**Comment by Tarek-Hasan** [comment] 2022-12-24 18:28
Why not maintain a different repo for models?

**Comment by NayamAmarshe** [comment] 2022-12-24 18:42
> Why not maintain a different repo for models?

The problem would be the distribution.

I'm planning to add an option to add custom models, would be nice.

**Comment by NayamAmarshe** [comment] 2022-12-27 12:02
Thanks for letting me know about this, I'm closing the issue.

**Closed by NayamAmarshe** 2022-12-27 12:02 UTC
