### ISSUE TITLE
Add DDS Support

### ISSUE THREAD

**Issue by TayMcKenzieNZ** [upscayl/upscayl#835] opened 2024-05-18 12:52 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Video games use DDS image format. It would be neat for the program to detect this format and allow upscaling.

### Related Problem(s)

Currently not supported unless image is converted to png

### Alternatives

Convert to jpg / png first, then upscale, then convert back to dds.

**Comment by NayamAmarshe** [comment] 2024-05-18 15:10
Duplicate of #114

**Closed by NayamAmarshe** 2024-05-18 15:10 UTC
Labels: enhancement
