### ISSUE TITLE
可以增加多国语言支持吗?

### ISSUE THREAD

**Issue by QQ804218** [upscayl/upscayl#446] opened 2023-09-03 02:33 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

可以增加多国语言支持吗?

### Related Problem(s)

可以增加多国语言支持吗?

### Alternatives

.....

**Comment by aaronliu0130** [comment] 2023-09-03 17:17
Duplicate of #91 .
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-09-03 17:17 UTC
Labels: enhancement

**Comment by QQ804218** [comment] 2023-09-06 03:05
![image](https://github.com/upscayl/upscayl/assets/67571282/ff053083-526e-4e58-a8be-e35079134d13)
已找到三方汉化版了,
