### ISSUE TITLE
allow preview button that does not save a final picture until you hit save (upscayl button)

### ISSUE THREAD

**Issue by XDM-Inc** [upscayl/upscayl#143] opened 2022-11-26 06:38 UTC
their should be a preview button that dose not save a photo yet and when you are satisfied then hit the upscayl button to finalize

**Comment by NayamAmarshe** [comment] 2022-11-27 05:16
Duplicate of #20 

I'll think about it. Currently there are other important features I have to work on so I'm a bit busy at the moment. Will add it in v2.1+ if possible

**Closed by NayamAmarshe** 2022-11-27 05:16 UTC
