### ISSUE TITLE
Open With Feature

### ISSUE THREAD

**Issue by yunus-cakir** [upscayl/upscayl#771] opened 2024-04-08 07:50 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Hi! Right clicking an image and opening it with Upscaly would be so easy if you have time to add this feature :))

**Comment by aaronliu0130** [comment] 2024-04-08 16:12
Duplicate of #268
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-04-08 16:12 UTC
Labels: enhancement

**Comment by NayamAmarshe** [comment] 2024-04-08 17:23
The only issue with this is that it's Windows specific for the most part and we have other things to take care of at the moment.

**Comment by aaronliu0130** [comment] 2024-04-08 17:31
I've documented some of my thoughts in 268. Interestingly, this effectively adds some CLI functionality to all platforms.
