### ISSUE TITLE
Do task by following folder hierarchy in batch mode

### ISSUE THREAD

**Issue by mic-user** [upscayl/upscayl#728] opened 2024-02-25 02:23 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Hi. Thanks for nice program.
Here is the thing.

If an user have conplex folder structure with image files that deep hierarchy,
the upscayl want to do follow the folder hierarchy and clone the folder hierarchy with up scaled output  in batch mode.

Please put his on the output option.

### Alternatives

No alternatives.

**Comment by aaronliu0130** [comment] 2024-02-25 02:35
Duplicate of #283 
> I have searched for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-02-25 02:35 UTC
Labels: enhancement
