### ISSUE TITLE
Batch upscale will not save images as JPG

### ISSUE THREAD

**Issue by codyzimmer** [upscayl/upscayl#273] opened 2023-04-13 21:33 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

Every time I try to batch upscale and select JPG as my image type, Upscayl still only produces PNG images.  I saw in the development roadmap that in v2.5 it is planned to just hide this option.  I would ask you to consider implementing it, as it would be a great time-saver for those of us who want/need images in JPG.

### To Reproduce

Batch upscale some images, select JPG as the image type.

### Expected Behavior

Upscayl should have produced images in .JPG format, but didn't.

### Version/Commit Hash

2.0.1

### OS Specifics

Mac OS 12.6.3 - AMD Radeon R9 M370X 2 GB Intel Iris Pro 1536 MB

### Screenshots

![2023-04-13_14-32-00](https://user-images.githubusercontent.com/98069576/231887666-060799f4-8f52-4b78-b2e6-2c5f42de5dec.png)
![2023-04-13_14-31-23](https://user-images.githubusercontent.com/98069576/231887671-fc0d6614-8bf1-4238-87c9-a9e8f18aa388.png)

**Comment by aaronliu0130** [comment] 2023-04-13 23:22
Duplicate of #174 
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-04-13 23:22 UTC
Labels: bug
