### ISSUE TITLE
Nested Folder Support

### ISSUE THREAD

**Issue by JoshMayberry** [upscayl/upscayl#400] opened 2023-07-22 01:08 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

It would be cool if nested folders were supported.
t could create an identical folder structure in it's new folder.

### Alternatives

Currently, I need to do each folder one by one.

**Comment by aaronliu0130** [comment] 2023-07-23 00:23
Duplicate of #283.

**Closed by aaronliu0130** 2023-07-23 00:23 UTC
Labels: enhancement
