### ISSUE TITLE
vkEnumeratePhysicalDevices failed 5 🚨 Error: Invalid GPU Device

### ISSUE THREAD

**Issue by Adilovnr** [upscayl/upscayl#836] opened 2024-05-18 13:34 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🖼 Selected Image Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
📁 Selected Image Directory:  C:\Users\ADLV_NDR\Downloads
🖼 imagePath:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"1","saveImageAs":"png","inputDir":"C:\\Users\\ADLV_NDR\\Downloads","fileNameWithExt":"16881103_014_62da.jpg","outputDir":"C:\\Users\\ADLV_NDR\\Downloads","outFile":"C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png","fileName":"16881103_014_62da","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg,-o,C:\Users\ADLV_NDR\Downloads\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png,-m,D:\upscayl-2.11.0-win\resources\models,-n,realesrgan-x4plus,-g,1,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","args":["D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","-i","C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da.jpg","-o","C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png","-m","D:\\upscayl-2.11.0-win\\resources\\models","-n","realesrgan-x4plus","-g","1","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1

### To Reproduce

You can't

### Upscayl Version (or commit hash)

2.11.0

### Platform

Windows

### OS Version

10

### GPU Name

NVIDIA GeForce GTX 1650

### Expected Behavior

Don't know

### Screenshots

No

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🎒 BACKEND REPORTED:  📄 Selected File Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🖼 Selected Image Path:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
📁 Selected Image Directory:  C:\Users\ADLV_NDR\Downloads
🖼 imagePath:  C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg
🔤 Extension:  jpg
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus","gpuId":"1","saveImageAs":"png","inputDir":"C:\\Users\\ADLV_NDR\\Downloads","fileNameWithExt":"16881103_014_62da.jpg","outputDir":"C:\\Users\\ADLV_NDR\\Downloads","outFile":"C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png","fileName":"16881103_014_62da","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":null}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,C:\Users\ADLV_NDR\Downloads\16881103_014_62da.jpg,-o,C:\Users\ADLV_NDR\Downloads\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png,-m,D:\upscayl-2.11.0-win\resources\models,-n,realesrgan-x4plus,-g,1,-f,png,-c,0
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","args":["D:\\upscayl-2.11.0-win\\resources\\bin\\upscayl-bin","-i","C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da.jpg","-o","C:\\Users\\ADLV_NDR\\Downloads\\16881103_014_62da_upscayl_4x_realesrgan-x4plus.png","-m","D:\\upscayl-2.11.0-win\\resources\\models","-n","realesrgan-x4plus","-g","1","-f","png","-c","0"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

🔄 Resetting image paths
🚧 UPSCAYL_PROGRESS:  vkEnumeratePhysicalDevices failed 5
🚨 Error: Invalid GPU Device

⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage:  1
```

**Comment by NayamAmarshe** [comment] 2024-05-18 15:13
Duplicate of #735

**Closed by NayamAmarshe** 2024-05-18 15:13 UTC
Labels: bug
