### ISSUE TITLE
Decoding Error, Ubuntu 22.04 (AppImage) 

### ISSUE THREAD

**Issue by link444112** [upscayl/upscayl#100] opened 2022-10-02 22:10 UTC
Other user reporting the same, but on Mac and Windows. 
![error](https://user-images.githubusercontent.com/104740380/193478496-a8eed37f-4ec9-45a4-b01d-a24b9ee1288e.png)

**Comment by aaronliu0130** [comment] 2022-10-03 00:27
Please don't open duplicate issues.

**Comment by NayamAmarshe** [comment] 2022-10-03 00:58
Duplicate of #98

**Closed by NayamAmarshe** 2022-10-03 00:58 UTC
