### ISSUE TITLE
When upscaling to an insanely large resolution, the upscayl process just terminates without error but no file has been created

### ISSUE THREAD

**Issue by KyodaiKen** [upscayl/upscayl#867] opened 2024-06-10 16:16 UTC
### Checklist

- [ ] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).

I can't do all these tasks as I would have to disable my iGPU in the BIOS which leads to my second monitor staying black. I could bring evidence that the iGPU is not the issue, as smaller images upscayl just fine. Vulkan and drivers are healthy as well. I also tried it with and without GPU overclocking.

- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

When upscaling to an insanely large resolution, the upscayl process just terminates without error but no file has been created.

I also ran the command line tool with verbose output, no error message is being shown, the process just terminates.

#863 seems to point to a similar issue.
#493 may be related as well.

### To Reproduce

1. Load an image with a size of for example 7800x3500 Pixels RGB888 (24 bit, no alpha).
2. Select Image Scale 2x and enable "Double Upscayl" - the model does not matter there, it happens regardles of the model
3. Run the upscayl and observe the second pass being terminated prematurely with the output file not being updated to the expected size.
-- OR --
1. Load an image with a size of for example 15200x7000 Pixels RGB888 (24 bit, no alpha).
2. Select Image Scale 2x and no "Double Upscayl" - the model does not matter there, it happens regardles of the model
3. Run the upscayl and observe the second pass being terminated prematurely with the output file not being updated to the expected size.

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

23H2 (OS Build 22631.3593)

### GPU Name

ASUS ROG STRIX NVidia RTX 3090 GAMING OC

### Expected Behavior

The upscayl should finish and not stall.

### Screenshots

Here you can see the UI after the progess allegedly successfully finished. Note the missing preview:
![image](https://github.com/upscayl/upscayl/assets/32415256/861d33ba-e5a8-4872-bc4d-72989114773f)

Here are hardware monitoring details just after the crash.
![pi-screen_2024-06-10_18-08-51](https://github.com/upscayl/upscayl/assets/32415256/744c4a5c-931c-4223-82e9-8ecb8f1d14a1)

GPU util. of iGPU is zero, so not used:
![image](https://github.com/upscayl/upscayl/assets/32415256/14502881-14e3-4554-a570-f676751da4c3)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
⤵️ Dropped file:  {"type":"image/png","filePath":"n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet\\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png","extension":"png"}
🖼 Setting image path:  n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png
🗂 Setting output path:  n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet
🖼 imagePath:  n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"realesrgan-x4plus-anime","gpuId":null,"saveImageAs":"png","inputDir":"n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet","fileNameWithExt":"Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png","outputDir":"n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet","outFile":"n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet\\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_realesrgan-x4plus-anime.png","fileName":"Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime","scale":"2","compression":"5","customWidth":"","useCustomWidth":false,"tileSize":512}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png,-o,n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_realesrgan-x4plus-anime.png,-s,2,-m,C:\Program Files\Upscayl\resources\models,-n,realesrgan-x4plus-anime,-f,png,-c,5,-t,512
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","args":["C:\\Program Files\\Upscayl\\resources\\bin\\upscayl-bin","-i","n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet\\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime.png","-o","n:\\commissions\\Kyoudai Ken\\The_Artspear\\NEW Ref Sheet\\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_realesrgan-x4plus-anime.png","-s","2","-m","C:\\Program Files\\Upscayl\\resources\\models","-n","realesrgan-x4plus-anime","-f","png","-c","5","-t","512"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce RTX 3090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 770]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 770]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 770]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 770]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce RTX 3090]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3090]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3090]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3090]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[1 Intel(R) UHD Graphics 770]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) UHD Graphics 770]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) UHD Graphics 770]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 Intel(R) UHD Graphics 770]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  0,00%

🚧 UPSCAYL_PROGRESS:  0,00%

🎒 BACKEND REPORTED:  0,24%

🚧 UPSCAYL_PROGRESS:  0,24%

🎒 BACKEND REPORTED:  0,48%

🚧 UPSCAYL_PROGRESS:  0,48%

🎒 BACKEND REPORTED:  0,71%

🚧 UPSCAYL_PROGRESS:  0,71%

🎒 BACKEND REPORTED:  0,95%

🚧 UPSCAYL_PROGRESS:  0,95%

🎒 BACKEND REPORTED:  1,19%

🚧 UPSCAYL_PROGRESS:  1,19%

🎒 BACKEND REPORTED:  1,43%

🚧 UPSCAYL_PROGRESS:  1,43%

🎒 BACKEND REPORTED:  1,67%

🚧 UPSCAYL_PROGRESS:  1,67%

🎒 BACKEND REPORTED:  1,90%

🚧 UPSCAYL_PROGRESS:  1,90%

🎒 BACKEND REPORTED:  2,14%

🚧 UPSCAYL_PROGRESS:  2,14%

🎒 BACKEND REPORTED:  2,38%

🚧 UPSCAYL_PROGRESS:  2,38%

🎒 BACKEND REPORTED:  2,62%

🚧 UPSCAYL_PROGRESS:  2,62%

🎒 BACKEND REPORTED:  2,86%

🚧 UPSCAYL_PROGRESS:  2,86%

🎒 BACKEND REPORTED:  3,10%

🚧 UPSCAYL_PROGRESS:  3,10%

🎒 BACKEND REPORTED:  3,33%

🚧 UPSCAYL_PROGRESS:  3,33%

🎒 BACKEND REPORTED:  3,57%

🚧 UPSCAYL_PROGRESS:  3,57%

🎒 BACKEND REPORTED:  3,81%

🚧 UPSCAYL_PROGRESS:  3,81%

🎒 BACKEND REPORTED:  4,05%

🚧 UPSCAYL_PROGRESS:  4,05%

🎒 BACKEND REPORTED:  4,29%

🚧 UPSCAYL_PROGRESS:  4,29%

🎒 BACKEND REPORTED:  4,52%

🚧 UPSCAYL_PROGRESS:  4,52%

🎒 BACKEND REPORTED:  4,76%

🚧 UPSCAYL_PROGRESS:  4,76%

🎒 BACKEND REPORTED:  5,00%

🚧 UPSCAYL_PROGRESS:  5,00%

🎒 BACKEND REPORTED:  5,24%

🚧 UPSCAYL_PROGRESS:  5,24%

🎒 BACKEND REPORTED:  5,48%

🚧 UPSCAYL_PROGRESS:  5,48%

🎒 BACKEND REPORTED:  5,71%

🚧 UPSCAYL_PROGRESS:  5,71%

🎒 BACKEND REPORTED:  5,95%

🚧 UPSCAYL_PROGRESS:  5,95%

🎒 BACKEND REPORTED:  6,19%

🚧 UPSCAYL_PROGRESS:  6,19%

🎒 BACKEND REPORTED:  6,43%

🚧 UPSCAYL_PROGRESS:  6,43%

🎒 BACKEND REPORTED:  6,67%

🚧 UPSCAYL_PROGRESS:  6,67%

🎒 BACKEND REPORTED:  6,90%

🚧 UPSCAYL_PROGRESS:  6,90%

🎒 BACKEND REPORTED:  7,14%

🚧 UPSCAYL_PROGRESS:  7,14%

🎒 BACKEND REPORTED:  7,38%

🚧 UPSCAYL_PROGRESS:  7,38%

🎒 BACKEND REPORTED:  7,62%

🚧 UPSCAYL_PROGRESS:  7,62%

🎒 BACKEND REPORTED:  7,86%

🚧 UPSCAYL_PROGRESS:  7,86%

🎒 BACKEND REPORTED:  8,10%

🚧 UPSCAYL_PROGRESS:  8,10%

🎒 BACKEND REPORTED:  8,33%

🚧 UPSCAYL_PROGRESS:  8,33%

🎒 BACKEND REPORTED:  8,57%

🚧 UPSCAYL_PROGRESS:  8,57%

🎒 BACKEND REPORTED:  8,81%

🚧 UPSCAYL_PROGRESS:  8,81%

🎒 BACKEND REPORTED:  9,05%

🚧 UPSCAYL_PROGRESS:  9,05%

🎒 BACKEND REPORTED:  9,29%
9,52%
9,76%

🚧 UPSCAYL_PROGRESS:  9,29%
9,52%
9,76%

🎒 BACKEND REPORTED:  10,00%

🚧 UPSCAYL_PROGRESS:  10,00%

🎒 BACKEND REPORTED:  10,24%

🚧 UPSCAYL_PROGRESS:  10,24%

🎒 BACKEND REPORTED:  10,48%

🚧 UPSCAYL_PROGRESS:  10,48%

🎒 BACKEND REPORTED:  10,71%

🚧 UPSCAYL_PROGRESS:  10,71%

🎒 BACKEND REPORTED:  10,95%

🚧 UPSCAYL_PROGRESS:  10,95%

🎒 BACKEND REPORTED:  11,19%

🚧 UPSCAYL_PROGRESS:  11,19%

🎒 BACKEND REPORTED:  11,43%

🚧 UPSCAYL_PROGRESS:  11,43%

🎒 BACKEND REPORTED:  11,67%

🚧 UPSCAYL_PROGRESS:  11,67%

🎒 BACKEND REPORTED:  11,90%

🚧 UPSCAYL_PROGRESS:  11,90%

🎒 BACKEND REPORTED:  12,14%

🚧 UPSCAYL_PROGRESS:  12,14%

🎒 BACKEND REPORTED:  12,38%

🚧 UPSCAYL_PROGRESS:  12,38%

🎒 BACKEND REPORTED:  12,62%

🚧 UPSCAYL_PROGRESS:  12,62%

🎒 BACKEND REPORTED:  12,86%

🚧 UPSCAYL_PROGRESS:  12,86%

🎒 BACKEND REPORTED:  13,10%

🚧 UPSCAYL_PROGRESS:  13,10%

🎒 BACKEND REPORTED:  13,33%

🚧 UPSCAYL_PROGRESS:  13,33%

🎒 BACKEND REPORTED:  13,57%

🚧 UPSCAYL_PROGRESS:  13,57%

🎒 BACKEND REPORTED:  13,81%

🚧 UPSCAYL_PROGRESS:  13,81%

🎒 BACKEND REPORTED:  14,05%

🚧 UPSCAYL_PROGRESS:  14,05%

🎒 BACKEND REPORTED:  14,29%

🚧 UPSCAYL_PROGRESS:  14,29%

🎒 BACKEND REPORTED:  14,52%

🚧 UPSCAYL_PROGRESS:  14,52%

🎒 BACKEND REPORTED:  14,76%

🚧 UPSCAYL_PROGRESS:  14,76%

🎒 BACKEND REPORTED:  15,00%

🚧 UPSCAYL_PROGRESS:  15,00%

🎒 BACKEND REPORTED:  15,24%

🚧 UPSCAYL_PROGRESS:  15,24%

🎒 BACKEND REPORTED:  15,48%

🚧 UPSCAYL_PROGRESS:  15,48%

🎒 BACKEND REPORTED:  15,71%

🚧 UPSCAYL_PROGRESS:  15,71%

🎒 BACKEND REPORTED:  15,95%

🚧 UPSCAYL_PROGRESS:  15,95%

🎒 BACKEND REPORTED:  16,19%

🚧 UPSCAYL_PROGRESS:  16,19%

🎒 BACKEND REPORTED:  16,43%

🚧 UPSCAYL_PROGRESS:  16,43%

🎒 BACKEND REPORTED:  16,67%

🚧 UPSCAYL_PROGRESS:  16,67%

🎒 BACKEND REPORTED:  16,90%

🚧 UPSCAYL_PROGRESS:  16,90%

🎒 BACKEND REPORTED:  17,14%

🚧 UPSCAYL_PROGRESS:  17,14%

🎒 BACKEND REPORTED:  17,38%

🚧 UPSCAYL_PROGRESS:  17,38%

🎒 BACKEND REPORTED:  17,62%

🚧 UPSCAYL_PROGRESS:  17,62%

🎒 BACKEND REPORTED:  17,86%

🚧 UPSCAYL_PROGRESS:  17,86%

🎒 BACKEND REPORTED:  18,10%

🚧 UPSCAYL_PROGRESS:  18,10%

🎒 BACKEND REPORTED:  18,33%

🚧 UPSCAYL_PROGRESS:  18,33%

🎒 BACKEND REPORTED:  18,57%

🚧 UPSCAYL_PROGRESS:  18,57%

🎒 BACKEND REPORTED:  18,81%

🚧 UPSCAYL_PROGRESS:  18,81%

🎒 BACKEND REPORTED:  19,05%

🚧 UPSCAYL_PROGRESS:  19,05%

🎒 BACKEND REPORTED:  19,29%

🚧 UPSCAYL_PROGRESS:  19,29%

🎒 BACKEND REPORTED:  19,52%

🚧 UPSCAYL_PROGRESS:  19,52%

🎒 BACKEND REPORTED:  19,76%

🚧 UPSCAYL_PROGRESS:  19,76%

🎒 BACKEND REPORTED:  20,00%

🚧 UPSCAYL_PROGRESS:  20,00%

🎒 BACKEND REPORTED:  20,24%

🚧 UPSCAYL_PROGRESS:  20,24%

🎒 BACKEND REPORTED:  20,48%

🚧 UPSCAYL_PROGRESS:  20,48%

🎒 BACKEND REPORTED:  20,71%

🚧 UPSCAYL_PROGRESS:  20,71%

🎒 BACKEND REPORTED:  20,95%

🚧 UPSCAYL_PROGRESS:  20,95%

🎒 BACKEND REPORTED:  21,19%

🚧 UPSCAYL_PROGRESS:  21,19%

🎒 BACKEND REPORTED:  21,43%

🚧 UPSCAYL_PROGRESS:  21,43%

🎒 BACKEND REPORTED:  21,67%

🚧 UPSCAYL_PROGRESS:  21,67%

🎒 BACKEND REPORTED:  21,90%

🚧 UPSCAYL_PROGRESS:  21,90%

🎒 BACKEND REPORTED:  22,14%

🚧 UPSCAYL_PROGRESS:  22,14%

🎒 BACKEND REPORTED:  22,38%

🚧 UPSCAYL_PROGRESS:  22,38%

🎒 BACKEND REPORTED:  22,62%

🚧 UPSCAYL_PROGRESS:  22,62%

🎒 BACKEND REPORTED:  22,86%

🚧 UPSCAYL_PROGRESS:  22,86%

🎒 BACKEND REPORTED:  23,10%

🚧 UPSCAYL_PROGRESS:  23,10%

🎒 BACKEND REPORTED:  23,33%

🚧 UPSCAYL_PROGRESS:  23,33%

🎒 BACKEND REPORTED:  23,57%

🚧 UPSCAYL_PROGRESS:  23,57%

🎒 BACKEND REPORTED:  23,81%

🚧 UPSCAYL_PROGRESS:  23,81%

🎒 BACKEND REPORTED:  24,05%

🚧 UPSCAYL_PROGRESS:  24,05%

🎒 BACKEND REPORTED:  24,29%

🚧 UPSCAYL_PROGRESS:  24,29%

🎒 BACKEND REPORTED:  24,52%

🚧 UPSCAYL_PROGRESS:  24,52%

🎒 BACKEND REPORTED:  24,76%

🚧 UPSCAYL_PROGRESS:  24,76%

🎒 BACKEND REPORTED:  25,00%

🚧 UPSCAYL_PROGRESS:  25,00%

🎒 BACKEND REPORTED:  25,24%

🚧 UPSCAYL_PROGRESS:  25,24%

🎒 BACKEND REPORTED:  25,48%

🚧 UPSCAYL_PROGRESS:  25,48%

🎒 BACKEND REPORTED:  25,71%

🚧 UPSCAYL_PROGRESS:  25,71%

🎒 BACKEND REPORTED:  25,95%

🚧 UPSCAYL_PROGRESS:  25,95%

🎒 BACKEND REPORTED:  26,19%

🚧 UPSCAYL_PROGRESS:  26,19%

🎒 BACKEND REPORTED:  26,43%

🚧 UPSCAYL_PROGRESS:  26,43%

🎒 BACKEND REPORTED:  26,67%

🚧 UPSCAYL_PROGRESS:  26,67%

🎒 BACKEND REPORTED:  26,90%

🚧 UPSCAYL_PROGRESS:  26,90%

🎒 BACKEND REPORTED:  27,14%

🚧 UPSCAYL_PROGRESS:  27,14%

🎒 BACKEND REPORTED:  27,38%

🚧 UPSCAYL_PROGRESS:  27,38%

🎒 BACKEND REPORTED:  27,62%

🚧 UPSCAYL_PROGRESS:  27,62%

🎒 BACKEND REPORTED:  27,86%

🚧 UPSCAYL_PROGRESS:  27,86%

🎒 BACKEND REPORTED:  28,10%

🚧 UPSCAYL_PROGRESS:  28,10%

🎒 BACKEND REPORTED:  28,33%

🚧 UPSCAYL_PROGRESS:  28,33%

🎒 BACKEND REPORTED:  28,57%

🚧 UPSCAYL_PROGRESS:  28,57%

🎒 BACKEND REPORTED:  28,81%

🚧 UPSCAYL_PROGRESS:  28,81%

🎒 BACKEND REPORTED:  29,05%

🚧 UPSCAYL_PROGRESS:  29,05%

🎒 BACKEND REPORTED:  29,29%

🚧 UPSCAYL_PROGRESS:  29,29%

🎒 BACKEND REPORTED:  29,52%

🚧 UPSCAYL_PROGRESS:  29,52%

🎒 BACKEND REPORTED:  29,76%

🚧 UPSCAYL_PROGRESS:  29,76%

🎒 BACKEND REPORTED:  30,00%

🚧 UPSCAYL_PROGRESS:  30,00%

🎒 BACKEND REPORTED:  30,24%

🚧 UPSCAYL_PROGRESS:  30,24%

🎒 BACKEND REPORTED:  30,48%

🚧 UPSCAYL_PROGRESS:  30,48%

🎒 BACKEND REPORTED:  30,71%

🚧 UPSCAYL_PROGRESS:  30,71%

🎒 BACKEND REPORTED:  30,95%

🚧 UPSCAYL_PROGRESS:  30,95%

🎒 BACKEND REPORTED:  31,19%

🚧 UPSCAYL_PROGRESS:  31,19%

🎒 BACKEND REPORTED:  31,43%

🚧 UPSCAYL_PROGRESS:  31,43%

🎒 BACKEND REPORTED:  31,67%

🚧 UPSCAYL_PROGRESS:  31,67%

🎒 BACKEND REPORTED:  31,90%

🚧 UPSCAYL_PROGRESS:  31,90%

🎒 BACKEND REPORTED:  32,14%

🚧 UPSCAYL_PROGRESS:  32,14%

🎒 BACKEND REPORTED:  32,38%

🚧 UPSCAYL_PROGRESS:  32,38%

🎒 BACKEND REPORTED:  32,62%

🚧 UPSCAYL_PROGRESS:  32,62%

🎒 BACKEND REPORTED:  32,86%

🚧 UPSCAYL_PROGRESS:  32,86%

🎒 BACKEND REPORTED:  33,10%

🚧 UPSCAYL_PROGRESS:  33,10%

🎒 BACKEND REPORTED:  33,33%

🚧 UPSCAYL_PROGRESS:  33,33%

🎒 BACKEND REPORTED:  33,57%

🚧 UPSCAYL_PROGRESS:  33,57%

🎒 BACKEND REPORTED:  33,81%

🚧 UPSCAYL_PROGRESS:  33,81%

🎒 BACKEND REPORTED:  34,05%

🚧 UPSCAYL_PROGRESS:  34,05%

🎒 BACKEND REPORTED:  34,29%

🚧 UPSCAYL_PROGRESS:  34,29%

🎒 BACKEND REPORTED:  34,52%

🚧 UPSCAYL_PROGRESS:  34,52%

🎒 BACKEND REPORTED:  34,76%

🚧 UPSCAYL_PROGRESS:  34,76%

🎒 BACKEND REPORTED:  35,00%

🚧 UPSCAYL_PROGRESS:  35,00%

🎒 BACKEND REPORTED:  35,24%

🚧 UPSCAYL_PROGRESS:  35,24%

🎒 BACKEND REPORTED:  35,48%

🚧 UPSCAYL_PROGRESS:  35,48%

🎒 BACKEND REPORTED:  35,71%

🚧 UPSCAYL_PROGRESS:  35,71%

🎒 BACKEND REPORTED:  35,95%

🚧 UPSCAYL_PROGRESS:  35,95%

🎒 BACKEND REPORTED:  36,19%

🚧 UPSCAYL_PROGRESS:  36,19%

🎒 BACKEND REPORTED:  36,43%

🚧 UPSCAYL_PROGRESS:  36,43%

🎒 BACKEND REPORTED:  36,67%

🚧 UPSCAYL_PROGRESS:  36,67%

🎒 BACKEND REPORTED:  36,90%

🚧 UPSCAYL_PROGRESS:  36,90%

🎒 BACKEND REPORTED:  37,14%

🚧 UPSCAYL_PROGRESS:  37,14%

🎒 BACKEND REPORTED:  37,38%

🚧 UPSCAYL_PROGRESS:  37,38%

🎒 BACKEND REPORTED:  37,62%

🚧 UPSCAYL_PROGRESS:  37,62%

🎒 BACKEND REPORTED:  37,86%

🚧 UPSCAYL_PROGRESS:  37,86%

🎒 BACKEND REPORTED:  38,10%

🚧 UPSCAYL_PROGRESS:  38,10%

🎒 BACKEND REPORTED:  38,33%

🚧 UPSCAYL_PROGRESS:  38,33%

🎒 BACKEND REPORTED:  38,57%

🚧 UPSCAYL_PROGRESS:  38,57%

🎒 BACKEND REPORTED:  38,81%

🚧 UPSCAYL_PROGRESS:  38,81%

🎒 BACKEND REPORTED:  39,05%

🚧 UPSCAYL_PROGRESS:  39,05%

🎒 BACKEND REPORTED:  39,29%

🚧 UPSCAYL_PROGRESS:  39,29%

🎒 BACKEND REPORTED:  39,52%

🚧 UPSCAYL_PROGRESS:  39,52%

🎒 BACKEND REPORTED:  39,76%

🚧 UPSCAYL_PROGRESS:  39,76%

🎒 BACKEND REPORTED:  40,00%

🚧 UPSCAYL_PROGRESS:  40,00%

🎒 BACKEND REPORTED:  40,24%

🚧 UPSCAYL_PROGRESS:  40,24%

🎒 BACKEND REPORTED:  40,48%

🚧 UPSCAYL_PROGRESS:  40,48%

🎒 BACKEND REPORTED:  40,71%

🚧 UPSCAYL_PROGRESS:  40,71%

🎒 BACKEND REPORTED:  40,95%

🚧 UPSCAYL_PROGRESS:  40,95%

🎒 BACKEND REPORTED:  41,19%

🚧 UPSCAYL_PROGRESS:  41,19%

🎒 BACKEND REPORTED:  41,43%

🚧 UPSCAYL_PROGRESS:  41,43%

🎒 BACKEND REPORTED:  41,67%

🚧 UPSCAYL_PROGRESS:  41,67%

🎒 BACKEND REPORTED:  41,90%

🚧 UPSCAYL_PROGRESS:  41,90%

🎒 BACKEND REPORTED:  42,14%

🚧 UPSCAYL_PROGRESS:  42,14%

🎒 BACKEND REPORTED:  42,38%

🚧 UPSCAYL_PROGRESS:  42,38%

🎒 BACKEND REPORTED:  42,62%

🚧 UPSCAYL_PROGRESS:  42,62%

🎒 BACKEND REPORTED:  42,86%

🚧 UPSCAYL_PROGRESS:  42,86%

🎒 BACKEND REPORTED:  43,10%

🚧 UPSCAYL_PROGRESS:  43,10%

🎒 BACKEND REPORTED:  43,33%

🚧 UPSCAYL_PROGRESS:  43,33%

🎒 BACKEND REPORTED:  43,57%

🚧 UPSCAYL_PROGRESS:  43,57%

🎒 BACKEND REPORTED:  43,81%

🚧 UPSCAYL_PROGRESS:  43,81%

🎒 BACKEND REPORTED:  44,05%

🚧 UPSCAYL_PROGRESS:  44,05%

🎒 BACKEND REPORTED:  44,29%

🚧 UPSCAYL_PROGRESS:  44,29%

🎒 BACKEND REPORTED:  44,52%

🚧 UPSCAYL_PROGRESS:  44,52%

🎒 BACKEND REPORTED:  44,76%

🚧 UPSCAYL_PROGRESS:  44,76%

🎒 BACKEND REPORTED:  45,00%

🚧 UPSCAYL_PROGRESS:  45,00%

🎒 BACKEND REPORTED:  45,24%

🚧 UPSCAYL_PROGRESS:  45,24%

🎒 BACKEND REPORTED:  45,48%

🚧 UPSCAYL_PROGRESS:  45,48%

🎒 BACKEND REPORTED:  45,71%

🚧 UPSCAYL_PROGRESS:  45,71%

🎒 BACKEND REPORTED:  45,95%

🚧 UPSCAYL_PROGRESS:  45,95%

🎒 BACKEND REPORTED:  46,19%

🚧 UPSCAYL_PROGRESS:  46,19%

🎒 BACKEND REPORTED:  46,43%

🚧 UPSCAYL_PROGRESS:  46,43%

🎒 BACKEND REPORTED:  46,67%

🚧 UPSCAYL_PROGRESS:  46,67%

🎒 BACKEND REPORTED:  46,90%

🚧 UPSCAYL_PROGRESS:  46,90%

🎒 BACKEND REPORTED:  47,14%

🚧 UPSCAYL_PROGRESS:  47,14%

🎒 BACKEND REPORTED:  47,38%

🚧 UPSCAYL_PROGRESS:  47,38%

🎒 BACKEND REPORTED:  47,62%

🚧 UPSCAYL_PROGRESS:  47,62%

🎒 BACKEND REPORTED:  47,86%

🚧 UPSCAYL_PROGRESS:  47,86%

🎒 BACKEND REPORTED:  48,10%

🚧 UPSCAYL_PROGRESS:  48,10%

🎒 BACKEND REPORTED:  48,33%

🚧 UPSCAYL_PROGRESS:  48,33%

🎒 BACKEND REPORTED:  48,57%

🚧 UPSCAYL_PROGRESS:  48,57%

🎒 BACKEND REPORTED:  48,81%

🚧 UPSCAYL_PROGRESS:  48,81%

🎒 BACKEND REPORTED:  49,05%

🚧 UPSCAYL_PROGRESS:  49,05%

🎒 BACKEND REPORTED:  49,29%

🚧 UPSCAYL_PROGRESS:  49,29%

🎒 BACKEND REPORTED:  49,52%

🚧 UPSCAYL_PROGRESS:  49,52%

🎒 BACKEND REPORTED:  49,76%

🚧 UPSCAYL_PROGRESS:  49,76%

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_realesrgan-x4plus-anime.png
💯 UPSCAYL_DONE:  n:\commissions\Kyoudai Ken\The_Artspear\NEW Ref Sheet\Kyo_Lower_Armor_Colors_WIP_15_upscayl_2x_realesrgan-x4plus-anime_upscayl_2x_realesrgan-x4plus-anime.png
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
```

**Comment by NayamAmarshe** [comment] 2024-06-10 19:09
Duplicate of #493

**Closed by NayamAmarshe** 2024-06-10 19:09 UTC
Labels: bug
