### ISSUE TITLE
Bulk folder dont detect images in subfolders Linux

### ISSUE THREAD

**Issue by Milor123** [upscayl/upscayl#507] opened 2023-10-05 16:02 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

```sh
⚙️ Setting saveImageAs to png
🔀 Setting model to realesrgan-x4plus
⚙️ Setting gpuId to empty string
🔀 Setting model to 
⚙️ upscayl cloud show to true
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  📝 Updating Overwrite:  false
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📁 Updating Folder Path:  /media/noe/HHDGAMEs/Monster/Folders
🖼 Selected Folder Path:  /media/noe/HHDGAMEs/Monster/Folders
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  /media/noe/HHDGAMEs/Monster/Folders
⚙️ Getting saveImageAs from localStorage:  png
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Setting rememberOutputFolder to false
⚙️ Setting compression to 100%
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/media/noe/HHDGAMEs/Monster/Folders,-o,/media/noe/HHDGAMEs/Monster/Folders_upscayled_realesrgan-x4plus_x4,-s,4,-m,/opt/Upscayl/resources/models,-n,realesrgan-x4plus,,,-f,png
🐞 BACKEND REPORTED:  🛑 Updating Stopped:  false
🚧 FOLDER_UPSCAYL_PROGRESS:  MESA-INTEL: warning: Haswell Vulkan support is incomplete

🚧 FOLDER_UPSCAYL_PROGRESS:  [0 AMD Radeon RX 6750 XT]  queueC=1[4]  queueG=0[1]  queueT=2[2]
🚧 FOLDER_UPSCAYL_PROGRESS:  
[0 AMD Radeon RX 6750 XT]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 AMD Radeon RX 6750 XT]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 AMD Radeon RX 6750 XT]  subgroup=64  basic=1  vote=1  ballot=1  shuffle=1

🚧 FOLDER_UPSCAYL_PROGRESS:  [1 Intel(R) HD Graphics 4600 (HSW GT2)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[1 Intel(R) HD Graphics 4600 (HSW GT2)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 Intel(R) HD Graphics 4600 (HSW GT2)]  fp16-p/s/a=1/0/0  int8-p/s/a=1/0/0
[1 Intel(R) HD Graphics 4600 (HSW GT2)]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage:  false
⚙️ Getting compression from localStorage 0
🐞 BACKEND REPORTED:  💯 Done upscaling
🐞 BACKEND REPORTED:  ♻ Scaling and converting now...
💯 FOLDER_UPSCAYL_DONE:  /media/noe/HHDGAMEs/Monster/Folders_upscayled_realesrgan-x4plus_x4
```

### Describe the Bug

I need select all the subfolder with imagenes in my `Main Folder`, whose structure is as follows:
```
--- Main Folder ( I need select it)
    --- Subfolder 1
         --- ImageA.webp
         --- ImageB.webp
         --- ImageC.webp
    --- Subfolder 2
         --- ImageA.webp
         --- ImageB.webp
         --- ImageC.webp
    --- Subfolder 3
         --- ImageA.webp
         --- ImageB.webp
         --- ImageC.webp
```

But the Upscaly only works if I select folder by folder, and it have many many subfolders with the same format of images.

### To Reproduce

I try use upscaly DEB version for my linux ubuntu 22.04 it work only selecting subfolder indivially, in the flatpak version the bulk dont work

the upscaly creates a `/media/noe/HHDGAMEs/Monster/Folders_upscayled_realesrgan-x4plus_x4` but it dont contain nothing.

### Version/Commit Hash

2.8.6 Debian version

### OS Specifics

Ubuntu 22.04 LTS

### Expected Behavior

Search imagenes over each subfolder and convert it.

**Comment by NayamAmarshe** [comment] 2023-10-05 18:57
Yes, this is currently a limitation on ncnn-vulkan Real-ESRGAN.

**Comment by Milor123** [comment] 2023-10-05 20:34
> Yes, this is currently a limitation on ncnn-vulkan Real-ESRGAN.

Ohh it could be a amazing feature its needed. How can I temporal solve it? 
I hace many subfolders and cant select one by one. Thank u very much

**Comment by aaronliu0130** [comment] 2023-10-05 20:54
Duplicate of #283 
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

---

You can try spawning multiple Upscayl instances for now

**Closed** 2023-10-05 21:18 UTC
Labels: bug
