### ISSUE TITLE
One button to upscale using all models

### ISSUE THREAD

**Issue by javad94** [upscayl/upscayl#1082] opened 2024-12-25 19:51 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Description

Hi there, can you add an option to upscale using all models so we can compare the result easily?

**Comment by aaronliu0130** [comment] 2024-12-27 16:54
Duplicate of #851
> I have searched for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-12-27 16:54 UTC
Labels: enhancement
