### ISSUE TITLE
Unknow Bug

### ISSUE THREAD

**Issue by PierrunoYT** [upscayl/upscayl#713] opened 2024-02-14 09:20 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

I don't see the difference between the two pictures. I want to use the slider.

### To Reproduce

Im not sure

### Upscayl Version (or commit hash)

2.6.6.

### Platform

Windows

### OS Version

Windows 11

### GPU Name

RTX 3080

### Expected Behavior

I want to use the slider.

### Screenshots

![grafik](https://github.com/upscayl/upscayl/assets/95778421/14852aa5-c602-4caa-980e-e2128f28ff31)

### Logs

```sh
No
```

**Comment by PierrunoYT** [comment] 2024-02-14 09:22
![grafik](https://github.com/upscayl/upscayl/assets/95778421/c593edfe-0165-44db-aeb4-c2e278390f35)

**Comment by PierrunoYT** [comment] 2024-02-14 09:22
It's upsidedown

**Comment by aaronliu0130** [comment] 2024-02-14 14:34
Duplicate of #68

**Closed by aaronliu0130** 2024-02-14 14:34 UTC
Labels: bug

**Comment by NayamAmarshe** [comment] 2024-02-15 09:49
I fixed this bug a long time ago and it still appears from time to time. No idea why. Probably a sharp.js issue
