### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by awadrummer** [upscayl/upscayl#1070] opened 2024-12-19 19:42 UTC
I'm receiving this error when launching the application. Does it not work offline? Is there a fix I'm overlooking in the previously reported issues? 

Application error: a client-side exception has occurred (see the browser console for more information).

![image](https://github.com/user-attachments/assets/79733ccd-9faf-458a-bb35-c75c0000f3be)

**Comment by NayamAmarshe** [comment] 2024-12-20 01:15
What exactly made this happen? This error is certainly not normal.

**Comment by HighGreen17** [comment] 2024-12-20 06:49
Oh!  Me too! 
I know that what do you 
You did add the order model in the program that choice  model  
 That  time started  error, Right?
How do  add the order model?
ex: I tried to figure out how the error started

**Comment by NayamAmarshe** [comment] 2024-12-20 09:39
Could you please Press: Control+Shift+J? You'll see an error, could you please post a screenshot of it?

**Comment by nienphan1** [comment] 2024-12-20 10:34
same ver 2.15.1
![image](https://github.com/user-attachments/assets/0d76eb07-afda-4cc4-8e53-a8371859d70f)

**Comment by nienphan1** [comment] 2024-12-20 10:37
> Bạn vui lòng nhấn: Control+Shift+J. Bạn sẽ thấy lỗi, bạn vui lòng đăng ảnh chụp màn hình lỗi đó được không?

Initially, I used the application normally. However, after choosing to upscale with the old custom model, the issue occurred. I tried uninstalling and reinstalling the app, but the error still persists.

**Comment by NayamAmarshe** [comment] 2024-12-20 12:13
> > Bạn vui lòng nhấn: Control+Shift+J. Bạn sẽ thấy lỗi, bạn vui lòng đăng ảnh chụp màn hình lỗi đó được không?
> 
> Initially, I used the application normally. However, after choosing to upscale with the old custom model, the issue occurred. I tried uninstalling and reinstalling the app, but the error still persists.

Can you try F12 or Ctrl + Shift + J or Ctrl+Shift+I and send a screenshot of the error inside console?

**Comment by nienphan1** [comment] 2024-12-20 12:18
> > > Bạn vui lòng nhấn: Control+Shift+J. Bạn sẽ thấy lỗi, bạn vui lòng đăng ảnh chụp màn hình lỗi đó được không?
> > 
> > 
> > Initially, I used the application normally. However, after choosing to upscale with the old custom model, the issue occurred. I tried uninstalling and reinstalling the app, but the error still persists.
> 
> Can you try F12 or Ctrl + Shift + J or Ctrl+Shift+I and send a screenshot of the error inside console?

Do you need anything else?

**Comment by nienphan1** [comment] 2024-12-20 13:30
> No, this is perfect! Thanks a lot. To fix this, click the [>>] button next to Network tab and select 'Application' and then select 'Storage' and click: Clear Site Data.
> 
> This should fix the error for now. I'll fix it in the new release.

thank you

**Comment by dontknowhy** [comment] 2024-12-21 04:38
But that doesn't work for me :(
```
framework-14efab3c3d1ed63b.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at em (index-806dc3b0805cdd8b.js:1:84348)
    at ad (framework-14efab3c3d1ed63b.js:1:58495)
    at ud (framework-14efab3c3d1ed63b.js:1:72825)
    at i (framework-14efab3c3d1ed63b.js:1:120357)
    at oO (framework-14efab3c3d1ed63b.js:1:99113)
    at framework-14efab3c3d1ed63b.js:1:98980
    at oF (framework-14efab3c3d1ed63b.js:1:98987)
    at ox (framework-14efab3c3d1ed63b.js:1:95739)
    at oC (framework-14efab3c3d1ed63b.js:1:96128)
    at r8 (framework-14efab3c3d1ed63b.js:1:44905)
a5 @ framework-14efab3c3d1ed63b.js:1
main-1af57f7b849fbe67.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at em (index-806dc3b0805cdd8b.js:1:84348)
    at ad (framework-14efab3c3d1ed63b.js:1:58495)
    at ud (framework-14efab3c3d1ed63b.js:1:72825)
    at i (framework-14efab3c3d1ed63b.js:1:120357)
    at oO (framework-14efab3c3d1ed63b.js:1:99113)
    at framework-14efab3c3d1ed63b.js:1:98980
    at oF (framework-14efab3c3d1ed63b.js:1:98987)
    at ox (framework-14efab3c3d1ed63b.js:1:95739)
    at oC (framework-14efab3c3d1ed63b.js:1:96128)
    at r8 (framework-14efab3c3d1ed63b.js:1:44905)
et @ main-1af57f7b849fbe67.js:1
main-1af57f7b849fbe67.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```
Sorry for copying the chrome's console log because I can't upload pics here :(

**Comment by NayamAmarshe** [comment] 2024-12-21 08:10
> But that doesn't work for me :(
> 
> ```
> framework-14efab3c3d1ed63b.js:1 TypeError: Cannot read properties of undefined (reading 'id')
>     at em (index-806dc3b0805cdd8b.js:1:84348)
>     at ad (framework-14efab3c3d1ed63b.js:1:58495)
>     at ud (framework-14efab3c3d1ed63b.js:1:72825)
>     at i (framework-14efab3c3d1ed63b.js:1:120357)
>     at oO (framework-14efab3c3d1ed63b.js:1:99113)
>     at framework-14efab3c3d1ed63b.js:1:98980
>     at oF (framework-14efab3c3d1ed63b.js:1:98987)
>     at ox (framework-14efab3c3d1ed63b.js:1:95739)
>     at oC (framework-14efab3c3d1ed63b.js:1:96128)
>     at r8 (framework-14efab3c3d1ed63b.js:1:44905)
> a5 @ framework-14efab3c3d1ed63b.js:1
> main-1af57f7b849fbe67.js:1 TypeError: Cannot read properties of undefined (reading 'id')
>     at em (index-806dc3b0805cdd8b.js:1:84348)
>     at ad (framework-14efab3c3d1ed63b.js:1:58495)
>     at ud (framework-14efab3c3d1ed63b.js:1:72825)
>     at i (framework-14efab3c3d1ed63b.js:1:120357)
>     at oO (framework-14efab3c3d1ed63b.js:1:99113)
>     at framework-14efab3c3d1ed63b.js:1:98980
>     at oF (framework-14efab3c3d1ed63b.js:1:98987)
>     at ox (framework-14efab3c3d1ed63b.js:1:95739)
>     at oC (framework-14efab3c3d1ed63b.js:1:96128)
>     at r8 (framework-14efab3c3d1ed63b.js:1:44905)
> et @ main-1af57f7b849fbe67.js:1
> main-1af57f7b849fbe67.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
> ```
> 
> Sorry for copying the chrome's console log because I can't upload pics here :(

Are you able to reproduce the issue? How did the error happen, could you write the steps so that I can test on my machine?

**Comment by dontknowhy** [comment] 2024-12-21 08:33
> Are you able to reproduce the issue? How did the error happen, could you write the steps so that I can test on my machine?
Yep.(Upscayl 2.15.1)
1. delete ~/.config/Upscayl so there aren't any configs.
2. start Upscayl from console so I can prove the error message won't print in console.
3. add custom models from [Upscayl's offical model repo](https://github.com/upscayl/custom-models) (I know models is inside the `models` directory.
5. console log:
```
16:23:50.398 › 🎒 BACKEND REPORTED:  📁 Custom Folder Path:  /home/dontknowhy/custom-models/models
16:23:50.400 › 🎒 BACKEND REPORTED:  📁 Updating Custom Models Folder Path:  /home/dontknowhy/custom-models/models
16:23:50.400 › 🎒 BACKEND REPORTED:  📁 Custom Models Folder Path:  /home/dontknowhy/custom-models/models
16:23:50.400 › 🎒 BACKEND REPORTED:  🔎 Detected Custom Models:  4xHFA2k,4xLSDIR,4xLSDIRCompactC3,4xLSDIRplusC,4xNomos2_otf_esrgan_fp16,4xNomos2_otf_esrgan_fp32,4xNomos8kSC,4xNomos8k_span_otf_medium,4xNomos8k_span_otf_strong,4xNomos8k_span_otf_weak,4xNomosWebPhoto_esrgan_fp16,4xNomosWebPhoto_esrgan_fp32,4xPurePhoto-span,4x_NMKD-Siax_200k,4x_NMKD-Superscale-SP_178000_G,RealESRGAN_General_WDN_x4_v3,RealESRGAN_General_x4_v3,realesr-animevideov3-x2,realesr-animevideov3-x3,realesr-animevideov3-x4,uniscale_restore,unknown-2.0.1
16:23:50.400 › 📜 CUSTOM_MODEL_FILES_LIST:  [
  '4xHFA2k',
  '4xLSDIR',
  '4xLSDIRCompactC3',
  '4xLSDIRplusC',
  '4xNomos2_otf_esrgan_fp16',
  '4xNomos2_otf_esrgan_fp32',
  '4xNomos8kSC',
  '4xNomos8k_span_otf_medium',
  '4xNomos8k_span_otf_strong',
  '4xNomos8k_span_otf_weak',
  '4xNomosWebPhoto_esrgan_fp16',
  '4xNomosWebPhoto_esrgan_fp32',
  '4xPurePhoto-span',
  '4x_NMKD-Siax_200k',
  '4x_NMKD-Superscale-SP_178000_G',
  'RealESRGAN_General_WDN_x4_v3',
  'RealESRGAN_General_x4_v3',
  'realesr-animevideov3-x2',
  'realesr-animevideov3-x3',
  'realesr-animevideov3-x4',
  'uniscale_restore',
  'unknown-2.0.1'
]
```
6. The "Select AI Model" does have these models.(and displays as the json like list above.
7. Select a model.
8. This Upscayl installation is broken.

**Comment by NayamAmarshe** [comment] 2024-12-21 10:01
Aha thanks! So this error occurs because it's trying to look for the model id in the list of default models. Got it. I'll fix this in the release this week. Thanks a lot for the help!

To fix the problem right now, open the dev tools window (Ctrl/Cmd+Shift+I) and delete the following entry of selectedModelId:
<img width="711" alt="image" src="https://github.com/user-attachments/assets/5e541ffe-0899-4785-b4a4-c563408a3601" />

**Comment by NayamAmarshe** [comment] 2024-12-21 10:16
Fixed in latest commit :) Please use the temporary fix for now.

**Comment by aaronliu0130** [comment] 2024-12-26 21:56
@awadrummer @dontknowhy Can you confirm if this issue was fixed by the latest release?

**Comment by NayamAmarshe** [comment] 2024-12-27 02:48
Yes it was :)

**Closed by NayamAmarshe** 2024-12-27 02:48 UTC
Labels: bug
