### ISSUE TITLE
Any docker version?

### ISSUE THREAD

**Issue by xinmans** [upscayl/upscayl#185] opened 2023-01-01 03:45 UTC

**Comment by aaronliu0130** [comment] 2023-01-01 21:46
Duplicate of #55

**Comment by aaronliu0130** [comment] 2023-05-10 12:46
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2023-05-10 12:46 UTC
Labels: duplicate
