### ISSUE TITLE
Custom Models not working

### ISSUE THREAD

**Issue by Lumelore** [upscayl/upscayl#721] opened 2024-02-17 21:46 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).
- [ ] My error involves vkEnumeratePhysicalDevices or vkCreateInstance, which means I should ignore the other issues and file this one despite the last checkbox.

### Describe the Bug

I am trying to use custom models, which I did make sure is ESRGAN. When I convert the .pth the .param does not have the text "input" in the second or third column, it just says "data". I have tried leaving it as is and changing the "data" in the second column to "input.1" (I am not putting quotes around it in the actual file btw). So when I try to use the models in upscayl, it does detect them, but when I try to use them it "finishes" very quickly and of course nothing is in the output folder.
Here is the log: [log.txt](https://github.com/upscayl/upscayl/files/14320223/log.txt)
Here are the models I was trying to use: [Typescale](https://openmodeldb.info/models/8x-NMKD-Typescale), [BSTexty](https://openmodeldb.info/models/2x-BSTexty), [ReFocus](https://openmodeldb.info/models/1x-ReFocus-V3)

This is what the top of the .param file looks like after being outputted from chainner with no modifications.
![data_example](https://github.com/upscayl/upscayl/assets/88530227/d7ecdfa9-800b-4a14-8fce-9da809102a1f)

Here is the modification I tried with the file
![input_example](https://github.com/upscayl/upscayl/assets/88530227/d13b38d6-efdd-4369-9d94-c62f0444ca2d)

I did try using both the newest version of chainner and version 0.21.0 and I noticed no difference in their outputs.

### To Reproduce

1. Download .pth for custom model
2. Use the model conversion guide to create .bin and .param
3. Try to use them upscayl
4. It will "finish" very quickly and nothing will be in the output folder

### Upscayl Version (or commit hash)

2.9.9

### Platform

Linux

### OS Version

Linux Mint 21.3

### GPU Name

NVIDIA RTX 3060

### Expected Behavior

The output folder should have contained upscaled images instead of nothing.

### Logs

```sh
[log.txt](https://github.com/upscayl/upscayl/files/14320223/log.txt)
```

**Comment by aaronliu0130** [comment] 2024-02-17 23:49
Duplicate of #690
> I have searched for my issue in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-02-17 23:49 UTC
Labels: bug

**Comment by Lumelore** [comment] 2024-02-18 00:05
I did search for it!! Literally nothing came up when I did, I swear! Please
reverse rick roll me.

**Comment by NayamAmarshe** [comment] 2024-02-18 06:42
It's happening because upscayl-ncnn currently only supports x4 models😅

**Comment by aaronliu0130** [comment] 2024-02-18 17:45
Well, that's also a reason, but as shown in the screenshots chaiNNer's output got weird, which is affecting all models rn
