### ISSUE TITLE
Bath Processing On Windows Results In mosaic

### ISSUE THREAD

**Issue by muv01** [upscayl/upscayl#321] opened 2023-05-14 11:17 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

<details>
Running on Windows 11, v2.5.1

Im trying to upscale a batch of images.  It works perfectly when I run upscaller one by one.  But when I use the batch processor the output is comletly different.  What outputs is the orignal image, but on mosaic format, split into tiles.  Each of the tiles is completly jumbled up.

I have changed any of the default options, as all I want to do is increase the image resoltuon, but to test I have tried different themes and dozens of different input images.

<summary>Logs</summary>
<pre>

</pre>
</details>

### To Reproduce

create a folder with some images in, set it to BATCH mode

### Expected Behavior

Images upscalled into a seperate folder

### Version/Commit Hash

2.5.1

### OS Specifics

win11

### Screenshots

![hamd01_someone_fitting_a_new_battery_to_an_electric_bike_03509cbe-05de-43b3-84d5-2c90a4345aa8_upscayl_2x_realesrgan-x4plus](https://github.com/upscayl/upscayl/assets/133573981/9ba08185-1047-4d77-a554-fd6be2c1604c)

**Comment by NayamAmarshe** [comment] 2023-05-14 11:44
Duplicate of #303

**Closed by NayamAmarshe** 2023-05-14 11:44 UTC
Labels: bug
