### ISSUE TITLE
Publish to HomeBrew

### ISSUE THREAD

**Issue by Goooler** [upscayl/upscayl#270] opened 2023-04-11 15:45 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

Publish the cask to HomeBrew to be easier to install and update.

### Alternatives

Nope.

**Comment by aaronliu0130** [comment] 2023-04-11 17:43
Duplicate of #191 and #34. This is currently blocked by our unwillingness to pay $99 a year for code signing.
> I have checked that this issue isn't addressed in any other issue or pull request.

![gifgit](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Comment by NayamAmarshe** [comment] 2023-04-14 02:03
I'd probably publish Upscayl on AppStore instead ;)

**Comment by aaronliu0130** [comment] 2023-04-14 13:53
If you're talking about the mac app store, I'm pretty sure that also requires $99 a year.

**Comment by NayamAmarshe** [comment] 2023-04-14 14:40
> If you're talking about the mac app store, I'm pretty sure that also requires $99 a year.

That's alright :)

**Comment by pavelzw** [comment] 2023-09-17 14:14
I have upscayl on my personal homebrew tap. You can install it using `brew install --no-quarantine pavelzw/pavelzw/upscayl`

Cask code: https://github.com/pavelzw/homebrew-pavelzw/blob/main/Casks/upscayl.rb

**Comment by NayamAmarshe** [comment] 2023-09-18 06:43
> I have upscayl on my personal homebrew tap. You can install it using `brew install --no-quarantine pavelzw/pavelzw/upscayl`
> 
> Cask code: https://github.com/pavelzw/homebrew-pavelzw/blob/main/Casks/upscayl.rb

Is it possible to make it official?

**Comment by pavelzw** [comment] 2023-09-18 06:51
Sure, we can also move it in this organization. For this, we need a separate repository in this organization called `homebrew-<tapname>`, for example `homebrew-upscayl`. When we put the cask code there, we will be able to install it via `brew install --no-quarantine upscayl/upscayl/upscayl` or via

```bash
$ brew tap upscayl/upscayl
$ brew install --no-quarantine upscayl
```

**Comment by akrabu** [comment] 2024-04-26 17:10
I think the SHA256 hash needs updated for the latest release...

```
Error: upscayl: SHA256 mismatch
Expected: 8cd9db46126d8108d99df0da9356748e0d1a13b877a5ed017ce2e56804e85eb1
  Actual: 632506a5d5c92593ac9f81707c067c0846d1b80647b3b3864748a9839d6dcfab
    File: /Users/akrabu/Library/Caches/Homebrew/downloads/47b6f106ffe3290c80bc1fb4534891646119ca5c2e743273dedf9d80554c3970--upscayl-2.11.0-mac.dmg
```

**Comment by aaronliu0130** [comment] 2024-04-26 19:10
It's open source. You may be the one to change that!

**Comment by akrabu** [comment] 2024-04-26 20:53
This is fair - and I would, if I knew how 😅

**Comment by NayamAmarshe** [comment] 2024-04-26 21:00
Hi @pavelzw I've invited you to the repository https://github.com/upscayl/homebrew-upscayl/

Sorry for delaying it for so long 🙏

**Comment by aaronliu0130** [comment] 2024-04-26 21:12
There's a homebrew cask in homebrew's official repos, I don't think we need to make a separate repository for this. There's a contributing guide and I'm going to start bumping the shasum now.

**Comment by NayamAmarshe** [comment] 2024-04-26 21:13
> There's a homebrew cask in homebrew's official repos, I don't think we need to make a separate repository for this. There's a contributing guide and I'm going to start bumping the shasum now.

I think it's still good to have it under the org, just in case. Individual contributions are always welcome of course but if we can make it official, it's better for everyone.

**Comment by aaronliu0130** [comment] 2024-04-26 21:15
Homebrew Casks are usually centralized in https://github.com/Homebrew/homebrew-cask, where I did submit 2.9.9 a couple months ago. In my opinion, duplicated work across different repositories isn't very good. I don't see how this is individual vs official.

**Comment by NayamAmarshe** [comment] 2024-04-26 21:22
> Homebrew Casks are usually centralized in https://github.com/Homebrew/homebrew-cask, where I did submit 2.9.9 a couple months ago, which allows for installation without adding additional sources. In my opinion, duplicated work across different repositories isn't very good. I don't see how this is individual vs official.

Ah ok, sorry I misunderstood how it works then.

**Closed by NayamAmarshe** 2024-04-26 21:22 UTC
Labels: duplicate, enhancement
