### ISSUE TITLE
Drag and drop folder into Batch Upscayl

### ISSUE THREAD

**Issue by 4pii4** [upscayl/upscayl#386] opened 2023-07-05 11:34 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the Wiki](https://github.com/upscayl/upscayl/wiki).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

1. Make the `Batch Upscale` button have a different background color when activated
2. Add the ability to drag and drop folder in batch upscale mode instead of having to select them manually
3. Add some kind of total conversion progress in batch upscale mode, for example: Processing file `19.png`, 19/50 completed.

**Comment by aaronliu0130** [comment] 2023-07-06 00:40
I don't see why 1 is needed
3 is a duplicate of #130 
![compulsory rickrolls are issued for duplicates of other issues and the FAQ](https://github.com/upscayl/upscayl/assets/11874211/1b6870c9-bc20-419b-8f08-e4f77db239e5)

**Comment by NayamAmarshe** [comment] 2023-09-09 13:33
This isn't possible at the moment. Only images can be dropped, not folders.

**Closed by NayamAmarshe** 2023-09-09 13:33 UTC
Labels: enhancement

**Comment by aaronliu0130** [comment] 2023-09-09 14:27
At least on Windows and Arch I can.
![image](https://github.com/upscayl/upscayl/assets/11874211/8e64a09a-a050-4a79-bda7-0d918d0ffd17)

**Comment by aaronliu0130** [comment] 2023-11-07 16:45
What does dropping a folder look like on your machine?

**Comment by 4pii4** [comment] 2023-12-09 05:31
> What does dropping a folder look like on your machine?

This is only 1 part of the story. On my machine, when I try to drag and drop a folder in Batch upscale mode it just tell me 'Please drag and drop an image'. Also dragging an image into Batch upscale set that image as the target for single upscale for some reason.

https://github.com/upscayl/upscayl/assets/138131197/819be8dd-e8cc-4f62-a8f7-ecebe2ebc562

**Comment by aaronliu0130** [comment] 2023-12-09 17:44
No, what I mean is that at least on Windows and Arch the software should be able to recognize folders you've dropped in. Since we only support drop and drop for normal Upscayl, it'll switch to that mode, which is expected.
