### ISSUE TITLE
Transparent image bug

### ISSUE THREAD

**Issue by Arka078** [upscayl/upscayl#237] opened 2023-03-04 18:33 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#faq-).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Describe the Bug

it creates a green background in photos with transparent backgrounds images

### To Reproduce

upscale an transparent photo

### Expected Behavior

it should upscale transparent images with transparent background

### Version/Commit Hash

2.0.1

### OS Specifics

windows

### Screenshots

![1](https://user-images.githubusercontent.com/103723488/222922837-c32c330d-3abb-4e68-be57-8538d3c89be8.png)

**Comment by NayamAmarshe** [comment] 2023-03-05 01:59
Did you try other models?

**Comment by Arka078** [comment] 2023-03-05 15:08
Yes, I have tried the same bug across all modules.

**Comment by aaronliu0130** [comment] 2023-03-05 15:18
If you don’t have logs, you may follow these instructions: Download and install git from https://git-scm.com/download (note that git is bundled with macOS) and node from https://nodejs.org/en/download/current/ (choose standalone installer 64 for both) then run these in your terminal (if you don't know what this is, search and open an app on your computer called "Command Prompt" or "cmd" for short):
```sh
git clone https://github.com/TGS963/upscayl
cd upscayl
npm install
npm run start
```
After the last command, upscayl should show up. Reproduce the error and send out the terminal output. `npm` will tell you about audit errors. These are due to #54 and currently expected.

**Comment by Arka078** [comment] 2023-03-05 19:00
It shows like this 


≡ƒÜÇ ICON PATH:  I:\Downloads\upscayl\main\build\icon.png
≡ƒÜÇ UPSCAYL EXEC PATH:  I:\Downloads\upscayl\resources\win\bin\upscayl-
≡ƒÜÇ MODELS PATH:  I:\Downloads\upscayl\resources\models
≡ƒÜÇ FFMPEG PATH:  I:\Downloads\upscayl\node_modules\upscayl-ffmpeg\bin\win\x64\ffmpeg.exe
wait  - compiling / (client and server)...
event - compiled client and server successfully in 996 ms (288 modules)
≡ƒÜÇ => fileName 1
≡ƒÜÇ => fileExt .png
≡ƒÜÇ => fileName 1
≡ƒÜÇ => fileExt .png
≡ƒÜÇ => fileName 1123213
≡ƒÜÇ => fileExt .png
≡ƒåÖ COMMAND:  -i C:\Users\yoy\Desktop/1123213.png -o C:\Users\yoy\Desktop/1123213_upscayl_4x_realesrgan-x4plus.png -s 4 -m I:\Downloads\upscayl\resources\models -n realesrgan-x4plus  -f png
≡ƒÜÇ => upscayl.stderr.on => stderr.toString() [0 NVIDIA GeForce RTX 3050]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce RTX 3050]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce RTX 3050]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce RTX 3050]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 0.00%

≡ƒÜÇ => upscayl.stderr.on => stderr.toString() 50.00%

Done upscaling
[24524:0306/002832.950:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by aaronliu0130** [comment] 2023-03-05 22:45
Weird, looks pretty normal.

**Comment by NayamAmarshe** [comment] 2023-03-06 02:01
@Arka078 Could you send me the image? It's either the image that's causing it or your hardware. I've tested multiple PNGs before, they work just fine.

**Comment by Arka078** [comment] 2023-03-06 11:50
Yes, of course, here it is.
![1123213](https://user-images.githubusercontent.com/103723488/223102263-8abe8e29-c278-4d11-a2a3-bf7704227bbb.png)

**Comment by NayamAmarshe** [comment] 2023-03-07 03:14
@Arka078 It's your hardware causing the issue. So for now I'm closing the issue. You probably need a driver update or a hardware upgrade/change.
![image](https://user-images.githubusercontent.com/25067102/223311076-4cc7ab3e-983e-4555-9281-e8224b1838b2.png)

**Closed by NayamAmarshe** 2023-03-07 03:14 UTC
Labels: bug
