### ISSUE TITLE
[VULKAN] vkQueueSubmit failed -4

### ISSUE THREAD

**Issue by ANRTNT** [upscayl/upscayl#948] opened 2024-08-28 14:52 UTC
### Checklist

- [X] I have **tried ALL** of the steps mentioned in the [troubleshooting guide](https://github.com/upscayl/upscayl/wiki/Troubleshooting).
- [X] I have **searched** for this in the [issues tab](https://github.com/upscayl/upscayl/issues?q=).

### Describe the Bug

I didn't have the problem in my previous batches and I have tried every possibility of a solution 

### To Reproduce

Batch Folder

### Upscayl Version (or commit hash)

2.11.5

### Platform

Windows

### OS Version

Windows 10

### GPU Name

GTX 1650

### Screenshots

![image](https://github.com/user-attachments/assets/1a13d41d-f5c1-40aa-81b0-2d62448acf35)

### Logs

```sh
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Blender exports\Fanta Test\0001.png
🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Blender exports\Fanta Test\0001.png
🖼 Selected Image Path:  E:\Blender exports\Fanta Test\0001.png
📁 Selected Image Directory:  E:\Blender exports\Fanta Test
🖼 imagePath:  E:\Blender exports\Fanta Test\0001.png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🎒 BACKEND REPORTED:  ✅ Upscayl Variables:  {"model":"ultramix_balanced","gpuId":null,"saveImageAs":"jpg","inputDir":"E:\\Blender exports\\Fanta Test","fileNameWithExt":"0001.png","outputDir":"E:\\Blender exports\\Fanta Test","outFile":"E:\\Blender exports\\Fanta Test\\0001_upscayl_4x_ultramix_balanced.jpg","fileName":"0001","scale":"4","compression":"0","customWidth":"","useCustomWidth":false,"tileSize":512}
🎒 BACKEND REPORTED:  📢 Upscayl Command:  -i,E:\Blender exports\Fanta Test\0001.png,-o,E:\Blender exports\Fanta Test\0001_upscayl_4x_ultramix_balanced.jpg,-m,E:\Upscayl\resources\models,-n,ultramix_balanced,-f,jpg,-c,0,-t,512
🎒 BACKEND REPORTED:  👶 Updating Child Processes:  {"binary":"E:\\Upscayl\\resources\\bin\\upscayl-bin","args":["E:\\Upscayl\\resources\\bin\\upscayl-bin","-i","E:\\Blender exports\\Fanta Test\\0001.png","-o","E:\\Blender exports\\Fanta Test\\0001_upscayl_4x_ultramix_balanced.jpg","-m","E:\\Upscayl\\resources\\models","-n","ultramix_balanced","-f","jpg","-c","0","-t","512"]}
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  false
🎒 BACKEND REPORTED:  [0 NVIDIA GeForce GTX 1650]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1650]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1650]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1650]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 NVIDIA GeForce GTX 1650]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[0 NVIDIA GeForce GTX 1650]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 NVIDIA GeForce GTX 1650]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 NVIDIA GeForce GTX 1650]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1

🎒 BACKEND REPORTED:  vkAllocateMemory failed -2

🚧 UPSCAYL_PROGRESS:  vkAllocateMemory failed -2

🎒 BACKEND REPORTED:  vkAllocateMemory failed -2

🚧 UPSCAYL_PROGRESS:  vkAllocateMemory failed -2

🎒 BACKEND REPORTED:  vkWaitForFences failed -4

🚧 UPSCAYL_PROGRESS:  vkWaitForFences failed -4

🎒 BACKEND REPORTED:  0.00%

🚧 UPSCAYL_PROGRESS:  0.00%

🎒 BACKEND REPORTED:  vkQueueSubmit failed -4

🚧 UPSCAYL_PROGRESS:  vkQueueSubmit failed -4

🎒 BACKEND REPORTED:  25.00%

🚧 UPSCAYL_PROGRESS:  25.00%

🎒 BACKEND REPORTED:  vkQueueSubmit failed -4
vkQueueSubmit failed -4

🚧 UPSCAYL_PROGRESS:  vkQueueSubmit failed -4
vkQueueSubmit failed -4

🎒 BACKEND REPORTED:  vkQueueSubmit failed -4

🚧 UPSCAYL_PROGRESS:  vkQueueSubmit failed -4

🎒 BACKEND REPORTED:  50.00%

🚧 UPSCAYL_PROGRESS:  50.00%

🎒 BACKEND REPORTED:  vkQueueSubmit failed -4

🚧 UPSCAYL_PROGRESS:  vkQueueSubmit failed -4

🎒 BACKEND REPORTED:  75.00%
vkQueueSubmit failed -4

🚧 UPSCAYL_PROGRESS:  75.00%
vkQueueSubmit failed -4

🎒 BACKEND REPORTED:  100.00

🙌 Upscayled Successfully!

🚧 UPSCAYL_PROGRESS:  100.00

🙌 Upscayled Successfully!

🎒 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  E:\Blender exports\Fanta Test\0001_upscayl_4x_ultramix_balanced.jpg
💯 UPSCAYL_DONE:  E:\Blender exports\Fanta Test\0001_upscayl_4x_ultramix_balanced.jpg
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🎒 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🖼️ Updating Image Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\0271.png
🖼 Selected Image Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\0271.png
📁 Selected Image Directory:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%
🖼 imagePath:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\0271.png
🔤 Extension:  png
🎒 BACKEND REPORTED:  📄 Selected File Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\0271.png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🔄 Resetting Upscaled Image Path
🚫 No valid image selected
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Ultramix Balanced)","value":"ultramix_balanced"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to ultramix_balanced
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
🔀 Model changed:  ultrasharp
🔀 Setting model to ultrasharp
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🚫 No valid image selected
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
🛑 Stopping Upscayl
🔄 Resetting image paths
🎒 BACKEND REPORTED:  🛑 Updating Stopped:  true
🎒 BACKEND REPORTED:  🛑 Stopping Upscaling Process 10332
🔄 Resetting image paths
🎒 BACKEND REPORTED:  📁 Updating Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🎒 BACKEND REPORTED:  📁 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
🖼 Selected Folder Path:  E:\Blender exports\Headphone Scene 1 & 2\jpg 50%\Processed
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 FOLDER_UPSCAYL
⚙️ Getting saveImageAs from localStorage:  jpg
⚙️ Getting model from localStorage:  {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
```

**Comment by NayamAmarshe** [comment] 2024-08-29 05:26
Duplicate of #943

**Closed by NayamAmarshe** 2024-08-29 05:26 UTC
Labels: bug, vulkan
