### ISSUE TITLE
Support the new state of the art image upscale: SUPIR

### ISSUE THREAD

**Issue by driqeks** [upscayl/upscayl#731] opened 2024-02-28 03:30 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.

### Description

SUPIR is a new open source image upscale model, much better than anything before: https://github.com/Fanghua-Yu/SUPIR

Two Minute Papers video about it: https://www.youtube.com/watch?v=POJ1w8H8OjY

**Comment by aaronliu0130** [comment] 2024-02-28 12:50
Duplicate of #689
> I have checked that this issue isn't addressed in any other issue or pull request.

![compulsory rickrolls are issued for duplicates of issues and the FAQ](https://user-images.githubusercontent.com/11874211/218282922-efab6795-84af-4cfb-9400-c28c8729ea78.gif)

**Closed by aaronliu0130** 2024-02-28 12:50 UTC
Labels: enhancement

**Comment by driqeks** [comment] 2024-03-04 23:56
> Duplicate of #689
> 
> > I have checked that this issue isn't addressed in any other issue or pull request.
> 
> ![compulsory rickrolls are issued for duplicates of issues and the FAQ]

I did check all the open issues, I would never have imagined that there would be a closed issue about it...

If you keep this project Real-ESRGAN only, then Upscayl will unfortunately quickly fade into irrelevance, Real-ESRGAN is just no longer up to date and there is better tech now.

**Comment by aaronliu0130** [comment] 2024-03-04 23:58
The repo claims it has a (V)RAM consumption of 60 gigs, and it's in Python, which would require us to install a ton of stuff.

**Comment by lrq3000** [comment] 2024-04-12 01:28
@aaronliu0130 Not anymore, it works with a newer compressed model of SUPIR and [this workflow](https://openart.ai/workflows/seven947/1minute-8k-upscale/1IPTks1gL7v0EPmvsMcx), it even works on my GeForce RTX 3060 Laptop with 6GB VRAM (although it takes ~20 min to process for me).

Worth noting the workflow author also [mentions](https://www.youtube.com/watch?v=sCJqmasct_c) in the same youtube video the [APISR](https://github.com/Kiteretsu77/APISR) which is a SOTA anime upscaler and apparently it can work in real-time.

**Comment by aaronliu0130** [comment] 2024-04-12 02:12
That's good news. Still, Python is a non-starter.
