### ISSUE TITLE
small black image? nothing saved, confused how to make work.

### ISSUE THREAD

**Issue by splace** [upscayl/upscayl#426] opened 2023-08-25 00:50 UTC
### Checklist

- [X] I have checked that this issue isn't addressed in [the FAQ](https://github.com/upscayl/upscayl#-faq).
- [X] I have checked that this issue isn't addressed in any other issue or pull request.
- [X] I have tried [setting my GPU ID](https://github.com/upscayl/upscayl/wiki/Guide#gpu-id).

### Paste the logs

<details><summary>Logs</summary><pre>
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"Digital Art","value":"realesrgan-x4plus-anime"}
⚙️ Setting gpuId to empty string
🔀 Setting model to 
🔄 Resetting image paths
🔀 Setting model to realesrgan-x4plus-anime
🔄 Resetting image paths
🐞 BACKEND REPORTED:  📄 Selected File Path:  /run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png
🖼 Selected Image Path:  /run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png
📁 Selected Image Directory:  /run/user/1000/doc/c16dbe65
🖼 imagePath:  /run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png
🔤 Extension:  png
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png,-o,/run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus-anime.jpg,-s,2,-m,/app/upscayl/resources/models,-n,realesrgan-x4plus-anime,,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:32:36.135] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:32:36.135] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:32:36.139] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:32:36.139] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:32:36.140] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:32:36.140] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🐞 BACKEND REPORTED:  image upscayl:  sh: line 1: glxinfo: command not found

🚧 UPSCAYL_PROGRESS:  sh: line 1: glxinfo: command not found

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:32:36.246] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:32:36.246] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🐞 BACKEND REPORTED:  image upscayl:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:32:36.423] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:32:36.423] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🐞 BACKEND REPORTED:  image upscayl:  LLVM ERROR: Cannot select: 0x7fd94822b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7fd9482118f0, FrameIndex:i64<10>
  0x7fd9482119c0: i64 = FrameIndex<10>
In function: cs_co_variant

🚧 UPSCAYL_PROGRESS:  LLVM ERROR: Cannot select: 0x7fd94822b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7fd9482118f0, FrameIndex:i64<10>
  0x7fd9482119c0: i64 = FrameIndex<10>
In function: cs_co_variant

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  /run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus-anime.jpg
🔀 Model changed:  realesrgan-x4plus
🔀 Setting model to realesrgan-x4plus
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png,-o,/run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,/app/upscayl/resources/models,-n,realesrgan-x4plus,,,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]
[2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]
[2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]
[2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]
[2023-08-25 01:33:33.343] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🐞 BACKEND REPORTED:  image upscayl:  sh: line 1: glxinfo: command not found

🚧 UPSCAYL_PROGRESS:  sh: line 1: glxinfo: command not found

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:33:33.491] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:33:33.491] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🐞 BACKEND REPORTED:  image upscayl:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:33:33.650] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:33:33.650] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🐞 BACKEND REPORTED:  image upscayl:  LLVM ERROR: Cannot select: 0x7f83d422b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7f83d4210ef0, FrameIndex:i64<10>
  0x7f83d4210fc0: i64 = FrameIndex<10>
In function: cs_co_variant

🚧 UPSCAYL_PROGRESS:  LLVM ERROR: Cannot select: 0x7f83d422b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7f83d4210ef0, FrameIndex:i64<10>
  0x7f83d4210fc0: i64 = FrameIndex<10>
In function: cs_co_variant

🐞 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🐞 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🐞 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🐞 BACKEND REPORTED:  🚫 Select Folder Operation Cancelled
🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  /run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Setting gpuId to empty string
⚙️ Getting rememberOutputFolder from localStorage false
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0
🔀 Setting model to 
🔀 Setting model to realesrgan-x4plus
🐞 BACKEND REPORTED:  📁 Selected Folder Path:  /var/home/simon/Downloads
🗂 Setting Output Path:  /var/home/simon/Downloads
🧠 Remembering Output Folder:  /var/home/simon/Downloads
🔄 Resetting Upscaled Image Path
🏁 UPSCAYL
🐞 BACKEND REPORTED:  📢 Upscayl Command:  -i,/run/user/1000/doc/c16dbe65/32(0,0)-(1,1)(0,0).png,-o,/var/home/simon/Downloads/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus.jpg,-s,2,-m,/app/upscayl/resources/models,-n,realesrgan-x4plus,-g,0,-f,jpg
🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]
[2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]
[2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/app/upscayl/resources/bin/MangoHud.conf' [ not found ]
[2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/upscayl-realesrgan.conf' [ not found ]
[2023-08-25 01:42:23.003] [MANGOHUD] [info] [config.cpp:118] skipping config: '/var/home/simon/.var/app/org.upscayl.Upscayl/config/MangoHud/MangoHud.conf' [ not found ]

🐞 BACKEND REPORTED:  image upscayl:  sh: line 1: glxinfo: command not found

🚧 UPSCAYL_PROGRESS:  sh: line 1: glxinfo: command not found

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:42:23.109] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:42:23.109] [MANGOHUD] [error] [cpu.cpp:568] Failed to initialize CPU power data

🐞 BACKEND REPORTED:  image upscayl:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🚧 UPSCAYL_PROGRESS:  [0 llvmpipe (LLVM 15.0.7, 128 bits)]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  fp16-p/s/a=1/1/0  int8-p/s/a=1/1/1
[0 llvmpipe (LLVM 15.0.7, 128 bits)]  subgroup=4  basic=1  vote=1  ballot=1  shuffle=1

🐞 BACKEND REPORTED:  image upscayl:  [2023-08-25 01:42:23.185] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🚧 UPSCAYL_PROGRESS:  [2023-08-25 01:42:23.185] [MANGOHUD] [info] [overlay.cpp:808] Uploading is disabled (permit_upload = 0)

🐞 BACKEND REPORTED:  image upscayl:  LLVM ERROR: Cannot select: 0x7fe56822b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7fe568210ef0, FrameIndex:i64<10>
  0x7fe568210fc0: i64 = FrameIndex<10>
In function: cs_co_variant

🚧 UPSCAYL_PROGRESS:  LLVM ERROR: Cannot select: 0x7fe56822b1d0: i16,ch = X86ISD::FILD<(load (s16) from %stack.10)> 0x7fe568210ef0, FrameIndex:i64<10>
  0x7fe568210fc0: i64 = FrameIndex<10>
In function: cs_co_variant

🐞 BACKEND REPORTED:  💯 Done upscaling
upscaledImagePath:  
💯 UPSCAYL_DONE:  /var/home/simon/Downloads/32(0,0)-(1,1)(0,0)_upscayl_2x_realesrgan-x4plus.jpg
⚙️ Getting saveImageAs from localStorage jpg
⚙️ Getting model from localStorage {"label":"General Photo (Real-ESRGAN)","value":"realesrgan-x4plus"}
⚙️ Getting gpuId from localStorage 0
⚙️ Getting rememberOutputFolder from localStorage false
</pre></details>

### Describe the Bug

![image](https://github.com/upscayl/upscayl/assets/1234848/997cd6e8-0f83-4ab1-ad3b-c0e4e836b8bf)

### To Reproduce

never work

### Version/Commit Hash

2.5.5

### OS Specifics

flatpak with llvm

**Comment by NayamAmarshe** [comment] 2023-08-25 08:28
Do you have a GPU?

**Comment by aaronliu0130** [comment] 2023-08-25 14:38
Possible duplicate of #354

**Comment by NayamAmarshe** [comment] 2023-09-01 15:39
Please

**Closed by NayamAmarshe** 2023-09-01 15:39 UTC
Labels: bug
